### PR TITLE
Add unobtainable Gen 9 Egg moves

### PR DESCRIPTION
**Pull request by DaWoblefet**
See https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9416548

### CODE REVIEW

**Comment by DaWoblefet** [comment]
Actually this doesn't work either, because obtainablemoves is gonna backport with inheritance. I tried to mirror what we did for BDSP, but this isn't really a good solution either.

**Comment by Karthik99999** [comment]
Can't you just make the banlist an empty array in Gen 8?

**Comment by KrisXV** [comment]
> Marking them as unobtainable would work, but then STABmons people would get mad bc unobtainable moves are banned from that format (even though other hisuian moves aren’t banned bc they aren’t marked as unobtainable for some reason)

Why are you trying to bring OM philosophy into this? Regardless, I don’t like the unobtainable approach since that’s not something we’ve done in the past either.

**Comment by DaWoblefet** [comment]
I think the correct solution would be, for Gen 8+, check if any obtainable Pokemon learn the move from a non-Egg source. I'll see if that's feasible or not to do.

**Comment by DaWoblefet** [comment]
> I think the correct solution would be, for Gen 8+, check if any obtainable Pokemon learn the move from a non-Egg source. I'll see if that's feasible or not to do.

It probably is, but beyond the scope of what I want to do. Even if we did get this working, we'd have to hardcode in events or something to handle the cases like Shroodle getting Cross Poison or the Mareep line getting Electroweb.

**Comment by DaWoblefet** [comment]
Superseded by https://github.com/smogon/pokemon-showdown/pull/9096

**Pull request closed without merging**
