### PR TITLE
Fix /avatar reply

### PR DESCRIPTION
**Pull request by iscke**

### CODE REVIEW

**Comment by whalemer** [comment]
insist's latest refactor made it a replybox with newlines

**Comment by Zarel** [comment]
ReplyBox should maybe auto-convert newlines to `<br />`

**Comment by Zarel** [comment]
Or to whitespace, tbh. Stripping whitespace probably makes more sense in HTML.

Except in `<pre>` blocks... In hindsight there's not a good way to deal with them.

**Comment by whalemer** [comment]
yeah IMO if you're passing newlines to replybox you should fix it where you're passing them, not in replybox

**Pull request merged**
