### PR TITLE
Update pokedex.ts

### PR DESCRIPTION
**Pull request by smell-of-curry**
Fixed Salazzle Evolution, to require to be female.

### CODE REVIEW

**Comment by DaWoblefet** [comment]
Combee is also like this if you'd like to get that as well while we're updating both.

**Comment by DaWoblefet** [comment]
Wait a minute, is ``evoGender`` even a property we support?

**Comment by smell-of-curry** [comment]
> Wait a minute, is `evoGender` even a property we support?

Oh wait, I added special typings for `evoGender`, `evoMoveUseTimes` and `evoTime`. There are a lot of evolutions that are broken without these

```ts
  /** Evolution gender. */
  declare readonly evoGender?: "M" | "F";
  /** Evolution move use times. Pokemon Must use the moves this amount of times */
  readonly evoMoveUseTimes?: number;
  /** Time required for the evolution. */
  readonly evoTime?: "day" | "night";
  ```

**Comment by DaWoblefet** [comment]
If you want to add a new property like that, you'd need to add support for that new property in various places that use it then (such as the data command). As it is, you can't just add a new property to a Pokemon like this without adding it in all the other necessary places too.

**Comment by DaWoblefet** [comment]
Closing this for now since it's been inactive, but if you would like to pursue adding these properties, you can.

**Pull request closed without merging**
