### PR TITLE
Chat commands: Make /sendhtmlpage multiline

### PR DESCRIPTION
**Pull request by mia-pi-git**
300 characters is... not enough for most bot owners to do anything much.

### CODE REVIEW

**Comment by whalemer** [comment]
have you actually tried to send more than 300 chars? it's not a chat message, so the 300 char limit doesn't apply to it.

**Comment by mia-pi-git** [comment]
> have you actually tried to send more than 300 chars? it's not a chat message, so the 300 char limit doesn't apply to it.

Odd, i was told by @KrisXV that it was failing. Don't have a bot, can't test it on main personally.

**Comment by KrisXV** [comment]
@whalemer I have, it doen't work with more than 300 characters via my bot.

**Comment by mia-pi-git** [comment]
Oh, i misunderstood what i was told then. 
This requires more investigation.

**Comment by AnnikaCodes** [comment]
image
It seems to work fine for me.

**Comment by mia-pi-git** [comment]
Okay well apparently there was a large miscommunication here.
Closing.

**Comment by KrisXV** [comment]
yeah it turns out im an idiot and my bot auto truncates

**Pull request closed without merging**
