### PR TITLE
Allow bots to do calcs

### PR DESCRIPTION
**Pull request by NicoDeVang**
Hello,

I'm currently using the _@smogon/calc_ API to allow my Showdown bot to do some calcs. The problem is that there are many annoying things which are not working as I want (Ditto, Aegislash, multi strikes moves...). **But** I figured out that we have the exact same function in "battle.ts" which is called "getDamage". So we don't need any external calculator, and that's right: **why would we use any external thing when we have the code behind our eyes?**

The problem is that this function has some RNG inside it.
`moveHit.crit = this.randomChance(1, critMult[critRatio]);` (line 2103)

My idea would be simply to split this function in two parts:
_getCustomRNGDamage()_-> Takes the original code of getDamage() and simply remove the RNG part and put it in arguments of this new function
_getDamage()_ -> Calling the function getCustomRNGDamage() and put it some RNG inside like rolls/crits...

It's very easy, it has 0 impact on the code, 0 addition/0 deletion, only a simple split. And this simple split would allow any AI to do calcs directly on Showdown, and maybe learn how to play Pokémon :)

Thank you,

NDV

Edit: It seems I made a mistake with commits... I'm not sure if I can edit/remove the "merge"... I'm really not familiar with Git, sorry :/

### CODE REVIEW

**Comment by AnnikaCodes** [comment]
It looks like you messed up a rebase or something; this PR contains a lot of irrelevant commits from other people.

**Comment by AnnikaCodes** [comment]
Wait, this isn't even your branch.

You have to actually fork PS and make your own changes to the code in a branch on your repository; this branch is from an old change made by someone else.

**Comment by Zarel** [comment]
Your idea might be good, though. Can you just copy/paste your changed code here? That would probably be simplest, if you don't know Git.

**Comment by NicoDeVang** [comment]
> Your idea might be good, though. Can you just copy/paste your changed code here? That would probably be simplest, if you don't know Git.

Hi Zarel,

Firstly, we have to add an argument in the end of the _randomizer_ function, which will have 0 impact on current code (as it’s undefined all the time).

```
	randomizer(baseDamage: number**, rng: number**) {
		const tr = this.trunc;
		return tr(tr(baseDamage * (100 - **(rng === undefined?this.random(16):rng)**)) / 100);
	}
```

Then, exact same thing for modifyDamage: we have to add an argument in the end, which again has 0 impact on the current code as it’s never called. We call randomizer with this new argument.

```
	modifyDamage(
		baseDamage: number, pokemon: Pokemon, target: Pokemon, move: ActiveMove, suppressMessages = false**, rng: number**
	) {
		const tr = this.trunc;
		if (!move.type) move.type = '???';
		const type = move.type;

		baseDamage += 2;

		// multi-target modifier (doubles only)
		if (move.spreadHit) {
			const spreadModifier = move.spreadModifier || (this.gameType === 'free-for-all' ? 0.5 : 0.75);
			this.debug('Spread modifier: ' + spreadModifier);
			baseDamage = this.modify(baseDamage, spreadModifier);
		}

		// weather modifier
		baseDamage = this.runEvent('WeatherModifyDamage', pokemon, target, move, baseDamage);

		// crit - not a modifier
		const isCrit = target.getMoveHitData(move).crit;
		if (isCrit) {
			baseDamage = tr(baseDamage * (move.critModifier || (this.gen >= 6 ? 1.5 : 2)));
		}

		// random factor - also not a modifier
		baseDamage = this.randomizer(baseDamage**,rng**);

		// STAB
		if (move.forceSTAB || (type !== '???' && pokemon.hasType(type))) {
			// The "???" type never gets STAB
			// Not even if you Roost in Gen 4 and somehow manage to use
			// Struggle in the same turn.
			// (On second thought, it might be easier to get a MissingNo.)
			baseDamage = this.modify(baseDamage, move.stab || 1.5);
		}
		// types
		let typeMod = target.runEffectiveness(move);
		typeMod = this.clampIntRange(typeMod, -6, 6);
		target.getMoveHitData(move).typeMod = typeMod;
		if (typeMod > 0) {
			if (!suppressMessages) this.add('-supereffective', target);

			for (let i = 0; i < typeMod; i++) {
				baseDamage *= 2;
			}
		}
		if (typeMod < 0) {
			if (!suppressMessages) this.add('-resisted', target);

			for (let i = 0; i > typeMod; i--) {
				baseDamage = tr(baseDamage / 2);
			}
		}

		if (isCrit && !suppressMessages) this.add('-crit', target);

		if (pokemon.status === 'brn' && move.category === 'Physical' && !pokemon.hasAbility('guts')) {
			if (this.gen < 6 || move.id !== 'facade') {
				baseDamage = this.modify(baseDamage, 0.5);
			}
		}

		// Generation 5, but nothing later, sets damage to 1 before the final damage modifiers
		if (this.gen === 5 && !baseDamage) baseDamage = 1;

		// Final modifier. Modifiers that modify damage after min damage check, such as Life Orb.
		baseDamage = this.runEvent('ModifyDamage', pokemon, target, move, baseDamage);

		if (move.isZOrMaxPowered && target.getMoveHitData(move).zBrokeProtect) {
			baseDamage = this.modify(baseDamage, 0.25);
			this.add('-zbroken', target);
		}

		// Generation 6-7 moves the check for minimum 1 damage after the final modifier...
		if (this.gen !== 5 && !baseDamage) return 1;

		// ...but 16-bit truncation happens even later, and can truncate to 0
		return tr(baseDamage, 16);
	}
```

And finally, exact same thing again for getDamage, but with two arguments this time (one for the crit factor). And you have to put moveHit just before the new brackets. We call modifyDamage with the new rng argument.

```
	getDamage(
		pokemon: Pokemon, target: Pokemon, move: string | number | ActiveMove,
		suppressMessages = false**, crit?: boolean, rng: number**
	): number | undefined | null | false {
		if (typeof move === 'string') move = this.dex.getActiveMove(move);

		if (typeof move === 'number') {
			const basePower = move;
			move = new Dex.Move({
				basePower,
				type: '???',
				category: 'Physical',
				willCrit: false,
			}) as ActiveMove;
			move.hit = 0;
		}

		if (!move.ignoreImmunity || (move.ignoreImmunity !== true && !move.ignoreImmunity[move.type])) {
			if (!target.runImmunity(move.type, !suppressMessages)) {
				return false;
			}
		}

		if (move.ohko) return target.maxhp;
		if (move.damageCallback) return move.damageCallback.call(this, pokemon, target);
		if (move.damage === 'level') {
			return pokemon.level;
		} else if (move.damage) {
			return move.damage;
		}

		const category = this.getCategory(move);
		const defensiveCategory = move.defensiveCategory || category;

		let basePower: number | false | null = move.basePower;
		if (move.basePowerCallback) {
			basePower = move.basePowerCallback.call(this, pokemon, target, move);
		}
		if (!basePower) return basePower === 0 ? undefined : basePower;
		basePower = this.clampIntRange(basePower, 1);

		**const moveHit = target.getMoveHitData(move);**

		**if(crit === undefined){**

			let critMult;
			let critRatio = this.runEvent('ModifyCritRatio', pokemon, target, move, move.critRatio || 0);
			if (this.gen <= 5) {
				critRatio = this.clampIntRange(critRatio, 0, 5);
				critMult = [0, 16, 8, 4, 3, 2];
			} else {
				critRatio = this.clampIntRange(critRatio, 0, 4);
				if (this.gen === 6) {
					critMult = [0, 16, 8, 2, 1];
				} else {
					critMult = [0, 24, 8, 2, 1];
				}
			}

			moveHit.crit = move.willCrit || false;
			if (move.willCrit === undefined) {
				if (critRatio) {
					moveHit.crit = this.randomChance(1, critMult[critRatio]);
				}
			}

			if (moveHit.crit) {
				moveHit.crit = this.runEvent('CriticalHit', target, null, move);
			}

		**} else {moveHit.crit = crit;}**

		// happens after crit calculation
		basePower = this.runEvent('BasePower', pokemon, target, move, basePower, true);

		if (!basePower) return 0;
		basePower = this.clampIntRange(basePower, 1);

		const level = pokemon.level;

		const attacker = pokemon;
		const defender = target;
		let attackStat: StatNameExceptHP = category === 'Physical' ? 'atk' : 'spa';
		const defenseStat: StatNameExceptHP = defensiveCategory === 'Physical' ? 'def' : 'spd';
		if (move.useSourceDefensiveAsOffensive) {
			attackStat = defenseStat;
			// Body press really wants to use the def stat,
			// so it switches stats to compensate for Wonder Room.
			// Of course, the game thus miscalculates the boosts...
			if ('wonderroom' in this.field.pseudoWeather) {
				if (attackStat === 'def') {
					attackStat = 'spd';
				} else if (attackStat === 'spd') {
					attackStat = 'def';
				}
				if (attacker.boosts['def'] || attacker.boosts['spd']) {
					this.hint("Body Press uses Sp. Def boosts when Wonder Room is active.");
				}
			}
		}

		const statTable = {atk: 'Atk', def: 'Def', spa: 'SpA', spd: 'SpD', spe: 'Spe'};
		let attack;
		let defense;

		let atkBoosts = move.useTargetOffensive ? defender.boosts[attackStat] : attacker.boosts[attackStat];
		let defBoosts = defender.boosts[defenseStat];

		let ignoreNegativeOffensive = !!move.ignoreNegativeOffensive;
		let ignorePositiveDefensive = !!move.ignorePositiveDefensive;

		if (moveHit.crit) {
			ignoreNegativeOffensive = true;
			ignorePositiveDefensive = true;
		}
		const ignoreOffensive = !!(move.ignoreOffensive || (ignoreNegativeOffensive && atkBoosts < 0));
		const ignoreDefensive = !!(move.ignoreDefensive || (ignorePositiveDefensive && defBoosts > 0));

		if (ignoreOffensive) {
			this.debug('Negating (sp)atk boost/penalty.');
			atkBoosts = 0;
		}
		if (ignoreDefensive) {
			this.debug('Negating (sp)def boost/penalty.');
			defBoosts = 0;
		}

		if (move.useTargetOffensive) {
			attack = defender.calculateStat(attackStat, atkBoosts);
		} else {
			attack = attacker.calculateStat(attackStat, atkBoosts);
		}

		attackStat = (category === 'Physical' ? 'atk' : 'spa');
		defense = defender.calculateStat(defenseStat, defBoosts);

		// Apply Stat Modifiers
		attack = this.runEvent('Modify' + statTable[attackStat], attacker, defender, move, attack);
		defense = this.runEvent('Modify' + statTable[defenseStat], defender, attacker, move, defense);

		if (this.gen <= 4 && ['explosion', 'selfdestruct'].includes(move.id) && defenseStat === 'def') {
			defense = this.clampIntRange(Math.floor(defense / 2), 1);
		}

		const tr = this.trunc;

		// int(int(int(2 * L / 5 + 2) * A * P / D) / 50);
		const baseDamage = tr(tr(tr(tr(2 * level / 5 + 2) * basePower * attack) / defense) / 50);

		// Calculate damage modifiers separately (order differs between generations)
		return this.modifyDamage(baseDamage, pokemon, target, move, suppressMessages**, rng**);
	}
```
I tested this code in .js after copied and pasted my .ts code and it works pretty well! 0 impact on current code and bots can now run some theorical calcs with something like **getDamage(attacker,defender,move,false,true,7.5)**: no need to use the Smogon calc anymore :)

Rgds,

NDV

**Comment by NicoDeVang** [comment]
> Your idea might be good, though. Can you just copy/paste your changed code here? That would probably be simplest, if you don't know Git.

Hi Zarel,

Firstly, we have to add an argument in the end of the _randomizer_ function, which will have 0 impact on current code (as it’s undefined all the time).

	randomizer(baseDamage: number, rng: number) {
		const tr = this.trunc;
		return tr(tr(baseDamage * (100 - (rng === undefined?this.random(16):rng))) / 100);
	}

Then, exact same thing for modifyDamage: we have to add an argument in the end, which again has 0 impact on the current code as it’s never called. We call randomizer with this new argument.

	modifyDamage(
		baseDamage: number, pokemon: Pokemon, target: Pokemon, move: ActiveMove, suppressMessages = false, rng: number
	) {
		const tr = this.trunc;
		if (!move.type) move.type = '???';
		const type = move.type;

		baseDamage += 2;

		// multi-target modifier (doubles only)
		if (move.spreadHit) {
			const spreadModifier = move.spreadModifier || (this.gameType === 'free-for-all' ? 0.5 : 0.75);
			this.debug('Spread modifier: ' + spreadModifier);
			baseDamage = this.modify(baseDamage, spreadModifier);
		}

		// weather modifier
		baseDamage = this.runEvent('WeatherModifyDamage', pokemon, target, move, baseDamage);

		// crit - not a modifier
		const isCrit = target.getMoveHitData(move).crit;
		if (isCrit) {
			baseDamage = tr(baseDamage * (move.critModifier || (this.gen >= 6 ? 1.5 : 2)));
		}

		// random factor - also not a modifier
		baseDamage = this.randomizer(baseDamage,rng);

		// STAB
		if (move.forceSTAB || (type !== '???' && pokemon.hasType(type))) {
			// The "???" type never gets STAB
			// Not even if you Roost in Gen 4 and somehow manage to use
			// Struggle in the same turn.
			// (On second thought, it might be easier to get a MissingNo.)
			baseDamage = this.modify(baseDamage, move.stab || 1.5);
		}
		// types
		let typeMod = target.runEffectiveness(move);
		typeMod = this.clampIntRange(typeMod, -6, 6);
		target.getMoveHitData(move).typeMod = typeMod;
		if (typeMod > 0) {
			if (!suppressMessages) this.add('-supereffective', target);

			for (let i = 0; i < typeMod; i++) {
				baseDamage *= 2;
			}
		}
		if (typeMod < 0) {
			if (!suppressMessages) this.add('-resisted', target);

			for (let i = 0; i > typeMod; i--) {
				baseDamage = tr(baseDamage / 2);
			}
		}

		if (isCrit && !suppressMessages) this.add('-crit', target);

		if (pokemon.status === 'brn' && move.category === 'Physical' && !pokemon.hasAbility('guts')) {
			if (this.gen < 6 || move.id !== 'facade') {
				baseDamage = this.modify(baseDamage, 0.5);
			}
		}

		// Generation 5, but nothing later, sets damage to 1 before the final damage modifiers
		if (this.gen === 5 && !baseDamage) baseDamage = 1;

		// Final modifier. Modifiers that modify damage after min damage check, such as Life Orb.
		baseDamage = this.runEvent('ModifyDamage', pokemon, target, move, baseDamage);

		if (move.isZOrMaxPowered && target.getMoveHitData(move).zBrokeProtect) {
			baseDamage = this.modify(baseDamage, 0.25);
			this.add('-zbroken', target);
		}

		// Generation 6-7 moves the check for minimum 1 damage after the final modifier...
		if (this.gen !== 5 && !baseDamage) return 1;

		// ...but 16-bit truncation happens even later, and can truncate to 0
		return tr(baseDamage, 16);
	}

And finally, exact same thing again for getDamage, but with two arguments this time (one for the crit factor). And you have to put moveHit just before the new brackets. We call modifyDamage with the new rng argument.

	getDamage(
		pokemon: Pokemon, target: Pokemon, move: string | number | ActiveMove,
		suppressMessages = false, crit?: boolean, rng: number
	): number | undefined | null | false {
		if (typeof move === 'string') move = this.dex.getActiveMove(move);

		if (typeof move === 'number') {
			const basePower = move;
			move = new Dex.Move({
				basePower,
				type: '???',
				category: 'Physical',
				willCrit: false,
			}) as ActiveMove;
			move.hit = 0;
		}

		if (!move.ignoreImmunity || (move.ignoreImmunity !== true && !move.ignoreImmunity[move.type])) {
			if (!target.runImmunity(move.type, !suppressMessages)) {
				return false;
			}
		}

		if (move.ohko) return target.maxhp;
		if (move.damageCallback) return move.damageCallback.call(this, pokemon, target);
		if (move.damage === 'level') {
			return pokemon.level;
		} else if (move.damage) {
			return move.damage;
		}

		const category = this.getCategory(move);
		const defensiveCategory = move.defensiveCategory || category;

		let basePower: number | false | null = move.basePower;
		if (move.basePowerCallback) {
			basePower = move.basePowerCallback.call(this, pokemon, target, move);
		}
		if (!basePower) return basePower === 0 ? undefined : basePower;
		basePower = this.clampIntRange(basePower, 1);

		const moveHit = target.getMoveHitData(move);

		if(crit === undefined){

			let critMult;
			let critRatio = this.runEvent('ModifyCritRatio', pokemon, target, move, move.critRatio || 0);
			if (this.gen <= 5) {
				critRatio = this.clampIntRange(critRatio, 0, 5);
				critMult = [0, 16, 8, 4, 3, 2];
			} else {
				critRatio = this.clampIntRange(critRatio, 0, 4);
				if (this.gen === 6) {
					critMult = [0, 16, 8, 2, 1];
				} else {
					critMult = [0, 24, 8, 2, 1];
				}
			}

			moveHit.crit = move.willCrit || false;
			if (move.willCrit === undefined) {
				if (critRatio) {
					moveHit.crit = this.randomChance(1, critMult[critRatio]);
				}
			}

			if (moveHit.crit) {
				moveHit.crit = this.runEvent('CriticalHit', target, null, move);
			}

		} else {moveHit.crit = crit;}

		// happens after crit calculation
		basePower = this.runEvent('BasePower', pokemon, target, move, basePower, true);

		if (!basePower) return 0;
		basePower = this.clampIntRange(basePower, 1);

		const level = pokemon.level;

		const attacker = pokemon;
		const defender = target;
		let attackStat: StatNameExceptHP = category === 'Physical' ? 'atk' : 'spa';
		const defenseStat: StatNameExceptHP = defensiveCategory === 'Physical' ? 'def' : 'spd';
		if (move.useSourceDefensiveAsOffensive) {
			attackStat = defenseStat;
			// Body press really wants to use the def stat,
			// so it switches stats to compensate for Wonder Room.
			// Of course, the game thus miscalculates the boosts...
			if ('wonderroom' in this.field.pseudoWeather) {
				if (attackStat === 'def') {
					attackStat = 'spd';
				} else if (attackStat === 'spd') {
					attackStat = 'def';
				}
				if (attacker.boosts['def'] || attacker.boosts['spd']) {
					this.hint("Body Press uses Sp. Def boosts when Wonder Room is active.");
				}
			}
		}

		const statTable = {atk: 'Atk', def: 'Def', spa: 'SpA', spd: 'SpD', spe: 'Spe'};
		let attack;
		let defense;

		let atkBoosts = move.useTargetOffensive ? defender.boosts[attackStat] : attacker.boosts[attackStat];
		let defBoosts = defender.boosts[defenseStat];

		let ignoreNegativeOffensive = !!move.ignoreNegativeOffensive;
		let ignorePositiveDefensive = !!move.ignorePositiveDefensive;

		if (moveHit.crit) {
			ignoreNegativeOffensive = true;
			ignorePositiveDefensive = true;
		}
		const ignoreOffensive = !!(move.ignoreOffensive || (ignoreNegativeOffensive && atkBoosts < 0));
		const ignoreDefensive = !!(move.ignoreDefensive || (ignorePositiveDefensive && defBoosts > 0));

		if (ignoreOffensive) {
			this.debug('Negating (sp)atk boost/penalty.');
			atkBoosts = 0;
		}
		if (ignoreDefensive) {
			this.debug('Negating (sp)def boost/penalty.');
			defBoosts = 0;
		}

		if (move.useTargetOffensive) {
			attack = defender.calculateStat(attackStat, atkBoosts);
		} else {
			attack = attacker.calculateStat(attackStat, atkBoosts);
		}

		attackStat = (category === 'Physical' ? 'atk' : 'spa');
		defense = defender.calculateStat(defenseStat, defBoosts);

		// Apply Stat Modifiers
		attack = this.runEvent('Modify' + statTable[attackStat], attacker, defender, move, attack);
		defense = this.runEvent('Modify' + statTable[defenseStat], defender, attacker, move, defense);

		if (this.gen <= 4 && ['explosion', 'selfdestruct'].includes(move.id) && defenseStat === 'def') {
			defense = this.clampIntRange(Math.floor(defense / 2), 1);
		}

		const tr = this.trunc;

		// int(int(int(2 * L / 5 + 2) * A * P / D) / 50);
		const baseDamage = tr(tr(tr(tr(2 * level / 5 + 2) * basePower * attack) / defense) / 50);

		// Calculate damage modifiers separately (order differs between generations)
		return this.modifyDamage(baseDamage, pokemon, target, move, suppressMessages, rng);
	}

I tested this code in .js after copied and pasted my .ts code and it works pretty well! 0 impact on current code and bots can now run some theorical calcs with something like **getDamage(attacker,defender,move,false,true,7.5)**: no need to use the Smogon calc anymore :)

Rgds,

NDV

**Comment by Zarel** [comment]
@NicoDeVang, do the `attacker`, `defender`, `move`, and `battle` variables just come from you explicitly calling `new Battle()` etc?

I'm seeing the following event calls in `getDamage` and `modifyDamage`:

- `WeatherModifyDamage`, `ModifyDamage`, `ModifyCritRatio`, `CriticalHit`, `Modify[stat]`

And the following callbacks:

- `damageCallback`, `basePowerCallback`

I don't believe any of the event calls have RNG, but `damageCallback` (Psywave) and `basePowerCallback` (Magnitude) do. Do you have any plans for those? (Hardcoding?)

I think one alternative trick is to simply override the RNG like this:

```ts
battle.prng = alwaysMax;
const maxDamage = battle.getDamage(...);

battle.prng = alwaysMin;
const minDamage = battle.getDamage(...);
```

I think that would involve less brittle code changes to PS's damage functions.

**Comment by NicoDeVang** [comment]
Your idea is quite better, yep. But in order to push through it as far as possible (in my opinion), the best way would probably be to create a new battle object like `battle.customRNG = new Object();` with the following attributes:

battle.customRNG.roll = alwaysMax; (for example)
battle.customRNG.crit = true;
battle.customRNG.psywave = ...;
battle.customRNG.magnitude = ...;
(which would solve your issue btw)

Then if(!battle.customRNG), it generates some RNG, else, it considers values from this object.

And I think that you also have to add the **alwaysMiddle** parameter (in top of alwaysMin and alwaysMax) which would equal to `(alwaysMin + alwaysMax)/2` just to have a theoretical value of a midRoll. Cuz if you wanna run billions of calcs for an AI learning, that will be quite faster to do `battle.prng = alwaysMiddle;const myDamage = battle.getDamage(...);` than do `battle.prng = alwaysMax;const maxDamage = battle.getDamage(...);battle.prng = alwaysMin;const minDamage = battle.getDamage(...);const myDamage = (minDamage + maxDamage) / 2;` cuz you simply run 2 times less calcs.

**Comment by Zarel** [comment]
I mean, yes, sure, that's all stuff you could do that I would be happy to accept if you wanted to try your luck at PRing again. You should join us at https://psim.net/devdiscord if you'd like us to walk you through that.

**Pull request closed without merging**
