### PR TITLE
Support setting a default format/mod for commands in rooms

### PR DESCRIPTION
**Pull request by Zarel**
Affected commands: `/data`, `/coverage`, `/effectiveness`, `/weakness`, `/learn`

Supersedes #7965

### CODE REVIEW

**Comment by Zarel** [comment]
@mia-pi-git you didn't understand why I wanted to support setting a default format as well as a default mod.

The reason is because a lot of commands work differently in different formats. For instance:

- Setting the default format to VGC would make `/learn` exclude past-gen learn methods
- Setting the default format to Tier Shift would make `/data` show Tier Shift stats

**Comment by Zarel** [comment]
@KrisXV do you think `dataCommandTierDisplay` should be folded into this?

**Comment by DaWoblefet** [comment]
Being able to use /learn etc. for VGC purposes at all would be awesome!

**Comment by KrisXV** [comment]
> @KrisXV do you think `dataCommandTierDisplay` should be folded into this?

probably, but this wouldnt be accurate for national dex anymore; we prefer the numbers

**Pull request merged**
