### PR TITLE
Fix Slow Start's interaction with Neutralizing Gas

### PR DESCRIPTION
**Pull request by KrisXV**
I don't know if this is the best approach to this but it's currently the only way I've tried that works.

### CODE REVIEW

**Comment by urkerab** [comment]
This bug seems to affects other Abilities too (I tested Flash Fire but there are probably others such as Unburden). Maybe you need to look for Abilities affected by NG and send them the End event?

**Comment by DaWoblefet** [comment]
Yes, there are currently several skipped tests in the repo for those sorts of persistent effects like Unburden, Slow Start, Illusion, and Gluttony that don't play well with NGas right now.

**Comment by Zarel** [comment]
The only other thing I can think of is to make NGas's volatile do nothing if the ability isn't active.

That might actually be simpler, actually.

**Comment by Zarel** [comment]
But I believe all abilities should be implemented that way: their volatile does nothing, but the ability itself checks if the volatile is there and uses that to determine how it works.

**Pull request merged**
