### PR TITLE
Improve handling of locks when users are merged

### PR DESCRIPTION
**Pull request by AnnikaCodes**

### CODE REVIEW

**Comment by Zarel** [comment]
Is there any reason `prevNames` is an Object?

**Comment by Zarel** [comment]
Thanks, by the way.

**Comment by Zarel** [comment]
But I wonder if `prevNames` should be refactored into an Array.

**Comment by AnnikaCodes** [comment]
> But I wonder if `prevNames` should be refactored into an Array.

Yeah I don't believe there's a need for keeping IDs _and_ names; just IDs should be fine. I'll probably get around to that later this week.

**Pull request merged**
