### PR TITLE
Fix typo in comment

### PR DESCRIPTION
**Pull request by singiamtel**
Very minor fix
idenitfy -> identify
dont -> don't

### CODE REVIEW

**Comment by AnnikaCodes** [comment]
Do typos in comments matter?

**Comment by PartMan7** [comment]
> Do typos in comments matter?

It's Hacktoberfest.

Typographical error-fixing is the _norm_.

**Comment by singiamtel** [comment]
> Do typos in comments matter?

Not much I guess, I was just scrolling through the code and saw it

**Review by xfix — APPROVED** [review]

**Comment by HoeenCoder** [comment]
I don't have an issue with typo fixes in comments personally. Sure its not really a code contribution, but its still nice to fix it.

**Pull request merged**
