### PR TITLE
Fix type immunity check in /ds weak and resists and disallow status moves

### PR DESCRIPTION
**Pull request by MacChaeger**
It broke something! Oops!

### CODE REVIEW

**Comment by MacChaeger** [comment]
It broke a bit more than one something, hang on while I add those fixes.

**Comment by MacChaeger** [comment]
Yeah I have no idea what those failing tests are for.

**Comment by MacChaeger** [comment]
Wait, they were only failing locally? Whuh?

**Comment by Zarel** [comment]
Thanks!

**Pull request merged**
