### PR TITLE
Support week-long roombans

### PR DESCRIPTION
**Pull request by mia-pi-git**
https://www.smogon.com/forums/threads/implement-a-weekban-command.3669889/#post-8588113

### CODE REVIEW

**Review by AnnikaCodes — COMMENTED** [review]
I PMd you my thoughts on Discord.

**Comment by mia-pi-git** [comment]
> Is there a reason there's no `weekban` alias?

I felt it'd be slightly out of pattern - i can add that, though.

**Comment by Zarel** [comment]
We've gradually, over time, transitioned commands over from defaulting to global (back when we didn't have chatrooms) to defaulting to room.

At this point, I believe all commands either have no default (promote/demote) or default to room (banning). Weekban is a ban command, so I think if `/ban` defaults to roombans, there's no ambiguity for `/weekban`.

**Comment by Zarel** [comment]
I would also add `/forceweekban`, and make `/forceweekban` and `/weekban` the defaults.

`/help ban` shows `/ban` and not `/roomban`, after all.

**Comment by Zarel** [comment]
Speaking of `/help ban`, do you want to add this to `/help ban` while you're at it?

**Comment by mia-pi-git** [comment]
> Speaking of `/help ban`, do you want to add this to `/help ban` while you're at it?
> I would also add `/forceweekban`, and make `/forceweekban` and `/weekban` the defaults.

Done. Removed /forceweekroomban and /weekroomban.

**Comment by mia-pi-git** [comment]
Shit, mistake in push.

**Comment by Zarel** [comment]
Thanks. I think maybe we should still have `/weekroomban` and maybe `/forceweekroomban` as aliases, though?

Also, how do you feel about `/wb` as an alias? "wb" often means "welcome back" so it might be weird, but I can't think of an actual conflict.

**Pull request merged**
