### PR TITLE
Groupchats: Add a button to staffintro to delete the groupchat

### PR DESCRIPTION
**Pull request by mia-pi-git**
Requested / convenient.

### CODE REVIEW

**Comment by Zarel** [comment]
I'm not sure "convenient" is the word I would use for being able to accidentally delete a groupchat with a single misclick...

**Comment by PartMan7** [comment]
What about making the value ``/htmlbox Are you sure you want to delete the groupchat? <button ...close>Hai</button>``

I'm aware that the usual PS protocol is to avoid this, but there's no way to undo deleting a groupchat.

**Comment by Zarel** [comment]
Very cool and creative use of `/htmlbox`.

Sadly you can't send uhtml to yourself, so that would still add an unclosable Delete button.

I think a better workaround would be to supporting requiring a confirmation client-side. Maybe with `<button data-requireconfirm="Delete">`.

**Comment by mia-pi-git** [comment]
Closing because this is barely relevant anymore, with groupchat deprecation.

**Pull request closed without merging**
