### PR TITLE
Add Pet Mods of the Season

### PR DESCRIPTION
**Pull request by acasualmemelord**
need to fix outdated stuff

### CODE REVIEW

**Comment by AnnikaCodes** [comment]
Checks are failing.

**Comment by acasualmemelord** [comment]
> Checks are failing.

image
have no idea how to fix this as it seems to be a problem with showdown's rooms script?

**Comment by KrisXV** [comment]
I believe this is all good now

@AnnikaCodes

**Comment by AnnikaCodes** [comment]
hopefully this works

**Pull request merged**
