### PR TITLE
Best of three (in progress)

### PR DESCRIPTION
**Pull request by Zarel**
This is a WIP of a PS best-of-three implementation. It's actually nearly completely finished, it just looks kind of ugly, mostly because client support for non-battle gamerooms needs to be improved.

### CODE REVIEW

**Comment by scheibo** [comment]
Obviously this is going to need to be updated to handle the recent `RoomGame` refactor, but could you elaborate on how "client support for non-battle gamerooms needs to be improved"? It sounds like something which may be blocked on the Preact rewrite?

**Comment by Zarel** [comment]
> Obviously this is going to need to be updated to handle the recent `RoomGame` refactor, but could you elaborate on how "client support for non-battle gamerooms needs to be improved"? It sounds like something which may be blocked on the Preact rewrite?

Yes, that's correct. The main issue I was dealing with was that music was playing and I wasn't very good at turning it off.

**Comment by scheibo** [comment]
>  The main issue I was dealing with was that music was playing and I wasn't very good at turning it off.

If this is all that is required, does this really need to be blocked on Preact? The BO3 feature seems to have enough popularity that it seems potentially worth duplicating work if someone wanted to pick it up and deliver it sooner provided the required effort is relatively small (compared to say, the Friend's List)?

**Comment by Zarel** [comment]
I should probably refactor BattleSound, yes. That's certainly a refactor that can land before a full Preact rewrite because it's in the `.ts` files already used by the old client.

**Comment by scheibo** [comment]
> I should probably refactor BattleSound, yes. That's certainly a refactor that can land before a full Preact rewrite because it's in the `.ts` files already used by the old client.

Given a refactor of BattleSound recently occured, is BO3 actually still blocked on Preact?

**Comment by Zarel** [comment]
Oh, no, this hasn't been blocked on Preact since forever. I did the relevant BattleSound refactor in Aug 2019:

https://github.com/smogon/pokemon-showdown-client/commit/f1a560f90a08fb0f61765f426c2a2eb09ac5a3e7

At this point, this mostly just needs to be rebased.

**Comment by DaWoblefet** [comment]
Superseded by https://github.com/smogon/pokemon-showdown/pull/9793

**Pull request closed without merging**
