### PR TITLE
Twisted Dimension: fix Trick Room interaction

### PR DESCRIPTION
**Pull request by HisuianZoroark**
Fixes a logic short circuit where using Trick Room does nothing in twisted dimension

### CODE REVIEW

**Comment by andrebastosdias** [comment]
Is there a reason why the `getActionSpeed` method wasn’t overridden inside the rulesets file, instead of relying on a ruletable check?

**Comment by urkerab** [comment]
@andrebastosdias I don't even think you can override a battle function inside a rule, but it also allows the rule to be used in a mashup.

**Comment by Karthik99999** [comment]
> @andrebastosdias I don't even think you can override a battle function inside a rule, but it also allows the rule to be used in a mashup.

You can.

```js
pokemon: {
	getActionSpeed() {},
},
```

**Comment by urkerab** [comment]
I'm sure that the above passes TypeScript but it's not actually usable; the battle only imports overrides from the format, not any of its rules. (Things like `onBegin` and `onTeamPreview` are special-cased to run on both the format and all rules.)

**Comment by andrebastosdias** [comment]
> I'm sure that the above passes TypeScript but it's not actually usable; the battle only imports overrides from the format, not any of its rules. (Things like `onBegin` and `onTeamPreview` are special-cased to run on both the format and all rules.)

If you override it, you won't need to access the rules since you know the mod is active. I just find it a bit odd to have such a remote rule in the main scripts.

**Comment by Slayer95** [comment]
> > @andrebastosdias I don't even think you can override a battle function inside a rule, but it also allows the rule to be used in a mashup.
> 
> You can
> 
> ```js
> pokemon: {
> 	getActionSpeed() {},
> },
> ```
> 
> is how you would format it.

This is supposed to go in ``scripts.ts``

**Comment by Karthik99999** [comment]
> This is supposed to go in `scripts.ts` (i.e. only for mods)

It definitely works in formats (see Fortemons, Loser's Game, Tera Donation in current `formats.ts`), though i guess not rulesets as urkerab pointed out.

**Comment by urkerab** [comment]
Indeed, I was the one who added support for it in formats, but you can't mash multiple formats together in quite the same way that you can with rules.

**Pull request merged**
