### PR TITLE
Add a Room Prize Winner rank

### PR DESCRIPTION
**Pull request by AnnikaCodes**
As per [this suggestion](https://www.smogon.com/forums/threads/allow-room-owners-to-promote-to-%E2%9C%A9.3669018/#post-8577989). This will obviously necessitate a change to main's `config.js` as well.

### CODE REVIEW

**Comment by Zarel** [comment]
This looks and sounds a bit too much like the Player rank. I don't like the symbol overlap tbh.

**Comment by Zarel** [comment]
I'll comment on the suggestion with more thoughts.

**Comment by AnnikaCodes** [comment]
Hmm, how about the black chess queen as a prize symbol (♛)

**Comment by Zarel** [comment]
Looks kinda unrecognizable at normal resolutions, I think. You should discuss it in the Suggestions thread, though.

**Comment by AnnikaCodes** [comment]
I'm going to draft this until we reach a consensus on what symbol the ROs want.

**Comment by AnnikaCodes** [comment]
Alrighty, it looks like `^` is a reasonable choice.

**Comment by Zarel** [comment]
Yep, sounds good to me, too.

**Pull request merged**
