### PR TITLE
Nicknamefilter: Support hiding nicks from filters

### PR DESCRIPTION
**Pull request by mia-pi-git**

### CODE REVIEW

**Comment by Zarel** [comment]
Looks like this requires a restart?

**Comment by Zarel** [comment]
Hm, having read the whole thing, I think it's safe to merge now for a restart whenever; it wouldn't break hotpatching. Would you agree?

**Review by Zarel — APPROVED** [review]

**Comment by mia-pi-git** [comment]
Yeah, i said this on discord but if someone else wants to do it, i'll leave it here. This doesn't need a restart but does need a monkeypatch (https://gist.github.com/mia-pi-git/1768d1bc0b55694a1b158502b5b47290)

**Comment by Zarel** [comment]
ty!

**Pull request merged**
