### PR TITLE
Room events: Add a command to view categories

### PR DESCRIPTION
**Pull request by AnnikaCodes**
Suggested [here](https://www.smogon.com/forums/threads/add-the-ability-to-view-categories-to-roomevents.3671887/#post-8626771).

### CODE REVIEW

**Comment by Zarel** [comment]
Isn't the problem that the regular list view doesn't show categories? Shouldn't the regular list view show categories?

**Comment by Zarel** [comment]
Or am I misinterpreting the request?

**Comment by AnnikaCodes** [comment]
The issue is that people want a list of categories (including those with no events in them), rather than a list of events that displays the categories each event is in (and can be filtered by category).

**Comment by Zarel** [comment]
Oh okay.

**Comment by Zarel** [comment]
Thanks!

**Pull request merged**
