### PR TITLE
Revert "Improved typing for `utils.ts`, and for iterating over base stats"

### PR DESCRIPTION
**Pull request by AnnikaCodes**
Reverts smogon/pokemon-showdown#8919. This broke certain mods and needs further testing.

### CODE REVIEW

**Comment by GregLyons** [comment]
1. Was it a compile-time error or a run-time error? And which mods were breaking? Aside from the `parseInt` and `startsWith` changes, the only changes which should change the run-time behavior are the ones that change `stat in newSpecies.baseStats` to `stat of Stats.statIDs`. I was assuming that the object `newSpecies.baseStats` always has `[hp, atk, def, spa, spd, spe]` as keys, but if at some point that object has a key added or removed, then my change would've broken that. If instead it's compile-time errors, I'm happy to fix those and re-open the PR.
2. What unit-testing framework do y'all use? (#8868) I'm most familiar with Jest, but I'm willing to pick up whatever PS uses. It seems like the relevant code (mods that tweak base stats) would be relatively easy to write some extra tests for.

**Comment by AnnikaCodes** [comment]
Runtime error, the problem was that `Stats` wasn't defined in that file. We use Mocha for testing.

**Comment by GregLyons** [comment]
I see. Which mods were breaking? Was it all the mods in which `Stats.statIDs` was used? Perhaps I'm misunderstanding how `namespace`s work in TS, but I'm not seeing any errors on my end, even when I run `npm run test` (I did before, but ran it again after pulling in most recent changes). Is there a way I could reproduce this error for further testing?

**Comment by GregLyons** [comment]
🤦 [namespaces don't actually do anything in JS](https://stackoverflow.com/questions/60376241/typescript-namespace-not-resolved-during-runtime). Sorry for not realizing that. I'll open another PR soon with different fixes.

**Pull request merged**
