### PR TITLE
Make Species#nfe work for previous generations

### PR DESCRIPTION
**Pull request by KrisXV**

### CODE REVIEW

**Comment by KrisXV** [comment]
I'm not really sure why the build is failing and what relevance it holds to this pull request.

**Comment by Zarel** [comment]
The validator looks at whether or not pokemon are NFE, so I could see the build failure being related.

**Comment by Zarel** [comment]
If you can't figure it out, I'll set aside some time tomorrow.

**Comment by KrisXV** [comment]
Fixed @Zarel

**Comment by Zarel** [comment]
Neat, thanks.

**Pull request merged**
