### PR TITLE
Fix Disguise Issues

### PR DESCRIPTION
**Pull request by ascriptmaster**
https://www.smogon.com/forums/threads/bug-reports-v2-0-read-op-before-posting.3469932/post-7762721

If a move hits a Disguise, Counter/Mirror Coat deal 1 damage.

### CODE REVIEW

**Comment by Marty-D** [comment]
Dealing 1 damage and having a power of 1 are different things. The situation with taking 0 damage is already explained in the Counter/Mirror Coat/Metal Burst descriptions.

**Comment by Marty-D** [comment]
Oh, they actually just changed the whole interaction in Gen 7. In Gen 5 and 6, countering 0 damage defaulted to 1 power, applying type effectiveness and could crit, etc. Now it literally just deals 1 typeless damage in that case.

**Comment by ascriptmaster** [comment]
Ok, good to know. This is still a pretty hacky solution, though, considering that I am hard coding the Disguise damage modification into the battle.js, so I really need some advice on how to fix that up?

**Comment by Marty-D** [comment]
Since the 1 damage thing has nothing to do with Disguise, it should be done in Counter/Mirror Coat/Metal Burst. It looks like someone already tried returning 1 damage from its damageCallback when there's no damage to return, but it probably isn't working correctly (and would be wrong in Gen 5 and 6 anyway).

**Comment by Marty-D** [comment]
Ah, that's annoying, I don't really have any better ideas in that case. @Zarel, what would you suggest?

**Comment by ascriptmaster** [comment]
Hmmm, what if we put Counter on an AfterDamage listener instead of responding directly to the Damage event? That might fix our problems. Does Rocky Helmet trigger if a Mimikyu with active Disguise is hit with a Physical move? If so, then I will make sure that the AfterDamage event runs properly and then maybe we can move Counter and friends to run against that event.

**Comment by Marty-D** [comment]
Yeah Rocky Helmet triggers. I believe it's exactly like Snackhound said in the research thread; busting Disguise simply does not run the damage formula at all (hence no crits, no type effectiveness, the Rollout bug, etc.), but does count as a hit and triggers any after damage interactions.

**Comment by ascriptmaster** [comment]
All right, I think I'll be able to refactor Counter to run onAfterDamage. It makes more sense for it to be there, anyways, since it isn't trying to affect the damage in any way.

I don't know how we can even test the "skip the damage formula" part, honestly, but that kind of thing might cause RNG desyncing from the proper console... which we probably also have with Shell Armor because of how it retroactively negates the crit if it occurs

**Comment by ascriptmaster** [comment]
bumpity

**Pull request merged**
