### PR TITLE
Add command to view remaining battles during lockdown

### PR DESCRIPTION
**Pull request by DaWoblefet**
I pretty frequently run an eval from Mia that does this to check if there's any private rated ladder games going on, so I figured I'd formalize it into a proper command.

### CODE REVIEW

**Comment by mia-pi-git** [comment]
Put this in a dropdown, please? there's often a lot!

**Comment by KrisXV** [comment]
> Put this in a dropdown, please? there's often a lot!

maybe we do a check if length is more than... 7? or some small number. but yes dropdown pls

**Comment by mia-pi-git** [comment]
> > Put this in a dropdown, please? there's often a lot!
> 
> maybe we do a check if length is more than... 7? or some small number. but yes dropdown pls

Preferably always put it in a dropdown, I usually spam that eval a lot and I'd like to keep my scrollback less clogged.

**Comment by DaWoblefet** [comment]
I like the idea of some small arbitrary number but am fine either way. I picked 10 for now.

**Comment by urkerab** [comment]
Out of interest, what does this show you that "Watch a battle" doesn't?

**Comment by DaWoblefet** [comment]
> Out of interest, what does this show you that "Watch a battle" doesn't?

Private battles, i.e. ones started with "Don't allow spectators" checked.

**Comment by urkerab** [comment]
What's the downside of including private battles there (for those users with access to them, obviously)?

**Comment by DaWoblefet** [comment]
I don't have a hard and fast opinion one way or the other, but in general I do like that you have to explicitly query these private battles during lockdown specifically. So far as I know, there's not currently another general way of looking up private battles without a username, and this command's purpose is specifically for looking up games in lockdown to make sure things are progressing smoothly. We could do that in /battles as well, but I think it's just as well to be a separate command for the use-case.

**Comment by mia-pi-git** [comment]
Yeah, would prefer a second command - it's not something we use at all unless it's a restart.

**Comment by mia-pi-git** [comment]
Seems like we're in agreement here, so gonna go ahead and merge this. Thanks wob!

**Pull request merged**
