### PR TITLE
Groups: Edit after the merger

### PR DESCRIPTION
**Pull request by theodelhay**
Editing of the /groups after the merger of the administrator and leader ranks

### CODE REVIEW

**Comment by sparkychildcharlie** [comment]
This isn't reflected in config-example.js tho

**Comment by Zarel** [comment]
I appreciate the enthusiasm, but yes, this should probably simultaneously change `config-example`.

**Comment by AnnikaCodes** [comment]
it'd also probably be a good idea to modify command help prompts that say `Requires: @ # & ~` and the like

**Comment by theodelhay** [comment]
I just saw the problem, but Annika managed to do it all https://github.com/smogon/pokemon-showdown/pull/6815.

**Pull request closed without merging**
