### PR TITLE
Life Orb/Shell Bell should take effect before Pickpocket

### PR DESCRIPTION
**Pull request by urkerab**
Thanks to @MacChaeger we can now move AfterMoveSecondarySelf to happen before AfterMoveSecondary and still have it only fire once, although I'm not sure I'm using the right target.

The other effects that use AfterMoveSecondarySelf are Fell Stinger, which doesn't care as its target has been KO'd anyway, and Meloetta's forme change, which seems fairly innocuous to me...

### CODE REVIEW

**Comment by Marty-D** [comment]
Would it make sense to just toss the whole thing in the new `afterMoveSecondaryEvent` before the AfterMoveSecondary part to send the appropriate target? I haven't had a chance to test this yet.

**Comment by urkerab** [comment]
Ah, so what we want is to change Life Orb/Shell Bell to use onSourceAfterMoveSecondary, and put their priority between Red Card and Pickpocket... assuming that will do the right thing, @MacChaeger ?

**Comment by urkerab** [comment]
No, because `onSourceAfterMoveSecondary` still runs once per target, so that's no good...

**Comment by urkerab** [comment]
Ugh, not quite right, this breaks Lock-On...

**Comment by urkerab** [comment]
> No, because onSourceAfterMoveSecondary still runs once per target, so that's no good...

I made it so that `onSource` events only run once when called as a spread event. This affects `onSourceAfterMoveSecondary` (good), `onSourceTryHit` (not used) and `onSourceInvulnerability`. Lock-On uses the latter, so I had to tweak it to use `onAnyInvulnerability` instead (fortunately it already checks both source and target).

This now makes the `AfterMoveSecondarySelf` event redundant, so I switched the users to `onSourceAfterMoveSecondary`, except for Fell Stinger and Relic Song, which simply use `onAfterMoveSecondary`.

At this point all I had to do was set the correct priority on the handlers. Thanks to @SadisticMystic for listing the effects in priority order for me.

**Comment by Zarel** [comment]
Okay, what's the status of this?

**Comment by AnnikaCodes** [comment]
Is this still in progress?

**Comment by urkerab** [comment]
Well, it looks like the status of this is that at the very least it needs rebasing...

**Comment by mia-pi-git** [comment]
Going to close this since it's been inactive for several years. Please feel free to reopen it if it's still relevant.

**Pull request closed without merging**
