### PR TITLE
Isle of Armor: Update Learnsets

### PR DESCRIPTION
**Pull request by HoeenCoder**

### CODE REVIEW

**Comment by Zarel** [comment]
GitHub can't display this diff, but on the other hand, this passes the learnset validator! I'll trust you that this is accurate. Thanks for the work on this!

**Comment by Zarel** [comment]
Also, do you guys have sources for where we got all this data? They're probably worth crediting.

**Comment by KrisXV** [comment]
SciresM

**Comment by KrisXV** [comment]
also thecommondude for move data

**Pull request merged**
