### PR TITLE
Changed lynches to vote in the votebox

### PR DESCRIPTION
**Pull request by Smallzi144**
Changed lynches to vote in the votebox
smallworldz

### CODE REVIEW

**Comment by AnnikaCodes** [comment]
Do you want to change the lynch message on line 846 as well? There are also some messages about "Selflynching" on lines 1560-70.

**Comment by Smallzi144** [comment]
yeah the one on 846 should  be changed to vote

im not fully sure how it works though if changing selflynching to selfvoting (lynching to voting) wont cause any probs 
 in line 1560-70 then those should be changed as well

**Comment by HoeenCoder** [comment]
> 
> 
> yeah the one on 846 should be changed to vote
> 
> im not fully sure how it works though if changing selflynching to selfvoting (lynching to voting) wont cause any probs
> in line 1560-70 then those should be changed as well

The change I see you added is just a text change, so it should be fine bar maybe Universal Backup (bot) not liking it, but thats a separate issue.

**Review by HoeenCoder — APPROVED** [review]

**Comment by Zarel** [comment]
@HoeenCoder is there a reason you approved instead of merged?

**Comment by HoeenCoder** [comment]
@Zarel was speaking to them on discord about changes related to the plugin, all set now so merging.

**Pull request merged**
