### PR TITLE
Gen 3 Random Battle Updates

### PR DESCRIPTION
**Pull request by TheTiksiBranch**
Normal updates, removing detractive clutter, killing redundant stab moves to quash double-stab set generation, and other assorted things like giving certain pokemon more individualized identities.

This should probably be reviewed by somebody else before it is merged.

### CODE REVIEW

**Comment by TheTiksiBranch** [comment]
Changes

----------

Charizard: double stab

Butterfree: removed two weak special attacks. there is something butterfree should be doing. special sweeping ain't it. hp fire less valuable than normally would be because both of your statuses affect steel types

Beedrill: this might not stay but anyway. off 80 attack, HP Bug is weak even after an SD, so Twineedle ensures that, whenever you click a STAB attack, there is a 30%+ chance somebody's getting poisoned. especially given that you're still pretty slow and _super_ frail after setting up, that's a big deal for bee.

Pidgeot: sub increases the chance of awful return-less sets and doesn't give that much

Fearow: redundant stab. i currently have sub removed but i may change my mind on that. syncs well with its speed, BP, and its pair of decent stabs as opposed to just one.

Arbok: rock slide is super weak, can miss, and doesn't bop any type that resists poison

Nidoking: you have many cooler and more practical moves than a bug move that can miss. removed megahorn. grass types lose to sludge bomb anyway

Clefable: double stab

Ninetales: double stab

Crobat: shadow ball gets neutral coverage anyway, so trading hp flying access (which could be your only stab) for hp coverage is less great. so removed hp coverage

Bellossom: double stab

Venomoth: i'm going to revert this one

Golduck: double stab

Arcanine: double stab

Poliwrath: the chance for belly drum instead of some standard bulky-ish water moves both gives him more of an identity and makes him quite dangerous

Politoed: double stab. counter cluttery

Tentacruel: more suited stab

Rapidash: agility kinda lame when you have lots of other stuff to do, already are fast, and might not even roll bp. and with agility gone, bp not worth

Slowbro: you're slowbro. just tank. no need to get fancy with fire blast

Slowking: double (non)stab

Magneton: substitute is just much less valuable than rest talk for how many resists you have, so the former i removed

Farfetch'd: previous set was kind of all over the place. understandable bc badmon with decent moves. but mandating slash and a boosting move, plus making both boosts as well as bp much more likely, both cement his identity and realistically make him much more dangerous

Dodrio: double stab

Muk: seems like i got a little too cute with shadow punch. also subpunch just dwarfed by resttalk and curse

Gengar: i feel like i never see perish trap here, which is rly sad for a pre-gen-4 randomized meta. so i added that. hypno kinda silly for a mon that can do stuff like gengar can, but with his speed and immunities it still may be worth? not sure. removed it for now. taunt cluttery when sub retained

Hypno: you're not a wallbreaker. thunder punch overdoing it. at the same time you can do cool things besides not dying, toxic not rly needed

Kingler: double (non)stab

Electrode: not sure why i gave this guy sub. he has taunt, and he's also not really threatening at all behind a sub. subtoxic electrode is not what this world needs

Marowak: double stab. i decided with eq over bonemerang bc always being forced to risk miss chance when using marowak strong move kinda sad

Hitmonlee: double stab

Hitmontop: double stab. also removed sub/endeavor/endure, leave the sub/endure stuff to hitmonlee. you have other stuff

Rhydon: toxic is clutter for reskinned golem. golem doesnt get it anywho

Blissey: being able to use special moves is nice but we don't need three. tbolt can go. also taking huge damage without recovering is kind of the opposite of what blissey should do, removed counter. it's a funny danger button though and has low rate so if it is desired back that's fine.

Kangaskhan: double stab. also rock slide clutter

Kingdra: double stab

Starmie: double stab

Electabuzz and Magmar: cool mons bc they can do lots of distinct things. subpunch not rly that distinct when you already have brick break. buzz got twave, mar got wow + seismic toss (talk about hitting _every_ mon for adequate damage). they both keep sub though bc it is dangerous with their coverage

Tauros: double stab. also trades iron tail for refresh, which gives it more of an identity as a status switch-in. especially useful given how dangerous status is in rands + how easy it can sometimes be to kill the status user and permanently remove the threat. and was anyone using iron tail anyway?

Vaporeon: double stab

Flareon: double (non)stab

Espeon: every other eeveelution gets wish. this fast and frail one can do without. and if no wish, no need for protect

Umbreon: i've changed minds on whether spd drop + bonking poison types, or getting neutral and rare coverage, is more valuable. going to the latter means replacing psychic with feint attack. charm and sub removed because every other move here is straight gold, especially trap + bp, which is sad that i never seem to see in pre gen-4 randomized meta along w/ perish trap

Kabutops: there should be a few rock types that get something besides ground coverage to spice things up. this one with brick break is a good bet.

Snorlax: double stab

Articuno: sub just not as scary without roost. i may add it back but i'm not super feeling it

Moltres: double stab

Dragonite: dragon claw more distinct than ice beam and thunderbolt because neutral coverage and damage output. (also it currently shows flamethrower removed and ice beam kept, im going to reverse that.) subpunch just a little too cute

Mew: having to resort to a 60 acc move on a mon with this movepool is sad. twave seems useful so i did that over hypno

Meganium: double stab. also replaced counter with reflect because its a good dual screening mon and i dont see dual screens often

Typhlosion: double stab

Feraligatr: not sure why i had rock slide over return originally. i got bored of return on physical waters maybe? reversed, this seems like a no-brainer, but maybe i had a good reason who knows.

Furret: double stab. also cutting clutter to increase chance of trick, the goal for this pool

Ledian: if u have ledian just go for the gold. sub just gonna prolong your demise.

Ariados: increasing trap+bp, see umbreon. also signal beam kinda not impressive when u have night shade for neutral coverage

Lanturn: double stab

Togetic: serene grace is funny and all but 45 attack. man. no thank you for body slam. i'm probably going to revert bp->protect switch

Xatu: why did this have rest talk? weird. weak to tons of stuff, resists little, and has other things to do

Azumarill: double stab + double nonstab

Sudowoodo: focus punch too much pizzazz for a bst and typing desperately trying to not sink this mon entirely. he should be happy he even gets resttalk

Sunflora: double stab

Quagsire: hp rock and counter clutter

Murkrow: i always get 3-4 attack sets with this and they're really disappointing. perish trap and annoy things with greater frequency instead

Gligar: iron tail is really bad guys. especially 100bp iron tail

Granbull: double stab. also subpunch cluttery when sub not really helpful like at all on this mon

Qwilfish: double stab

Shuckle: ive ran out of patience for how weak wrap is in this gen. every time i get wrap but no toxic shuckle, i long for the sweet release of death bc nothing happens. the vision was for wrap to exacerbate toxic, but we'd need wrap/toxic/resttalk only for that set and itd be kinda dry

Sneasel: double (non)stab. also this mon has super big power problems and few speed problems. so qa not great.

Ursaring: double stab. also yawn much more compelling than focus punch on a mon with eq

Piloswine: rock slide not backed up by stab or power is bad

Octillery: double (non)stab

Mantine: double (non)stab. rain dance too situational so i killed that too

Houndoom: double stab

Stantler: double stab

Miltank: double stab. also counter cluttery. everything else is so good compared to it.

Raikou: did i really just rearrange order of moves in file? that's obnoxious. i'll revert i guess. (no changes)

Entei: double stab and double nonstab. also sub cluttery

Suicune: double stab

Tyranitar: his set was too all over the place. left fire blast and crunch as the only two special moves, and now hp bug bolsters dd sets.

Lugia: eq kinda silly when (1) stab psychic already conks more than half of poison immune pokemon and (2) you're lugia. psychic/ice beam is enough for even cm lugia so i removed thunderbolt. also dual screens lugia terrifies me because lugia never dies. so i added the missing screen

Ho-oh: absolutely horrifying mon. reflect is not even bad, just everything else is so good i can't justify it

Sceptile: one neutral coverage special move is enough. subseed more

Blaziken: double stab. but twice

Swampert: double stab. also pert has better stuff to do than nonstab rock slide

Mightyena: have i said that iron tail is awful? especially when toxic and heal bell are so clutch

Beautifly: two _slightly_ strong attacks is better than four super weak ones. I might replace HP Bug with HP Flying.

Ludicolo: double stab

Shiftry: if i ever were to get sunny day + hp ice, i would've just forfeited then and there. lets not make that an option. hp coverage not life critical anyway, you have neutral coverage dark stab

Swellow: double stab

Slaking: double stab, also focus punch is just too much to ask of a mon as punishable as this. but that left only four moves... so lets bring glorious hyper beam into the fold. notching any one ko can turn losses into victories, and band 150 bp from slaking's attack is really good at that thing

Ninjask: i cut the gordian knot of protect sets that lacked bp. protect not that critical anyway, 1 speed boost is usually enough

Shedinja: i havent personally seen an awful shed set but its movepool looked like a disaster waiting to happen. two damaging moves, protect, bp, and one other funky option is enough excitement for mr. 1 hp.

Exploud: double stab and double nonstab. also toxic cluttery

Nosepass: expecting nosepass to actually trap and kill steel types is kind of delusional i realized? so hp rock gets the nod because it is generally a more useful attacking type to have. also taunt does not hit the bang-buck ratio this awful awful mon wants

Mawile: sd+bp and subpunch together kinda clunky. body slam can paralyze things which is really appreciated for mawile.

Medicham: double stab

Manectric: a manectric behind a sub is just a manectric with slightly more choice over what it paralyzes. pass

Plusle: I gave it HP Ice and left Minun with HP Grass to give them a slight difference for funs

Illumise: Such a weak mon. Toxic is a real boon. Poses zero threat behind a sub so i replaced that

Wailord: double stab

Torkoal: double stab. also have i told you unstabbed weak rock slide is bad? also his defense and resttalk make him a nice toxic user

Spinda: double stab. also subpunch is too lofty an expectation for those stats. also why did it have bp? trick and statuses much more valuable to spinda than these things

Zangoose: double stab

Solrock: light screen just really random. overheat is already there to make sure the set isn't completely lacking in spice

Whiscash: three mediocre coverage moves is too much for humble whiscash. I'll take the one that hits dreaded waters in a new way while also possibly paralyzing things.

Kecleon: have i told you that iron tail is bad?

Chimecho: why not dual screens with this

Huntail: double stab

Relicanth: i'm going to revert this

Metagross: have i told you unstabbed rock slide is bad? not exactly weak here, but you just don't need it and have a billion other things to do

Regice: boltbeam is iconic for a reason. if an opposing ice type eats your tbolts, you still probably outstall them anyway. you are regice after all

Registeel: counter is cluttery

Kyogre: double stab

Groudon: sub not as good as it could be with the uber level drop cutting into groudon's speed. on the other hand, twave on this moderately slow bulky behemoth that poses a serious threat to things? it's really good. 

Jirachi: you can do better than reflect on this

Deoxys-Speed: great dual-screener. superpower not awful but this utility mon has enough attack moves without it

**Comment by TheImmortal** [comment]
I was planning on going through gen 3 tomorrow with some Random Battle staff after getting complaints. Not sure what to do with this.

**Comment by TheTiksiBranch** [comment]
Well, alright. You can include me in your review session and I'll bring up these ideas there, you can make one pullreq after your review session and then i can make another one that doesn't duplicate what you did, you and the staff can review this as/after you do your complaint-addressing (and use the change explanations to see what changes you have already addressed), whatever.

**Comment by Zarel** [comment]
I don't see any gen 3 random battle updates and it's been two days since you said "tomorrow"... Is there any reason not to merge first and then do your update?

**Comment by TheImmortal** [comment]
The update started yesterday. There's no reason to spend time reviewing and merging this because it's literally going to be overwritten.

**Pull request closed without merging**
