### PR TITLE
NFE: Don't inherit from OU

### PR DESCRIPTION
**Pull request by TheMezStrikes**

### CODE REVIEW

**Comment by Zarel** [comment]
Why not?

**Comment by Zarel** [comment]
...why not?

**Comment by TheImmortal** [comment]
It's a unique metagame? It doesn't follow OU. Just because it shared similar clauses doesn't mean it should inherit.

**Comment by Zarel** [comment]
I guess...

**Comment by TheMezStrikes** [comment]
Very similar case to why LC doesn't inherit

**Pull request merged**
