### PR TITLE
Unify /guess and /choose

### PR DESCRIPTION
**Pull request by Zarel**
A lot of roomgames that should be using `/choose` or `/guess` but aren't. I'm going to unify them.

Would appreciate input from whoever's maintaining Trivia right now. @sparkychildcharlie?

### CODE REVIEW

**Comment by Zarel** [comment]
`/trivia answer` looks a bit too complex to factor in, but it really should...

**Comment by Zarel** [comment]
We'll wait for Mastermind/subgame to get refactored first.

**Comment by sparkychildcharlie** [comment]
Annika does Trivia and I do Scavs - but unifying them like this seems nice.  The commands for the two rooms are kinda tradition by now so changing them might throw people off when they try to race to sumbitntheir answers. /ta and /scavenge - long and clunky as they are - both have history and tons of reflex habits attached to both.  I can do something to make it use Chat.errorMessage throughout scavengers since im sure there are many instances if were talking about unifying stuff

**Comment by AnnikaCodes** [comment]
I maintain Trivia. I definitely want `/ta` to remain as an alias since that's what users are used to typing, but I think that aliasing it to `/guess` would be fine. I agree with the overall idea of having one command for all roomgames.

**Comment by Zarel** [comment]
We can keep all the old aliases; I just want `/choose` or `/guess` (maybe `/c` as a shortcut) to also work for all roomgames going forward.

**Comment by AnnikaCodes** [comment]
Sounds good to me!

**Comment by Zarel** [comment]
Probably also `/answer` too

**Comment by Zarel** [comment]
(Technically this will only crash hotpatch if there's a currently-running game of one of these, but I'm in no hurry so this can wait until next restart.)

**Pull request merged**
