### PR TITLE
Fix Healing Wish setting up slot condition on failure

### PR DESCRIPTION
**Pull request by Karthik99999**
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9220431

@DaWoblefet are you sure healing wish/lunar dance should fail during `onHit`? This fix requires a pretty awful hardcode.

### CODE REVIEW

**Comment by DaWoblefet** [comment]
Yeah you can change it - it's one of the non-Stomping Tantrum failures which I hypothesize in SwSh is very late: https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8548957. We know that from USUM, Stomping Tantrum just has a cutoff point in the checks done before move success where it determines if it should be doubled.

In USUM it's part of a generic list of "uncategorized" move events, which includes the following:
<details>
<summary>Uncategorized move event list</summary>
Conversion
Camouflage
Defog
Mimic
Sketch
Follow Me
Rage Powder
Refresh
Spider Web / Mean Look / Block
Splash
Celebrate
Hold Hands
Curse
Worry Seed
Stockpile
Focus Energy
Aqua Ring
Magic Coat
Snatch
Trick / Switcheroo
Endure
Protect / Detect
Recycle
Psycho Shift
Pain Split
Belly Drum
Acupressure
Rest
Conversion 2
Encore
Taunt
Torment
Disable
Imprison
Aromatherapy
Heal Bell
Memento
Spite
Psych Up
Heart Swap
Power Swap
Guard Swap
Power Trick
Power Split
Guard Split
Lock-On
Transform
Lunar Dance
Healing Wish
Wish
Gastro Acid
Role Play
Baton Pass
Teleport
Magnet Rise
Helping Hand
Destiny Bond
Grudge
Soak
Simple Beam
Entrainment
Shell Smash
Reflect Type
Bestow
After You
Quash
Ally Switch
Trick-or-Treat
Forest's Curse
Flower Shield
Topsy-Turvy
Electrify
King's Shield
Powder
Spiky Shield
Baneful Bunker
Purify
Strength Sap
Laser Focus
Speed Swap
Spotlight
Instruct
</details>

**Comment by urkerab** [comment]
You might want to add the side condition manually in case it was already set for some weird reason. (C uses healing wish, D is fresh so it stays active, D's healing wish fails because A and C have both fainted, but C's healing wish still heals B after an Ally Switch.)

**Comment by Karthik99999** [comment]
> Yeah actually now that you mention it, ally switch activating a stored Healing Wish is also a bug, right?

No this is intended (there's even a test for this).

**Comment by DaWoblefet** [comment]
Thanks Karthik!

**Pull request merged**
