### PR TITLE
Use onAfterMoveSecondary for Magician effect

### PR DESCRIPTION
**Pull request by Karthik99999**
This was done to fix the timing of item activation for Magician, which currently steals these items before they can activate. The bug report for this Magician interaction stated this happening to Weakness Policy, but Magician should interact in the same way with the other items I have changed. Should I add additional tests for the other items like Snowball, Cell Battery etc.?

### CODE REVIEW

**Comment by Karthik99999** [comment]
After taking a look at #8104, I tried changing magician to use onAfterMoveSecondary, and it worked while the items I changed were reverted back to using onDamagingHit.

**Comment by DaWoblefet** [comment]
This looks correct to me! PS's onAfterMoveSecondary is in the Sheer Force-negated block which is where Magician is supposed to live. I'll let Marty sign off.

**Review by DaWoblefet — APPROVED** [review]

**Comment by Marty-D** [comment]
There don't seem to be any existing tests for Magician actually working correctly, so it isn't very surprising that this skipped test passes since it's expecting Magician not to work. `AfterMoveSecondary` is for effects where the move's target is the Pokemon with the Ability. I think `AfterMoveSecondarySelf` with the source and target parameters swapped will do what you want.

**Review by Marty-D — APPROVED** [review]
That was quick; looks good, thanks! 👍

**Pull request merged**
