### PR TITLE
Namelock: Prevent strange hostfilter lock behavior

### PR DESCRIPTION
**Pull request by panpawn**

### CODE REVIEW

**Comment by Zarel** [comment]
Why...?

**Comment by Zarel** [comment]
My first rule of UI design: The purpose of a computer is to do things for you. If your computer is telling you to do things for it, you have failed at UI design.

**Comment by Zarel** [comment]
In other words: Instead of telling a user to do something, why not just... do it for them?

**Comment by panpawn** [comment]
Okay, I'll update this when I have time

**Comment by DaWoblefet** [comment]
This is no longer an issue; you can namelock people locked via #hostfilter now.

**Pull request closed without merging**
