### PR TITLE
Fix Nightmare not getting removed after certain curing effects

### PR DESCRIPTION
**Pull request by Karthik99999**

### CODE REVIEW

**Review by AnnikaCodes — CHANGES_REQUESTED** [review]
Can you please push another commit or rebase this so that GitHub reruns the CI with the latest fixes for the TypeScript issues?

**Comment by gigalh128** [comment]
Could you add the fix for gen 2 as well? https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9228860

**Comment by Karthik99999** [comment]
> Could you add the fix for gen 2 as well? https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-9228860

The changes I made should already fix this

**Comment by DaWoblefet** [comment]
Thanks Karthik!

**Pull request merged**
