### PR TITLE
Add Obstruct in list of protection moves

### PR DESCRIPTION
**Pull request by ZardMX**

### CODE REVIEW

**Comment by Marty-D** [comment]
Please put the previous descriptions in the Gen 7 mod. Things that don't exist in old gens shouldn't be mentioned there.

**Comment by ZardMX** [comment]
I'm a little bit confused here, where do we see those descriptions except in the code? I mean for example the move Protect has a different desc in gen 2 than in gen 8 but it shows the shortDesc to me when I am in a gen 2 battle.

**Comment by Zarel** [comment]
They're not currently used, but future-proofing is probably a good idea.

**Comment by ZardMX** [comment]
Why is Travis not checking the changes from my latest commit?

**Comment by Zarel** [comment]
Because it has a merge conflict. You'll need to fix the merge conflict before Travis can check it.

**Comment by ZardMX** [comment]
Let me know if I messed up anything while fixing the merge conflict.

**Pull request merged**
