### PR TITLE
Sim: Implement Gen 7 forced slot switching

### PR DESCRIPTION
**Pull request by Slayer95**
In SM Doubles switch requests, if the player team is all fainted except for one Pokémon, it must switch on the left side.

https://www.youtube.com/watch?v=x4Xgc3JNUz0&feature=youtu.be&t=23m8s

### CODE REVIEW

**Comment by Slayer95** [comment]
Client PR: Zarel/Pokemon-Showdown-Client/pull/1259

**Comment by AnnikaCodes** [comment]
@Slayer95 are you going to work on this or any of your old PRs?

**Comment by Zarel** [comment]
This is close to done so I'd pick it up even if Slayer95 didn't want to finish it.

**Comment by mia-pi-git** [comment]
Going to close this since it's been inactive for several years. Please feel free to reopen it if you're going to work on it again.

**Pull request closed without merging**
