### PR TITLE
Bug Fix: Neutralizing Gas Ending Issues

### PR DESCRIPTION
**Pull request by aviettran**
> Neutralizing Gas wearing off should cause entrance Abilities to reactivate in order of Speed

> Neutralizing Gas should not wear off twice after suppression

neutralizinggas test from #7857

### CODE REVIEW

**Comment by DaWoblefet** [comment]
I'm going to test the following just to make sure:
- Check if it uses raw / summary screen Speed or Speed with modifiers (I expect Speed with modifiers)
- Check if non-entrance Abilities also activate in order of Speed. E.g. would the Speed of two Defiant & Intimidate Pokemon determine if Defiant gets an Attack boost? (I expect no)
- Does Unnerve still have priority? (I expect yes)

These would be because I expect whatever event we run for Abilities coming in naturally (e.g. the start of the game, or two switchins after a double KO) is what Neutralizing Gas actually does. I'll double check and get back to you.

**Comment by DaWoblefet** [comment]
Good thing I tested! My assumption was wrong about Unnerve - it doesn't have priority on reactivation, unlike regular switchins. Neutralizing Gas does use Speed sorting with modifiers (e.g. Choice Scarf is included). It also doesn't turn on the abilities one at a time. It's more like just entrance abilities are turned on one at a time. For example, if I have fast Intimidate vs. slow Defiant, Intimidate will still trigger Defiant and give a +1 boost.

So I think the direct call to Speed sort like you've done is actually preferable here. I will add a test for that sort of Defiant / Intimidate behavior to ensure nothing's wrong there.

**Comment by DaWoblefet** [comment]
Ugh, I messed up a push. Sorry about that xfix, you can ignore.

**Comment by DaWoblefet** [comment]
On topic, I added Defiant and Unnerve tests. Of note is that I had to skip the Unnerve test because apparently PS has another bug with Unnerve and Neutralizing Gas. On cart, if Unnerve was active, then negated by Neutralizing Gas, then Neutralizing Gas leaves, Unnerve doesn't visibly reactivate - it does negate Berries and all, it just doesn't display the message. But if Unnerve never activated initially and Neutralizing Gas lets it start, then it does display a message. I have two tests for that behavior.

**Review by DaWoblefet — APPROVED** [review]
I'm ok leaving the Unnerve issue unsolved for now. This is a pretty relevant fix for Doubles play so I'm very happy with it.

**Review by Marty-D — APPROVED** [review]
👍

**Pull request merged**
