### PR TITLE
Gigantamax forme change is client-only

### PR DESCRIPTION
**Pull request by urkerab**
Despite accepting that his other reports were invalid the reporter here https://www.smogon.com/forums/posts/8312554 is defiant(!) about this one...

### CODE REVIEW

**Comment by urkerab** [comment]
DaWoblefet confirmed this for me.

**Comment by Zarel** [comment]
Honestly, I was going to have it governed by a flag on the Dynamax thingy.

**Comment by urkerab** [comment]
Oh, you mean that when you tell the client that you're Dynamaxing, you include the Gigantamax flag? I was worried that would confuse the client in the case where a natural forme change happens during Dynamaxing, which shouldn't wear off at the end of Dynamax.

**Comment by Zarel** [comment]
I'm pretty sure those wouldn't interfere.

But yes, I mean `|-start|POKEMON|Dynamax|Gigantamax`

**Comment by Zarel** [comment]
But I wonder if this should also apply to other cosmetic forme changes? Like idk, Mimikyu?

**Comment by urkerab** [comment]
That's not cosmetic; when Mimikyu's Disguise is busted, its speed, type, weight, etc. all reset, while Dynamaxing doesn't reset speed, type or weight.

**Pull request merged**
