### PR TITLE
Fix excluding variables in /ms

### PR DESCRIPTION
**Pull request by aviettran**
For !recovery, !recoil, and !pivot. !zrecovery was fine, but I added tests.

### CODE REVIEW

**Comment by aviettran** [comment]
@DaWoblefet

**Review by DaWoblefet — APPROVED** [review]
Tests look good.

**Comment by Zarel** [comment]
Merge conflicts :(

**Comment by aviettran** [comment]
> Merge conflicts :(

Resolved.

**Comment by DaWoblefet** [comment]
Thanks!

**Pull request merged**
