### PR TITLE
Let's Go: Mega Evolve Y & Itemless Megas

### PR DESCRIPTION
**Pull request by EvezaGit**
In Gen 7 Let's Go formats, these changes allow Pokemon to Mega Evolve without a held item, and allow Pokemon with multiple Mega Evolutions to choose between their Mega Evolutions during battle. This is accurate to cartridge. Have tested fairly extensively on my side server, so hopefully it all works! 

This pull request has been made simultaneously with one for smogon/pokemon-showdown-client.

### CODE REVIEW

**Comment by DaWoblefet** [comment]
Good start! Is there any particular reason to split up the protocol here into a mega and megay, as opposed to say, supporting an additional optional parameter on ``mega`` to a specific X or Y?

**Comment by EssCode** [comment]
> Good start! Is there any particular reason to split up the protocol here into a mega and megay, as opposed to say, supporting an additional optional parameter on `mega` to a specific X or Y?

Have tried that approach in the past and it generally felt less convenient to implement- much easier to add a new simple parameter than to refactor every use of the mega value. Could try and implement it that way in the future as it's technically cleaner but this felt better than nothing for the time being

**Comment by DaWoblefet** [comment]
It sounds to me like just adding a new parameter for the X/Y forms, and then you've got the logic for Mega Evolution without items already. Since all you're adding is an additional parameter, it's not a huge refactor of the protocol. I also think it's weird to assume X is the default Mega when you pick between two Megas.

**Comment by KrisXV** [comment]
I'm pretty sure X is assumed to be default purely because it's before Y alphabetically. Either way, this is already a lot of work, so changing it entirely again would be a lot of work. This is a good stepping stone IMO until a refactor happens later down the road, because a refactor of that level would require a lot of bugfixing from my experience.

**Comment by DaWoblefet** [comment]
My concern is that if we add this new megay protocol, then refactor it, you have to keep the old megay protocol around on the client to support older replays with it. We also have a lot of code reduplication that shouldn't be needed. Like granted, LGPE isn't exactly our highest-activity format or anything, but I think we can do it and it won't be _super_ bad.

**Comment by EssCode** [comment]
That's a reasonable concern. I can look into the parameter alternative tomorrow if it's nobody else's priority, should help that I'm more familiar with the way the client and server interface now.

**Comment by EssCode** [comment]
Nope, that kind of implementation is still beyond me. Before even considering the issue of turning every instance of canMegaEvo into an array, adding a parameter to 'mega' in the choose command is finicky enough, as is carrying the value of that parameter all the way to runMegaEvo. If anyone else wants to give it a shot in the near future that would be great, otherwise this is somewhat awkward as there's some minor interest in LGPE VGC and this mechanic is quite important there.

**Pull request closed without merging**
