### PR TITLE
Datasearch: Improve dexsearchhelp & movesearchhelp

### PR DESCRIPTION
**Pull request by Distrib-ps**

### CODE REVIEW

**Comment by AnnikaCodes** [comment]
@Zarel do you have opinions on this?

**Comment by Distrib-ps** [comment]
Bump

**Review by AnnikaCodes — APPROVED** [review]
I'm not too opinionated about the design of help messages, but this looks OK to me. It might be worth moving "The order of the parameters does not matter." to the summary; that seems at least as relevant to the average user than a list of supported tiers?

**Comment by Zarel** [comment]
Sorry, I think I missed this.

As far as I can tell, all this does is hide a bunch of the help behind a readmore. Is there a reason for this?

**Comment by Zarel** [comment]
I'm not against this but I'd prefer to understand more about why people want this.

**Comment by Distrib-ps** [comment]
Requested on discord :

**Comment by Zarel** [comment]
@AnnikaCodes? I'll let you decide I guess.

**Comment by AnnikaCodes** [comment]
I wanted a readmore because it makes broadcasting the help for these commands much less spammy. I think this would be a good usecase for your `readmore-broadcast` idea.

**Comment by Zarel** [comment]
There's no need to block this PR on that. It's been open a long time, let's merge and implement `readmore-broadcast` some other time.

**Comment by Zarel** [comment]
Thanks, @Distrib-ps!

**Pull request merged**
