### PR TITLE
SSB: Batch Update

### PR DESCRIPTION
**Pull request by Nolnis**
Name change that I missed in my batch update

### CODE REVIEW

**Comment by Zarel** [comment]
This will have to wait a month for another batch, unfortunately.

**Comment by Instructing** [comment]
Hi Instruct here!
I'm heavily against doing this, or else I would've done it myself, because of the reason of why I namechanged is why I haven't transferred this from the previous username to this one. PM me on PS for more information.

**Comment by Instructing** [comment]
Hi nol! Instruct here!!!!

Just so you know, this is about half done in regards to a namechange (sorry that I didn't see your previous pr) for ssb, but you'll also have to update the name in ssb/random-teams.js (or however its formatted) or else the quotes will not show up. Thanks!

**Comment by Zarel** [comment]
> Just so you know, this is about half done in regards to a namechange (sorry that I didn't see your previous pr) for ssb, but you'll also have to update the name in ssb/random-teams.js (or however its formatted) or else the quotes will not show up. Thanks!

I think the best solution to this sort of problem is to group things together in their own file, rather than leaving them spread out over multiple files.

**Comment by Zarel** [comment]
Thanks!

**Pull request merged**
