### PR TITLE
RoomGame: Support a second game in room.subGame

### PR DESCRIPTION
**Pull request by AnnikaCodes**
I feel like there's something more to do here but I can't think of what it would be.

### CODE REVIEW

**Comment by Zarel** [comment]
I wonder if players should be synced?

**Comment by AnnikaCodes** [comment]
I mean, the whole point of Mastermind is that each round has only a subset of the main game's players. I think that maintaining one player list for both the main and sub games would be too restrictive and make this less useful.

**Comment by Zarel** [comment]
Oh, I see. Interesting.

**Comment by Zarel** [comment]
Hm, after a brief review, this is probably enough.

If you want to do this on hard mode, you could add assertions (i.e. by throwing for unexpected state). But considering we already get plenty of unexpected state, that might not be advisable in practice.

**Comment by AnnikaCodes** [comment]
If we get a lot of unexpected state I don't think that throwing would be a good idea, at least not in production

**Comment by Zarel** [comment]
Fair. I do want to investigate, but there's no need to block this on that.

**Pull request merged**
