### PR TITLE
Punishments: Support giving multiple punishments to one user

### PR DESCRIPTION
**Pull request by mia-pi-git**
Title. Useful functionality - this should work for both rooms and global punishments.
Not sure on some of the function names (see `PunishmentMap#deleteOne`, `PunishmentMap#each` (though that was necessary because forEach didn't work with the type overload of wanting to call the callback once per each punishment object))

### CODE REVIEW

**Review by AnnikaCodes — COMMENTED** [review]
Review sent on Discord as requested.....

**Comment by AnnikaCodes** [comment]
(CI is failing)

**Comment by mia-pi-git** [comment]
I hate TS 4.3 ;_;

**Comment by mia-pi-git** [comment]
OK, fixed it.

**Review by AnnikaCodes — APPROVED** [review]
OK, this looks good. Thanks! I'll merge this tomorrow, when I have time to hotpatch it and monitor the server.

**Pull request merged**
