### PR TITLE
Remove restrictions on concurrent battle searches

### PR DESCRIPTION
**Pull request by scheibo**
https://www.smogon.com/forums/threads/improve-searching-for-concurrent-ladder-battles.3660989/

### CODE REVIEW

**Comment by Zarel** [comment]
I wonder if there's a compromise solution here?

**Comment by Zarel** [comment]
We talked about this in Staff.

The only thing I want to fix is the case of "player is losing, player starts a new game but leaves the old game open (which is bad manners), instead of just forfeiting".

Most other games straight-up don't allow concurrent games, which is their solution. I do agree that our current solution is too harsh; I just wish we had a better one.

**Comment by Zarel** [comment]
For everyone at home watching: I _did_ propose removing restrictions completely, and I'm fine with it as a last resort, but I do wish there was something better than nothing we could do about it.

**Comment by scheibo** [comment]
I don't really care to police bad manners nor do I have an elegant solution for doing so. Its 3 minutes and the person on the other end can open a new game themselves and be notified if their rude original opponent comes back.

**Comment by Zarel** [comment]
I guess that's valid enough.

**Pull request merged**
