### PR TITLE
Smogon master

### PR DESCRIPTION
**Pull request by hsahovic**

### CODE REVIEW

**Comment by hsahovic** [comment]
Oops, I did it again. Sorry about that - please disregard this PR.

**Comment by Zarel** [comment]
I still think we can just integrate your fork into master. If you'd like, I can write the code myself.

**Comment by hsahovic** [comment]
That would be amazing :) How would you like to proceed?

**Comment by Zarel** [comment]
I would probably add config settings for:

`noThrottle` - remove all the timer-based throttles

`noAltChecking` - remove all IP-based limits

`noGuestAuthentication` - remove the client signature authentication

And then a command-line flag `--no-security` to quickly remove all of the above.

**Comment by Zarel** [comment]
Is this all you need? Am I missing anything?

**Comment by hsahovic** [comment]
I think you got everything yep :) I just want to make sure `noThrottle` would also remove limits such as max number of concurrent challenges / battles, in addition to time-based limits

**Comment by Zarel** [comment]
@mia-pi-git next is the command-line flag, `./pokemon-showdown start --no-security 8000`

Do you want to handle that?

**Comment by mia-pi-git** [comment]
> @mia-pi-git next is the command-line flag, `./pokemon-showdown start --no-security 8000`
> 
> Do you want to handle that?

#7648

**Pull request closed without merging**
