### PR TITLE
Allow Weezing-Galar to have a VC transfer move without its Hidden Ability

### PR DESCRIPTION
**Pull request by Karthik99999**
hardcoded but I don't think there's another solution (aside from remove Galarian Weezing's HA in the gen 7 mod but that seems dumb)

### CODE REVIEW

**Comment by Zarel** [comment]
How do you teach it this move in-game?

**Comment by Karthik99999** [comment]
> How do you teach it this move in-game?

Kanto Koffing, which you can obtain from the virtual console with its gen 1-2 specific moves (such as Zap Cannon), can evolve into Galarian Weezing after being transfered to SwSh. Since this Koffing doesn't have its hidden ability due to not having one at the time of the VC transfer release, the resulting Galarian Weezing is allowed to not have its hidden ability as well.

**Comment by Zarel** [comment]
Can you give an example of a VC transfer move?

**Comment by KrisXV** [comment]
> Can you give an example of a VC transfer move?

Zap Cannon, Bide, Rage

**Comment by Zarel** [comment]
I suppose Rage works.

**Comment by KrisXV** [comment]
Zap Cannon is the only move legal in Sw/Sh though

**Comment by Zarel** [comment]
I was asking to write the unit test, but it turns out there's already a Zap Cannon Koffing unit test.

**Comment by urkerab** [comment]
I was thinking that the 7V source would need to include the species being transferred, so that the validator would ensure that if we were in fact transferring a 7V Koffing that there weren't any moves specific to 7V Weezing moves in the moveset, but no such move exists, so that's not a problem.

**Pull request closed without merging**
