### PR TITLE
Body Press uses SpD boosts under Wonder Room

### PR DESCRIPTION
**Pull request by urkerab**
Body Press tries really hard to use the attacker's Def, and it's almost clever enough to compensate for Wonder Room, but it turns out that it then goes on to use the attacker's SpD boosts.

Sorry, but I can't remember which researcher discovered this quirk.

### CODE REVIEW

**Comment by Zarel** [comment]
We can add a hint here, right? "Wonder room, Body Press used" is public information, right?

**Comment by Zarel** [comment]
(@DaWoblefet, @Marty-D)

**Comment by Marty-D** [comment]
You're right, it wouldn't be an info leak.

**Comment by Zarel** [comment]
@urkerab pls do

**Comment by urkerab** [comment]
Something like this?

**Comment by Zarel** [comment]
In hindsight, you should probably check boosts for both Def and SpD.

**Pull request merged**
