### PR TITLE
Tournaments: Modernize permission checking

### PR DESCRIPTION
**Pull request by KrisXV**

### CODE REVIEW

**Review by Zarel — APPROVED** [review]

**Comment by Zarel** [comment]
I'd merge this now but I'm afraid I'll forget to update the server's permissions. This'll have to wait until I'm at my computer again.

**Comment by KrisXV** [comment]
Speaking of which, config still needs updated from the prizewinner permission changes (in both the prizewinner rank itself and in RO)

**Comment by Zarel** [comment]
Has Prize Winner been fixed yet? I haven't heard anything about that.

**Comment by Zarel** [comment]
Thanks, btw!

**Pull request merged**
