### PR TITLE
Add Clanger as an Alias for Kommo-o

### PR DESCRIPTION
**Pull request by ACakeWearingAHat**
This has been used by both the UU community and the sim in general as the colloquial term for kommo-o for years at this point. Ask Estarossa, Lilburr, and other UU community members for confirmation if needed.

### CODE REVIEW

**Comment by Zarel** [comment]
There were a few others in the suggestions thread. Do you want to add them all at once?

**Comment by ACakeWearingAHat** [comment]
Honestly I did this independently from the suggestions thread but yeah, that sounds good

**Comment by ACakeWearingAHat** [comment]
and by that i mean feel free to alias whatever has enough approval; i am not in enough communities to comment on most of the ones in the thread

**Comment by Zarel** [comment]
Hm, let's just accept this separately, then.

**Pull request merged**
