### PR TITLE
Document restriction rules

### PR DESCRIPTION
**Pull request by urkerab**

### CODE REVIEW

**Comment by Zarel** [comment]
I was hoping to have examples of restrictions here. Like, I definitely was very confused about what a restriction was until I saw an example. I think it would help a lot here.

**Comment by urkerab** [comment]
As in a list of OMs and how they use restrictions?

**Comment by Zarel** [comment]
Not the entire list, but just a few examples so people can better understand what restrictions are for.

**Comment by urkerab** [comment]
OK, I picked 4 OMs and used them as examples.

**Comment by Zarel** [comment]
This is great! Much clearer than before! Thanks!

**Pull request merged**
