### PR TITLE
SSB: Update several ranks

### PR DESCRIPTION
**Pull request by Nolnis**
Update ranks of SSB fighters.

### CODE REVIEW

**Comment by Zarel** [comment]
I heard something about Dragontite?

Anyway, I think one-month delay for batching seems probably appropriate?

**Comment by KrisXV** [comment]
Yeah, it should be %Celestial instead of +Dragontite now

also, if by 'appropriate' you mean now/sometime soon then I agree; I don't see a point in trying to work on updating the SSB rank system to be automated when there's going to be one replacing it eventually (which we can do an automated rank system there instead)

**Comment by HoeenCoder** [comment]
Automation of this is on my TODO list for SSB4

**Comment by Asheviere** [comment]
I already DM'd you but I wanted to change my quotes in there as well while you're at it changing minor things :)

**Comment by KrisXV** [comment]
Promote Robyn to leader too, @Nolnis

**Comment by Zarel** [comment]
The error's inexplicable... Do any of you know what it's about?

**Comment by TheJetOU** [comment]
> The error's inexplicable... Do any of you know what it's about?

TypeScript always seemed to have issued with this type of code—pulling it out to a variable usually works for me.

**Comment by Zarel** [comment]
That did end up fixing it, yes. This will need an update to be fixed for real, though.

**Comment by Zarel** [comment]
(i.e. promote Robyn to Leader, that should fix the error.)

**Comment by Nolnis** [comment]
@KrisXV Robyn isn't in ssb unless there's a name change I missed

**Comment by TheJetOU** [comment]
> (i.e. promote Robyn to Leader, that should fix the error.)

What? How would pushing an unrelated commit somehow rebase Nolnis' branch?

**Comment by Zarel** [comment]
> What? How would pushing an unrelated commit somehow rebase Nolnis' branch?

GitHub Actions automatically merges the target branch before running tests. Or at least they say they do.

**Comment by Zarel** [comment]
Okay, it's been a month. Assuming @Nolnis is the one currently maintaining SSB rank updates, you should open a PR whenever the next update happens, but keep in mind that it won't be merged until it accumulates a month of updates.

**Pull request merged**
