### PR TITLE
Support hotpatching formats without reloading processes

### PR DESCRIPTION
**Pull request by mia-pi-git**
Should make it a lot easier to hotpatch formats consecutively, without worrying about memory from extra processes lying around. 

This will require a restart.

### CODE REVIEW

**Comment by Slayer95** [comment]
This probably helps with memory spikes in such scenarios. However, hotpatching doesn't internally remove the old code from memory (``require.cache = {}``) doesn't help. So that would mean going back to the time when PS needed to be restarted every week / few days.

Hence, If this goes through, there would still need to be another way to respawn the simulator processes.

**Comment by Slayer95** [comment]
See also https://github.com/nodejs/node/issues/8443

**Comment by mia-pi-git** [comment]
> This probably helps with memory spikes in such scenarios. However, hotpatching doesn't internally remove the old code from memory (`require.cache = {}` doesn't help.) So that would mean going back to the time when PS needed to be restarted every week / few days.
> 
> Hence, If this goes through, there would still need to be another way to respawn the simulator processes.

Does deleting the cache remove the reference? It seems to work fine in chat hotpatches?

**Comment by Slayer95** [comment]
Unfortunately, it's unclear how thorough is enough. There is also the V8 code cache, that won't get cleared even if the Node.js modules are.

**Comment by Slayer95** [comment]
What I'd suggest is tracking the active battles when ``/hotpatch`` is ran, and schedule a non-stackable task to run ``Rooms.PM.respawn()`` when they are all over. If battles are hotpatched again, then the task for respawn is overriden.

**Comment by AnnikaCodes** [comment]
Do old battle simulation processes still cause memory problems? Our server consistently has 20+ GB free and I don't think child processes' memory usage counts against the main process's Node memory cap.

As a test, I just hotpatched formats on Main. Before the hotpatch:
> [Main process] RSS: 3.03 GiB, Heap: 1.61 GiB / 2.57 GiB
(and ~3.5 GB used by all battle simulator processes with 36G available)

After: 
> [Main process] RSS: 3.07 GiB, Heap: 1.71 GiB / 2.60 GiB
(and ~3.8 GB used by all battle simulator processes with 36G available, which later went up to 4.1G with 35G available)

So I'm not sure how important saving memory here is. If we can figure out how to flush the cache properly and reliably it would be an improvement, but I don't think having a larger permanent memory usage increase after hotpatching (necessitating more restarts) is a good tradeoff.

**Comment by mia-pi-git** [comment]
Agreed, probably not worth it.

**Pull request closed without merging**
