### PR TITLE
Make gmax chip damage occur in speed order

### PR DESCRIPTION
**Pull request by Karthik99999**
https://github.com/smogon/pokemon-showdown/projects/3#card-51997606

Would've liked to fix the other gmax chip damage related bugs, but this should do for now.

### CODE REVIEW

**Comment by Marty-D** [comment]
Although this was my idea I don't particularly love it since it only takes care of the one issue and makes the others harder to fix. I'd like to know if @pyuk-bot's idea panned out or whether she thinks it's still feasible before committing to this solution for now.

**Comment by Zarel** [comment]
One thing we could do is separate `onResidual` from `onSideResidual` and `onFieldResidual`.

**Comment by Zarel** [comment]
This would require residual events to be even weirder than they already are, though.

**Comment by DaWoblefet** [comment]
This was superseded by https://github.com/smogon/pokemon-showdown/pull/8222.

**Pull request closed without merging**
