### PR TITLE
Fix Egg Moves on Ursaluna-Bloodmoon and Greninja-Bond

### PR DESCRIPTION
**Pull request by Karthik99999**
Normally this isn't a hardcode we'd want but making the egg moves work "normally" would be equally as messy so just sticking the egg move sources into their normal learnsets is the easiest solution.

### CODE REVIEW

**Comment by DaWoblefet** [comment]
The "correct" solution seems to me to be something like you attach some property to Blood Moon and Greninja-Bond that tells them to specifically inherit egg moves from Teddiursa and Froakie. I gave that a whirl and wasn't able to get it to work with _only_ Egg Moves by leveraging ``learnsetParent``, but that will pull in everything (e.g. Blood Moon shouldn't be able to get Aerial Ace). If anyone else has a better idea for a generic implementation I'm open, but hardcoding as egg moves is also fairly straightforward.

**Comment by KrisXV** [comment]
> The "correct" solution seems to me to be something like you attach some property to Blood Moon and Greninja-Bond that tells them to specifically inherit egg moves from Teddiursa and Froakie. I gave that a whirl and was sort of able to get it to work by using `learnsetParent`, but that pulled in everything, and we want _only_ Egg Moves (e.g. Blood Moon shouldn't be able to get Aerial Ace). If anyone else has a better idea for a generic implementation I'm open, but hardcoding as egg moves is also fairly straightforward.

i think i'd prefer this route since we'd likely get another instance of this in dlc2 as well

**Comment by urkerab** [comment]
Are these the only two species that are male-only and have a different learnset to their base forme?

**Comment by DaWoblefet** [comment]
> Are these the only two species that are male-only and have a different learnset to their base forme?

Being male-only really has nothing to do with it; the issue is that Teddiursa and Froakie can't ever evolve into Greninja-Bond and Ursaluna-Bloodmoon. They could be female-only and have the same problem. The relation is only the other way around.

**Comment by DaWoblefet** [comment]
I'm going to merge for now, since this fixes a relevant legality bug.

**Comment by urkerab** [comment]
> Being male-only really has nothing to do with it;

Actually I was looking for a property that tells them to explicitly inherit egg moves.

**Pull request merged**
