### PR TITLE
Refactor Sockets to ProcessManager+TypeScript

### PR DESCRIPTION
**Pull request by Zarel**
This is fully working except for crash recovery.

Closes #5795

### CODE REVIEW

**Comment by Zarel** [comment]
There's also a bunch of sockets tests that need to be rewritten now...

**Comment by Zarel** [comment]
I spent a lot of time thinking about how ProcessManager should abstract something like this. In the end, I went for `RawProcessManager` - a process manager that specifically puts a single stream into a subprocess.

**Comment by Kaiepi** [comment]
I wouldn't worry too much about the sockets tests. There's more work that needs to be done with sockets in order to make them testable in a more efficient way anyway.

**Comment by Zarel** [comment]
The sockets tests are skipped right now, anyway. It turns out I just needed to fix `users-utils`. Now the only thing left is crash recovery.

**Comment by Zarel** [comment]
@scheibo @Kaiepi I think you're the only ones with the right technical knowledge to review this.

Personally the part I'm most indecisive about are class names; I'm not a huge fan of `StreamWorker`.

**Comment by Zarel** [comment]
(For the record, I'd still like a review, whenever you have time.)

**Pull request merged**
