### PR TITLE
Fix keeberry activiating due to present healing

### PR DESCRIPTION
**Pull request by Volco**
https://github.com/Zarel/Pokemon-Showdown/projects/3#card-25870237

### CODE REVIEW

**Comment by Volco** [comment]
Probably not the best possible fix for this but for now it should work fine for it's purpose

**Comment by Zarel** [comment]
Genius. But yes I'm somewhat afraid of side effects. @Marty-D?

**Comment by Marty-D** [comment]
I believe this would break interaction with King's Shield.

**Comment by Zarel** [comment]
Should Kee Berry check for 0bp attacks, then?

**Comment by Volco** [comment]
it would also break the baneful bunker interaction now that you mention king's shield

**Comment by Volco** [comment]
wait actually no, present isn't contact

**Comment by Marty-D** [comment]
It's not about being contact; King's Shield purposely doesn't block Status moves.

**Comment by Volco** [comment]
oh, i forgot it did that

**Comment by Volco** [comment]
okay, i tested it by forcing keeberry to always give hp for the test specifically. it is not an issue. the move still gets blocked by kings shield

**Comment by Volco** [comment]
instead of checking for 0bp why not check to see if it dealt damage. there was something added a while back that would allow checking if a mon took damage that turn and by who iirc.

**Comment by Zarel** [comment]
I'm pretty sure that this is wrong because other 0-damage moves would activate Kee Berry, such as False Swipe against a foe with 1 HP left.

**Comment by Volco** [comment]
Oh, hmm. Well i did test the interaction of healing present (Status) on king's shield and it was blocked by king's shield. Likely due to ``onModifyMove()`` runs after ``onTryHit()``

**Comment by Volco** [comment]
Once something is figured out what to do instead i will adjust the pr accordingly

**Comment by Volco** [comment]
so how should this be handled?

**Comment by Zarel** [comment]
We could keep track of this sort of thing in the `move.damage` property, which could treat `.damage === 0` separately from `.damage === null` or something.

**Comment by Volco** [comment]
sorry still been busy, will pick this back up once i have time
same for my other 2 prs

**Comment by Zarel** [comment]
Why was this merged? I thought Marty and I both pointed out this would introduce more bugs than it fixes.

**Comment by Zarel** [comment]
Especially since I was maintaining this part of the code and could easily have fixed it properly. :[

**Comment by TheImmortal** [comment]
It does not break King’s Shield as the user mentioned. So what bug are you referring to?

**Comment by Zarel** [comment]
There are too many tiny interactions. I'd rather just hardcode Kee Berry.

**Pull request merged**
