### PR TITLE
Sketch Gen 8 BDSP Update

### PR DESCRIPTION
**Pull request by EnPassant4264**
The whole point of the Sketch Gen 8 Moves rule is to _avoid_ hardcoding the team validator based on format, so this updates the BDSP formats to match.

Not sure where the first four commits came from since they're already on main.

### CODE REVIEW

**Comment by urkerab** [comment]
> Not sure where the first four commits came from since they're already on main.

Try rebasing instead of merging?

**Comment by EnPassant4264** [comment]
Okay, I rebased it, and that's where the 41 new commits here are.

**Comment by DaWoblefet** [comment]
With all the extra stuff in this PR, it's really hard to review. You can reach out to any of the devs on Discord (myself included) to help with fixing this up so it can be accepted.

**Comment by KrisXV** [comment]
The hardcode is fine since it applies to the entire BDSP mod

**Pull request closed without merging**
