### PR TITLE
Improve and simplify Random Battles tests

### PR DESCRIPTION
**Pull request by livid-washed**
For revamped formats, tests ensuring the correct structure of set data files, that every Pokemon (except Ditto and Unown) generates with four moves, and that all moves on all sets are obtainable, have been combined in a single code block in `all-gens.js`, instead of repeating mostly identical code for every format.

We have identified illegal moves in Gen 3 Random Battle and Gen 9 Baby Random Battle that were previously not caught due to mistakes or omissions with the tests, and modified the sets accordingly. Specifically:
- In Gen 3, Politoed does not learn Encore. Encore has been removed from its sets.
- In Gen 3, Rayquaza does not learn Swords Dance. The Bulky Setup set with Swords Dance has been removed.
- In Gen 9, Croagunk does not learn Close Combat or Swords Dance. The Fast Attacker set has been removed.
- In Gen 9, Meowth-Galar does not learn Thunder Wave. Thunder Wave has been removed from its sets.
- In Gen 9, Golett does not learn Stone Edge. Stone Edge has been replaced by Rock Tomb.

This also removes some old tests for past gens that are no longer necessary or useful due to the revamps.

### CODE REVIEW

**Comment by adrivrie** [comment]
Is there any particular reason the gen 2/3/4 files still exist?

**Comment by livid-washed** [comment]
> Is there any particular reason the gen 2/3/4 files still exist?

No reason. I'm not sure what the standard practice is but I can delete them.

**Review by ACakeWearingAHat — APPROVED** [review]
this isn't necessarily my area of expertise so don't take this review as any actual sign of quality and moreso take it as the rands room approving it

**Comment by DaWoblefet** [comment]
Looks good to me!

**Pull request merged**
