### PR TITLE
Rename the "mystery" and "authentic" move flags

### PR DESCRIPTION
**Pull request by pacmanboss256**
This PR changes the 'Mystery' flag and the 'Authentic' flag so they better represent what the flag actually means

### CODE REVIEW

**Comment by DaWoblefet** [comment]
I think it'd be helpful to completely modify the flag name from mystery -> ``animatesAgainstAllies`` and update all references.

Minimally, we should also make it clear that we don't currently reference this flag for PS's own animations.

**Comment by pacmanboss256** [comment]
I did this on my ipad so i had to do that manually. will fix later today

**Comment by Zarel** [comment]
I like `infiltrates` assuming it's not very different from Infiltrator. I believe PSdex uses `bypasssub`.

**Comment by KrisXV** [comment]
`infiltrates` is wrong, Infiltrator allows mons to hit around subs and screens, whereas the `authentic` flag just hits around substitute, so `bypasssub` would probably be better (also, `move.infiltrates` already exists for Infiltrator, so it'd cause some ambiguity imo).

**Comment by Zarel** [comment]
(Drafting because of the build error.)

**Comment by pacmanboss256** [comment]
i can make it `bypasssub`

**Comment by EvGym** [comment]
I think it might be more clear to rename animonally -> allyanimonly
It is a small detail but it is easier to read for me.
Good work on fixing these flags!

**Comment by KrisXV** [comment]
> I think it might be more clear to rename animonally -> allyanimonly
> It is a small detail but it is easier to read for me.
> Good work on fixing these flags!

its not ally-anim only though, so this would be wrong.

``allyanim`` might be better though

**Comment by Zarel** [comment]
I'm fine with `allyanim`. Maybe `targetallyanim` would be clearer though?

**Comment by KrisXV** [comment]
what does `targetallyanim` mean? I don't see how it's more clear

**Comment by Zarel** [comment]
"target" clarifies that the flag controls whether or not the animation plays when an ally is targeted. There are a lot of ways animations could involve alllies (being used by an ally doesn't seem like an unusual interpretation) so I think clarification could be nice there.

**Comment by Zarel** [comment]
ty!

**Pull request merged**
