### PR TITLE
Update item users on some items

### PR DESCRIPTION
**Pull request by Karthik99999**
https://www.smogon.com/forums/threads/bug-reports-v4-read-original-post-before-posting.3663703/post-8944777

- Added Marowak-Alola to Thick Club
- Added Farfetch'd-Galar to Leek
- Added all Pikachu formes to Light Ball

The bug report mentioned stuff like the base formes of things like Giratina and Zacian not having their forme specific items show up, but I didn't add them cause I feel like there was a reason this was done. If there isn't then I can do those too.

### CODE REVIEW

**Comment by DaWoblefet** [comment]
It makes sense to me not to include those forme change items - we don't want to recommend people choosing Giratina with Griseous Orb and Pressure, for example.

**Comment by DaWoblefet** [comment]
Oh actually, this is still missing Totem Alolan Marowak.

**Comment by Zarel** [comment]
Hm, I definitely wanted some way to specify "all formes" but this is probably a better implementation if it's only a few pokemon.

**Comment by DaWoblefet** [comment]
Thanks Karthik!

**Pull request merged**
