### PR TITLE
SSB: Fix Tiki image

### PR DESCRIPTION
**Pull request by Distrib-ps**

### CODE REVIEW

**Comment by mia-pi-git** [comment]
Why is this necessary? The image is fine as is.

**Comment by KrisXV** [comment]
> Why is this necessary? The image is fine as is.

No it’s not, it displays as a broken image when embedded.

**Comment by Distrib-ps** [comment]
Image does not work. I contacted him to give me a new link.

**Comment by xInstruct** [comment]
If you give me confirmation that tiki gave you the image link i’ll approve the pull request

**Comment by Distrib-ps** [comment]
> If you give me confirmation that tiki gave you the image link i’ll approve the pull request

**Review by xInstruct — APPROVED** [review]
yep that’s proof all right. Thanks!

**Pull request merged**
