### PR TITLE
Sim/`DexItems`: Deduplicate `Item` against parent mod

### PR DESCRIPTION
**Pull request by larry-the-table-guy**
Dedup for `Items`.

Very similar to #10658.

|   stage  | \`DexItems\` ret size | \`Items\` ret size | \`allMods.items.all()\` | total heap size |
| -------- | --------------------: | -----------------: | ----------------------: | --------------: |
| baseline | 8714 KB | 7485 KB | 125 ms | 256 MB |
| w/ dedup | 1445 KB |  830 KB | 102 ms | 250 MB |

19876 -> 2173 instances of \`Item\`, 6MB peak savings.

### CODE REVIEW

**Comment by Zarel** [comment]
Oh, I don't think I've gotten the MIT license from you yet. Could you repeat after me?

> I, [name], license all my contributions to Pokémon Showdown, past and future, under the MIT license.

**Comment by larry-the-table-guy** [comment]
> Oh, I don't think I've gotten the MIT license from you yet. Could you repeat after me?
> 
> > I, [name], license all my contributions to Pokémon Showdown, past and future, under the MIT license.
> 
> (It doesn't need to be your legal name if you don't want to give it)

Isn't it already MIT since I've got the same LICENSE file in my repo, based on https://github.com/smogon/pokemon-showdown/blob/master/CONTRIBUTING.md#license ?

But yeah, whatever license is fine with me.

**Comment by Zarel** [comment]
> Isn't it already MIT since I've got the same LICENSE file in my repo, based on https://github.com/smogon/pokemon-showdown/blob/master/CONTRIBUTING.md#license ?
> 
> But yeah, whatever license is fine with me.

Oh I'd forgotten that that policy was only for client PRs. Either way, the explicit license is nice to have, in case you make client PRs in the future.

**Comment by larry-the-table-guy** [comment]
Sure, no problem.

I, Larry, license all my contributions to Pokémon Showdown, past and future, under the MIT license.

(to be transparent, Larry is not my legal name. But it can represent whatever I do on this account)

**Pull request merged**
