### PR TITLE
Add Gen 7 Hackmons Cup

### PR DESCRIPTION
**Pull request by hilts-vaughan**
Is it possible to get this in the server since there are still other Gen7 metas? 

FYI I did test locally.

### CODE REVIEW

**Comment by TheImmortal** [comment]
Perhaps. Not as a ladder tho.

**Comment by TheImmortal** [comment]
And not doubles because that's even more niche.

**Comment by hilts-vaughan** [comment]
I know it's niche but I think the main gripe I had is that now it has a much larger Dex pool. I can always spin up my own server with this change (and I have) so it's not a deal breaker but I hope you will at least reconsider in the future. :)

**Comment by hilts-vaughan** [comment]
Thanks for merging my PR!

**Pull request merged**
