### PR TITLE
Add some common rooms to the roomid type

### PR DESCRIPTION
**Pull request by whalemer**

### CODE REVIEW

**Comment by Zarel** [comment]
Why did the first one fail unit tests? I couldn't figure out the error message.

**Comment by whalemer** [comment]
I accidentally changed some things from `function(param = 'thing' as RoomID)` to `function(param: thing)`, which changes the param type from RoomID to string

**Comment by Zarel** [comment]
Hmm.

**Comment by Zarel** [comment]
I'm not _sure_ if I like this...

**Pull request merged**
