### PR TITLE
Monotype Random Battle - Apply Gen7 Same Type Clause

### PR DESCRIPTION
**Pull request by xfix**

### CODE REVIEW

**Comment by TheImmortal** [comment]
While we're doing this, can you make ``isMonotype`` determined by ``Same Type Clause`` that way this can be applied to any random battle, not just ``gen7monotyperandombattle``.

**Comment by xfix** [comment]
Hm, that's interesting, I just tried doing this, and realized that PoTD thing doesn't work.

```javascript
		// PotD stuff
		let potd;
		if (global.Config && Config.potd && this.getRuleTable(this.getFormat()).has('potd')) {
			potd = this.getTemplate(Config.potd);
		}
```

**Comment by TheImmortal** [comment]
Yeah PoTD has been broken forever. Nobody bothered fixing it because we don't use it.

**Comment by TheImmortal** [comment]
@xfix ?

**Pull request closed without merging**
