### PR TITLE
Chat plugins: Support exporting plugin state

### PR DESCRIPTION
**Pull request by AnnikaCodes**
This will make it easier to debug chat plugins. I also added state to some of the plugins that I felt could use it.

### CODE REVIEW

**Comment by Zarel** [comment]
Looks great, thanks!

**Comment by Zarel** [comment]
I wonder if all the state was simply at the top level?

So instead of `export const state = {foo, bar};` you would `export foo` and `export bar`.

And then `Chat.plugins[pluginName]` would be everything the plugin exported except `commands` and `pages`.

**Comment by AnnikaCodes** [comment]
> I wonder if all the state was simply at the top level?
> 
> So instead of `export const state = {foo, bar};` you would `export foo` and `export bar`.
> 
> And then `Chat.plugins[pluginName]` would be everything the plugin exported except `commands` and `pages`. Maybe even including `commands` and `pages`.

Yeah, that seems like a better idea. Is there a reason to exclude `commands` and `pages`?

**Comment by Zarel** [comment]
> Is there a reason to exclude `commands` and `pages`?

You might reclaim some RAM, I guess? Probably worth keeping them.

**Comment by Zarel** [comment]
Looks good, thanks!

**Pull request merged**
