### PR TITLE
Fix bugs in chatlog date parsing

### PR DESCRIPTION
**Pull request by whalemer**
fuck the js date api

mia's doesn't work because `${date}-15` isn't guaranteed to be valid, ie `2010-04-5` is valid while `2010-04-5-15` isn't.

### CODE REVIEW

**Comment by Zarel** [comment]
Yes, I know, JavaScript's date API is super fucked up.

But, um, I was pretty sure our app doesn't need any advanced date parsing.

**Comment by Zarel** [comment]
What was wrong with the old code? I can't tell what this is trying to fix.

**Comment by whalemer** [comment]
`new Date(whatever)` parses `whatever` as UCT, `<date>.getDate` and friends read it back as local time.

**Comment by Zarel** [comment]
Oh! Yeah, that makes sense.

**Pull request merged**
