### PR TITLE
Fix Gmax forme validation

### PR DESCRIPTION
**Pull request by KrisXV**

### CODE REVIEW

**Comment by Zarel** [comment]
Wait, why not update the `isGigantamax` definition, instead of here?

**Comment by KrisXV** [comment]
because i edited this on the website and im not sure where else hoeen might have used this and dont want to break anything

**Comment by Zarel** [comment]
(Go up four lines.)

**Comment by KrisXV** [comment]
ok fine

**Comment by Zarel** [comment]
Oh, that's why Hoeen changed it; he wanted `isGigantamax` to be a string. Unfortunately, it's not set up yet, so you'll have to change it back to a boolean, too.

**Comment by KrisXV** [comment]
ok done

**Comment by Zarel** [comment]
It turns out you were right the first time, but now we know why. Progress, I guess?

**Pull request closed without merging**
