### PR TITLE
Add alt form index data to dex

### PR DESCRIPTION
**Pull request by scheibo**
Numbers obtained from kwsch/PKHeX's FormConverter.cs (thanks Kurt).
Thanks to @Lusamine (Anubis) for help with the peculiarities.

### CODE REVIEW

**Comment by scheibo** [comment]
I need to add tests (confirm no gaps or dupes in forme numbers for each gen), but I don't know how you would like me to handle numbering the 'cosmetic' formes. Please advise

**Comment by Zarel** [comment]
I think I would rather just have the `otherFormes` array in index number order, for the very niche use-cases where it's needed at all.

**Comment by scheibo** [comment]
@monsanto felt this was too fragile, and its also not possible given how PS does not map formes correctly to the formes on the cartridge. Natdex/keeping past and future gen formes around, FORMES.md, arbitrarily not supporting certain forms (Vivillon, Minior-Meteor colors) etc makes indexes into `otherFormes` not work

**Comment by Zarel** [comment]
That _would_ pose a problem for Pokémon with mixed cosmetic/non-cosmetic formes, most notably Vivillon and Floette.

I would probably merge cosmetic and non-cosmetic formes into the `otherFormes` array.

**Comment by scheibo** [comment]
Still impossible, please see the numbers on the indexes in the pokedex.ts and the comments Ive left

**Comment by Zarel** [comment]
PS can put nonexistent formes last, so the formes that actually exist are correctly indexed.

As far as I'm aware, PS currently only diverges from cartridge forme lists in two ways: we have Gmax formes, and we don't have formes for event abilities. We are planning to add formes for event abilities, and Gmax formes can be after all other formes.

**Comment by scheibo** [comment]
- natdex means Pikachu formes are incorrect (gen 6 pikachus are currently in the same other formes array as later gens, there are 2 different pikachu-forme0 depending on the gen)
- you need to add in minior meteor colored  formes and make minior meteor the base because minior meteor red is forme 0, minior red is forme 7
- you need to reorder vivillon to have its baseForme be Icy Snow, not Meadow which is forme 6
- pokestar formes are not formes

**Comment by Zarel** [comment]
Anyway I don't need to block on major data rearrangement. This is fine for now.

**Comment by scheibo** [comment]
> Anyway I don't need to block on major data rearrangement. This is fine for now

OK thanks, Im still not sure how to assign forme numbers to cosmetic formes before things get rearranged though?

**Comment by Zarel** [comment]
Alternatively, we could have a `formeOrder` array, which just lists all the formes by speciesName in in-game order?

**Comment by scheibo** [comment]
> Alternatively, we could have a `formeOrder` array (on the base species, next to `otherFormes`), which just lists all the formes by speciesName in in-game order? With duplicates for Minior-Meteor and event formes, for now?

I will do this in the morning. I believe i will need to change the gen 6 pokedex as well for pikachu. otherwise i will leave in formes that dont impact actual forme numbers (leaving LGPE's starter pikachu affects Pikachu-Gmax's forme number, but gmax isnt a forme so its unimportant)

**Comment by monsanto** [comment]
I was planning to tackle this soonish, pleasant surprise to wake up early and see it mostly done. Thanks all.

`formeOrder` sounds fine for now as it does not require cosmetics to have pokedex entries. Good idea

**Comment by Zarel** [comment]
Do you want this merged now? It looks good to me.

**Pull request merged**
