### PR TITLE
items.ts

### PR DESCRIPTION
**Pull request by Lucasrang**

### CODE REVIEW

**Comment by Lucasrang** [comment]
i would request the admins to pls accept this change

**Comment by DaWoblefet** [comment]
I'll repeat here; please stop opening PRs concerning Mega Luxray. We simulate the actual games, and will not add a fake Mega Pokemon to the main Pokedex.

**Comment by Lucasrang** [comment]
> I'll repeat here; please stop opening PRs concerning Mega Luxray. We simulate the actual games, and will not add a fake Mega Pokemon to the main Pokedex.

Well i saw a video of a mega garbodor so i thought we can do the same... sorry if it concerned you

**Comment by mia-pi-git** [comment]
> Well i saw a video of a mega garbodor so i thought we can do the same... sorry if it concerned you

Mega garbodor in that video was done on a side server, fwiw (you can do your own mons locally too! We on main just won't merge them.)

**Pull request closed without merging**
