### PR TITLE
Update commandline -h generate-team

### PR DESCRIPTION
**Pull request by adrivrie**
The -h for the command line tool (as well as the COMMANDLINE.md file) had as the default for the generate-team option "gen7randombattles". This should be gen9randombattles now.

### CODE REVIEW

**Comment by DaWoblefet** [comment]
There is no Gen 9 Random Battle yet, so this can't be the case.

**Comment by adrivrie** [comment]
It is, and running it without argument throws an error (because indeed there's no gen9 rands yet). I figured hard-defaulting it to gen8 now makes little sense as this hasn't been updated in years, and it will only keep failing for a limited time.

**Comment by DaWoblefet** [comment]
This will be merged once Gen 9 randbats goes live.

**Comment by AnnikaCodes** [comment]
Why not just write "the latest Random Battles format"?

**Comment by MathyFurret** [comment]
Beep :3

**Comment by monsanto** [comment]
Annika's suggestion seems reasonable to me

**Comment by adrivrie** [comment]
Changed it to the "latest Random Battles format".

**Comment by DaWoblefet** [comment]
Thanks adrivrie!

**Pull request merged**
