### PR TITLE
Fix Aura Wheel's interaction with dynamaxing

### PR DESCRIPTION
**Pull request by KrisXV**
This will need client side adjustment as well

### CODE REVIEW

**Comment by TZubiri** [comment]
This is also fixed here I believe.https://github.com/smogon/pokemon-showdown/pull/6080/commits/95b262051cb5daa4b575c86c11cb8362a3156711

**Comment by KrisXV** [comment]
That code doesn't exist in scripts.js...

**Comment by Zarel** [comment]
Specifically, it's fixed by #6080.

**Comment by Zarel** [comment]
I'm not even accepting #6080; I'm definitely not accepting the hardcode of a single move.

**Pull request closed without merging**
