### PR TITLE
Helptickets: Display shared battles in staffintro

### PR DESCRIPTION
**Pull request by AnnikaCodes**
[Requested by global staff](https://www.smogon.com/forums/threads/improving-help-tickets.3642984/page-6#post-8607392).

### CODE REVIEW

**Comment by Zarel** [comment]
Looks good!

**Comment by Zarel** [comment]
Importing from chat plugins may cause problems further down the line, but we can deal with them then, I think.

**Comment by AnnikaCodes** [comment]
Yeah, I don't usually like to import from *plugins* (my philosophy is that you should ideally be able to remove anything in the `chat-plugins/` directory and have PS work fine), but `info.ts` is in `chat-commands/` so I'm less wary of that. It'd be easy enough to move to `Rooms` but that would lose hotpatchability :x.

**Comment by Zarel** [comment]
I think it's easily monkeypatched, so if that's your only concern it's not a big deal.

**Pull request merged**
