### PR TITLE
Use BigInt for PRNG seed

### PR DESCRIPTION
**Pull request by xfix**
This makes `nextFrame` method so much simpler.

### CODE REVIEW

**Comment by Zarel** [comment]
I would prefer not using this specific modern feature because it makes interop more complicated.

**Comment by Zarel** [comment]
I... I see benefits to this. I do agree it makes the code simpler. I'm not a fan of how you seem to have dropped support for the old array format.

I think this is _marginally_ useful, but I don't think it's anywhere near useful enough to be worth dropping backwards compatibility for.

**Comment by Zarel** [comment]
Heck, I'm not even sure it's worth complicating `state.ts`.

**Comment by xfix** [comment]
Yeah, fair, reduced the scope of changes to `nextFrame`, hopefully that's acceptable.

**Comment by xfix** [comment]
Or I guess I can use `reverse()`.

**Comment by Zarel** [comment]
I... I guess I'm still not sure if I think this is worth dropping support for older JavaScript engines. Like, I'm aware that we already dropped support for Node versions not supporting BigInt, but it might be nice to keep the old one around.

The conversion between `PRNGSeed` and bigint is also kind of subtle, I don't know if it's worth requiring people to know `BigInt64Array` and the subtleties of big/little-endianness.

If we were concerned about readability, I would refactor it this way:

```ts
/** calculates `a * b + c` */
multiplyAdd(a: PRNGSeed, b: PRNGSeed, c: PRNGSeed) {
	const out: PRNGSeed = [0, 0, 0, 0];
	let carry = 0;

	for (let outIndex = 3; outIndex >= 0; outIndex--) {
		for (let bIndex = outIndex; bIndex < 4; bIndex++) {
			const aIndex = 3 - (bIndex - outIndex);

			carry += a[aIndex] * b[bIndex];
		}
		carry += c[outIndex];

		out[outIndex] = carry & 0xFFFF;
		carry >>>= 16;
	}

	return out;
}

nextFrame(seed: PRNGSeed, framesToAdvance = 1): PRNGSeed {
	const a: PRNGSeed = [0x5D58, 0x8B65, 0x6C07, 0x8965];
	const c: PRNGSeed = [0, 0, 0x26, 0x9EC3];

	for (int i = 0; i < framesToAdvance; i++) {
		seed = this.multiplyAdd(seed, a, c);
	}

	return seed;
}
```

**Pull request closed without merging**
