### PR TITLE
Add Ability Clause

### PR DESCRIPTION
**Pull request by HisuianZoroark**
Requested by UT

### CODE REVIEW

**Comment by KrisXV** [comment]
Rename to ability clause pls

**Comment by DaWoblefet** [comment]
Most of this code is shared with ``2abilityclause``. I wonder if there's a way to make this more generic in case we ever want ``3abilityclause`` etc.

**Comment by KrisXV** [comment]
Yes, we can change it into a value rule easily

**Comment by KrisXV** [comment]
I'll work on turning into a value rule in a bit, its better to get this in before gen 9 starts

**Pull request merged**
