### PR TITLE
Add a RoomBattle#challengeType property

### PR DESCRIPTION
**Pull request by TheJetOU**
This commit adds a `challengeType` property to `RoomBattle` of
type `rated | unrated | challenge | tour`.

Previously, there was no way to programatically differ an unrated
battle from a challenge, which is useful in places like filters.

(This pull request requires a restart.)

### CODE REVIEW

**Comment by Zarel** [comment]
Calling it `type` would probably make it confused with `Battle#gametype`. We should at least think of a better name.

**Comment by Zarel** [comment]
Two ideas, pick one:

- Just overload `rated` with `"Tournament" | "Unrated" | "Challenge" | number`
- Name this `challengeType`

**Comment by TheJetOU** [comment]
I'll go with `challengeType` because ``>> room.battle.rated`` returning `"Tournament"` feels weird.

**Comment by Zarel** [comment]
It actually already returns "Tournament".

**Comment by Zarel** [comment]
Well, `Battle#rated` does. `RoomBattle#rated` currently doesn't. But they should probably be updated to match, anyway.

**Comment by TheJetOU** [comment]
> Well, `Battle#rated` does. `RoomBattle#rated` currently doesn't. But they should probably be updated to match, anyway.

It doesn't. Am I doing something wrong?

```
>> room
<< GameRoom(battle-gen7randombattle-1)
>> !!room.tour
<< true
>> room.rated
<< 0
```

**Comment by Zarel** [comment]
I'm saying `Battle#rated` i.e. the `battle` object from `sim/`.

https://github.com/smogon/pokemon-showdown/blob/f6d5f9ddb8e03a05c7179d19214ce12f1d4d2ba9/sim/battle.ts#L65

This one.

**Comment by TheJetOU** [comment]
Hm, I am leaning more towards renaming it to something more sensible (maybe even renaming the protocol message?), because a `rated` property holding the string "Tournament Battle" is illogical and unexpected, for me at least.

I'm not too interested in taking that on though currently.

**Comment by Zarel** [comment]
That's fair. I should merge this soonish.

**Pull request merged**
