### PR TITLE
Add Pokemon Home support

### PR DESCRIPTION
**Pull request by KrisXV**
This isn't 100% accurate yet but will make implementing Pokemon Home a lot easier when it does come out.

### CODE REVIEW

**Comment by KrisXV** [comment]
It's out and this should be mostly accurate barring some testing

**Comment by KrisXV** [comment]
@Zarel @TheImmortal all the stuff in here is confirmed 100% accurate

**Comment by TheImmortal** [comment]
OU/DOU haven't really announced what's banned but I guess this'll do for now.

**Comment by KrisXV** [comment]
I spoke with Finch with what to tier as what

**Pull request merged**
