### PR TITLE
Update Pokémon colors to match Dec 2023 HOME changes

### PR DESCRIPTION
**Pull request by aQrator**
As per https://bulbapedia.bulbagarden.net/wiki/List_of_Pokémon_by_color#Changes, some colours in game were adjusted last December. Tauros-Paldea and Wooper-Paldea were already fixed it seems, so here are the others

### CODE REVIEW

**Comment by DaWoblefet** [comment]
There's still an [open suggestion](https://www.smogon.com/forums/threads/use-pokemon-homes-color-data-instead-of-game-specific-color-data.3724151/) about whether or not we should use Pokemon Home's colors or Pokemon Scarlet/Violet's colors. I'm in favor of using Home's colors, but there's a few more differences than what you've adjusted here.

**Comment by aQrator** [comment]
Ah. I must have missed that. Apologies, and feel free to delete.

**Comment by DaWoblefet** [comment]
> Ah. I must have missed that. Apologies, and feel free to delete.

No need, this just needs a few tweaks. I posted a follow-up to the thread, including approving using Home data for colors (for now): https://www.smogon.com/forums/threads/use-pokemon-homes-color-data-instead-of-game-specific-color-data.3724151/post-10016447

So in this PR, these are the Pokemon colors that still need adjusted:
Dialga-Origin
Wyrdeer
Sneasler
Overqwil
Brute Bonnet
Ogerpon-Wellspring
Ogerpon-Wellspring-Tera

If you could update these as well in your PR, I can merge it!

**Comment by aQrator** [comment]
Will do

**Comment by DaWoblefet** [comment]
Thanks aQrator!

**Pull request merged**
