### PR TITLE
Eternabeam is one word

### PR DESCRIPTION
**Pull request by PartMan7**
Source: https://bulbapedia.bulbagarden.net/wiki/Eternabeam_(move)

### CODE REVIEW

**Comment by Zarel** [comment]
Are we actually using Bulbapedia as a source? I remember they were one of the worst recently.

**Comment by PartMan7** [comment]
PokemonDB, pokemon.fandom, and Serebii all say the same thing, too.

**Comment by Zarel** [comment]
Yes, I know, I'm just saying you shouldn't cite Bulbapedia.

**Comment by PartMan7** [comment]
Noted.

**Pull request merged**
