### PR TITLE
Dynamax Cannon now targets both foes instead of just one in doubles

### PR DESCRIPTION
**Pull request by CK-Yong**
This fixes https://github.com/smogon/pokemon-showdown/projects/3#card-29789538

### CODE REVIEW

**Comment by Zarel** [comment]
...this does not need a test. The test adds nothing the change doesn't.

**Comment by DaWoblefet** [comment]
Wait a second here, who said Dynamax Cannon was a spread move? This is blatantly false; it's just like any other single target attack.

**Comment by Zarel** [comment]
Good to know.

**Comment by Zarel** [comment]
@TZubiri I'm removing your write access to Mechanics Bugs. You _must_ ask researchers before adding a mechanics bug.

**Comment by CK-Yong** [comment]
Thanks for verifying guys, I didn't test it myself, just assumed that someone tested this in-game and posted the ticket.

**Comment by TZubiri** [comment]
@Zarel, Removing write access is a good idea since I'm no longer active in triaging issues from the smogon thread.

However I must vocalize my recommendation, in case someone chooses to take over triaging, that mechanics bugs be reported as github issues rather than a kanban board item, so that more detail can fit, like in this example: https://github.com/smogon/pokemon-showdown/issues/6089

In the case of a false bug, the source trail can then be audited, to identify the fault and address it systematically. In this case I think it was a misinterpreted third party website.

I wish you all the best in the project.

**Pull request closed without merging**
