### PR TITLE
Let Admins add global FAQs

### PR DESCRIPTION
**Pull request by KrisXV**

### CODE REVIEW

**Comment by mia-pi-git** [comment]
Although I do see merit in this, I'd like to ask two questions.
1 - Does the benefit from this outweigh the benefit in being able to easily translate FAQs? (this is important since they're so commonly used)
2 - Do we change /faqs enough to make this worth it?

**Comment by KrisXV** [comment]
> Although I do see merit in this, I'd like to ask two questions.
> 1 - Does the benefit from this outweigh the benefit in being able to easily translate FAQs (which is important since they're so commonly used)?
> 2 - Do we change /faqs enough to make this worth it?

why not just paste our pm convo, that goes over both of these things

[20:13:49] +Kris: i think the way i handled faqs is prob the best compromise
[20:14:00] @Mia: i would have just put it in roomfaqs
[20:14:07] @Mia: keyed it to a 'global' roomid
[20:14:16] +Kris: true
[20:14:26] +Kris: but there were more oddities about the hardcoded faqs
[20:14:53] @Mia: f
[20:15:07] @Mia: i think my issue is
[20:15:12] @Mia: it makes translations a lot harder
[20:15:20] +Kris: yea
[20:15:35] @Mia: plus as a matter of practice we really dont change them that often
[20:15:53] +Kris: i mean idrc what the end result of the pr is
[20:16:07] +Kris: just sucks that most of help's rfaqs
[20:16:11] +Kris: are being used globally
[20:16:17] +Kris: w/o the formality
[20:16:25] +Kris: of being in !faq
[20:16:59] @Mia: tru
[20:17:02] @Mia: just hardcode imo

**Comment by mia-pi-git** [comment]
> > Although I do see merit in this, I'd like to ask two questions.
> > 1 - Does the benefit from this outweigh the benefit in being able to easily translate FAQs (which is important since they're so commonly used)?
> > 2 - Do we change /faqs enough to make this worth it?
> 
> why not just paste our pm convo, that goes over both of these things
> 
> [20:13:49] +Kris: i think the way i handled faqs is prob the best compromise
> [20:14:00] @mia: i would have just put it in roomfaqs
> [20:14:07] @mia: keyed it to a 'global' roomid
> [20:14:16] +Kris: true
> [20:14:26] +Kris: but there were more oddities about the hardcoded faqs
> [20:14:53] @mia: f
> [20:15:07] @mia: i think my issue is
> [20:15:12] @mia: it makes translations a lot harder
> [20:15:20] +Kris: yea
> [20:15:35] @mia: plus as a matter of practice we really dont change them that often
> [20:15:53] +Kris: i mean idrc what the end result of the pr is
> [20:16:07] +Kris: just sucks that most of help's rfaqs
> [20:16:11] +Kris: are being used globally
> [20:16:17] +Kris: w/o the formality
> [20:16:25] +Kris: of being in !faq
> [20:16:59] @mia: tru
> [20:17:02] @mia: just hardcode imo

I mean, for one, it doesn't really address them both imo.
Two, I wanted to make the questions clear for anyone else to weigh in on if they wanted.

**Comment by KrisXV** [comment]
honestly. forgot this pr was open but it probably wouldve been closed anyway so w/e. im fine with just hardcoding

**Pull request closed without merging**
