### PR TITLE
Fix Stadium Mechanics (Struggle VS Ghost-types)

### PR DESCRIPTION
**Pull request by PlagueVonKarma**
Struggle should affect Ghost-types in Stadium, designed to avoid infinite battles. Thanks to Kris for helping me figure out what to do...

Source: https://www.smogon.com/forums/threads/stadium-format-is-now-available-on-ps.3526616/post-8517229

I'm not necessarily a _programmer_, but if I can help the Stadium sim improve in some way, that's good enough for me.

### CODE REVIEW

**Comment by Zarel** [comment]
Thanks! This looks good.

Can anyone contribute unit tests? If not, I'll add them when I have time.

**Comment by Zarel** [comment]
Specifically: How does Struggle affect Rock-types in RBY vs Stadium?

**Comment by PlagueVonKarma** [comment]
> Specifically: How does Struggle affect Rock-types in RBY vs Stadium 1?

It hits them for "not very effective" damage, as it's Normal-type. It's specifically programmed to ignore Ghost-type immunity, thus the programming here.

**Comment by KrisXV** [comment]
I can do some unit tests in a bit

**Comment by Zarel** [comment]
Thanks! I'll accept this while you write unit tests.

**Pull request merged**
