### PR TITLE
Refactor tournament plugin loading

### PR DESCRIPTION
**Pull request by whalemer**

### CODE REVIEW

**Comment by Zarel** [comment]
I'm confused what this achieves?

**Comment by Zarel** [comment]
It doesn't seem simpler at a glance. Can you clarify what improvement this makes?

**Comment by whalemer** [comment]
Feels less hacky than the current situation to me, makes it a lot easier to load things other than commands (ie, roomsettings) from tours.

**Comment by Zarel** [comment]
Oh, I see. Yeah, this is good.

**Pull request merged**
