### PR TITLE
Chat commands: Make /sendhtmlpage send to the last active connection

### PR DESCRIPTION
**Pull request by mia-pi-git**
Minor QOL thing, but apparently it'd be nice to have this.
See: Felucia in dev talking about it being sent to the first conn, not the current.

### CODE REVIEW

**Comment by Zarel** [comment]
This is a really great improvement, thanks!

Even better would be some way of tracking which connection the request came from, which I think we should also do. I think that's very doable, actually; just include the connection index with the request message.

**Comment by TheMezStrikes** [comment]
If you track which connection the request came from, you'd also need to let the `/sendhtmlpage` command select which connection to send data to, which is likely to end up being unintuitive

**Comment by mia-pi-git** [comment]
It'd be uninutive, sure, but doable. 
just something like `|pm|sender|receiver||requestpage|pageid|connIndex` and then providing an option for /sendhtmlpage shouldn't be that hard. I find that the only issue would be, what would be the proper way to specify an index? Break all bots currently using the command or risk the provided HTML tripping up on it?

**Comment by Zarel** [comment]
I'm not opposed to breaking all bots currently using it, tbh. I'd rather than than use an unwieldy syntax for it.

**Comment by mia-pi-git** [comment]
Okay. I'm still kind of confused why specifying a connection is better than just going for the last active connection, but i suppose that can be discussed in the follow-up PR. I'll write it now.

**Comment by Zarel** [comment]
> why specifying a connection is better than just going for the last active connection

Race conditions, mostly. Imagine I click `view-bot-scrappie-whatever` on my phone right before I click "search" on my computer.

**Comment by mia-pi-git** [comment]
Ah, fair.

**Pull request merged**
