### PR TITLE
Proc hazards in the order they were set

### PR DESCRIPTION
**Pull request by MathyFurret**
https://github.com/smogon/pokemon-showdown/projects/3#card-23557574

Entry hazards now use a new `EntryHazard` event, which is run immediately after `SwitchIn` and uses a stable sort for its resolution. (String keys in objects are guaranteed to remain in insertion order, and `Array#sort` is guaranteed stable.)

### CODE REVIEW

**Comment by Karthik99999** [comment]
The extra condition seems a bit unnecessary to me. Why not just call the `onEntryHazard` event everywhere the `onSwitchIn` event is called?

**Comment by DaWoblefet** [comment]
> Actually this raises an interesting question: does Court Change preserve the order of hazards across sides?
Pretty sure yes re: Court Change, but I'll double check to make sure.

You could probably move Heavy-Duty Boots code to the generic ``entryhazard`` condition.

All the tests relevant to the following pass, but I figure it's relevant to the implementation so I'll post it here anyway: entry hazards are a part of Game Freak's equivalent of onSwitchIn, along with the following effects (this list is as of Gen 7):
<details>
<summary>List of effects in Game Freak's onSwitchIn equivalent</summary>
Slot effects:
Lunar Dance
Healing Wish
Z-Memento / Z-Parting Shot

Side effects:
Stealth Rock
Spikes
Toxic Spikes
Sticky Web

Abilities:
Intimidate
Slow Start
Limber
Insomnia
Magma Armor
Immunity
Water Veil
Drizzle
Drought
Sand Stream
Snow Warning
Primordial Sea
Desolate Land
Delta Stream
Air Lock / Cloud Nine
Trace
Download
Forewarn
Anticipation
Frisk
Mold Breaker
Pressure
Unnerve (note: typically Unnerve will activate in the event before Game Freak's onSwitchIn)
Imposter
Dark Aura
Fairy Aura
Aura Break
Water Bubble
Electric Surge
Psychic Surge
Misty Surge
Grassy Surge
Comatose

Items:
Cheri
Chesto
Rawst
Aspear
Persim
Pecha
Lum
Leppa
Oran
Berry Juice
Sitrus
Figy
Wiki
Mago
Aguav
Iapapa
Liechi
Ganlon
Salac
Petaya
Apicot
Lansat
Starf
Micle
Mental Herb
Amulet Coin
Air Balloon
</details>

Then, the [order of modifier application within a given event](https://www.smogon.com/forums/threads/sword-shield-battle-mechanics-research.3655528/post-8685465) (which is broadly not implemented generally on the sim yet) would cause these effects to activate for each Pokemon in order of their Speed. In this case, it's slot effects > side effects (hazards) > Abilities > items.

So things like this will happen as a result: if Choice Scarf Landorus-T and Tapu Koko simulatenously switch in, with Stealth Rock active, first Stealth Rock damages Landorus-T, then Intimidate activates, then Stealth Rock damages Tapu Koko, then Electric Surge activates. Another simpler example is that Healing Wish activates before hazard damage.

**Comment by MathyFurret** [comment]
actually, if all hazards are grouped between slot effects and abilities, that sounds like a reason we _should_ do what karthik said

**Comment by DaWoblefet** [comment]
> Actually this raises an interesting question: does Court Change preserve the order of hazards across sides?

Confirming it does preserve the order as suspected.

**Comment by MathyFurret** [comment]
> You could probably move Heavy-Duty Boots code
does this mean Poison type with HDB doesn't remove tspikes? because as it was coded before, they would

**Comment by DaWoblefet** [comment]
> does this mean Poison type with HDB doesn't remove tspikes? because as it was coded before, they would

Nope they do; I forgot about that, so it is best to leave the HDB implementation alone.

**Comment by DaWoblefet** [comment]
Thanks a bunch Mathy!

**Pull request merged**
