### PR TITLE
Create flag for abilities not affected by Gastro Acid

### PR DESCRIPTION
**Pull request by urkerab**
And use it everywhere to simplify checks for illegal copying, overwriting or swapping of Abilities.

### CODE REVIEW

**Comment by Marty-D** [comment]
I don't know if Flower Gift is on this list now, but it wasn't in any other gen and neither was Forecast. Zen Mode only got on this list in Gen 7.

I disagree with removing detail in the descriptions.

**Comment by urkerab** [comment]
Sorry, despite knowing that Zen Mode got added to the list in Gen 7, I got the list mixed up with the list of Abilities that can't be copied (but can be suppressed or replaced) except for some reason by Skill Swap.

Zen Mode not being in the list in Gen 6 means that Simple Beam, Skill Swap and Worry Seed now automatically special-case it, avoiding the need for an override.

I've reverted all of the descriptions.

**Comment by Zarel** [comment]
I think I like this, although I'm not sold on `permanent` as a flag name. `isUnchangeable`?

**Comment by urkerab** [comment]
> I'm not sold on permanent as a flag name

https://github.com/smogon/pokemon-showdown/commit/d8bea75618b1382305b7f8071c204fba3ebb054c#commitcomment-36425902

**Zarel** replied on 14 Dec 2019

> I like that name. Let's do it.

**Comment by Zarel** [comment]
I didn't imagine it would just be a property. As a property, I think `isPermanent` makes more sense.

**Comment by Zarel** [comment]
Superseded by #7614

**Pull request closed without merging**
