### PR TITLE
Bug fix/heal block independent fail

### PR DESCRIPTION
**Pull request by aviettran**

### CODE REVIEW

**Comment by aviettran** [comment]
Haven't tested this in client, since Heal Block isn't valid in any of the formats. What's a good way to test?

**Comment by DaWoblefet** [comment]
Hop on localhost and battle in something like Gen 7 Custom Double Battle.

**Comment by aviettran** [comment]
Looks like Gen 7 Doubles OU works, thanks. Not sure quite sure what the proper method of displaying custom text for a move failure is. If someone can give me a quick primer it'd save me some time.

**Comment by DaWoblefet** [comment]
I would also like to know this fwiw.

**Comment by aviettran** [comment]
I figured it out. An educational experience. The client has the sim as a dependency, so I pulled the client repo and did a full build with the changes from this PR. I was then able to do a full test. Moving this PR out of draft.

image

**Review by Marty-D — APPROVED** [review]
Nicely done once again, thanks! If there's a card associated with this I'll go move it over now.

**Pull request merged**
