### PR TITLE
Gen 3/4: Remove HAs in `getSpecies` instead of scripts files

### PR DESCRIPTION
**Pull request by KrisXV**

### CODE REVIEW

**Comment by Zarel** [comment]
Why?

I think the current approach has some nicenesses, such as that iterating `Dex.mod('gen4').data.Pokedex` is more accurate.

**Comment by KrisXV** [comment]
You’re mutating immutable data as it currently stands l; if you want niceness in iterating values of Dex.mod('gen4').data.Pokedex then hardcode the changes in mods/gen4/pokedex.ts imo

**Comment by Zarel** [comment]
Honestly that's fair, it should be safe here but we probably can't rely on that.

**Comment by Zarel** [comment]
By which I mean, it _is_ a bit easy to accidentally do something unsafe.

**Comment by Rezzo64** [comment]
This commit is currently causing an error on building the client: 

```
Building `data/teambuilder-tables.js`... /home/sean/Documents/Projects/pokemon-showdown-client/caches/pokemon-showdown/dist/data/mods/gen4/scripts.js:29
      delete this.modData("Pokedex", i).abilities["H"];
                                       ^

TypeError: Cannot delete property 'H' of #<Object>
```

**Pull request merged**
