### PR TITLE
Fix bug with Hidden Power desc for past gens

### PR DESCRIPTION
**Pull request by Spandamn**

### CODE REVIEW

**Comment by TheImmortal** [comment]
I think @Zarel would say use `move.realMove` instead of hardcoding

**Comment by Spandamn** [comment]
it wasnt much of a difference really

**Comment by Spandamn** [comment]
well merge it i guess

**Comment by DaWoblefet** [comment]
@Spandamn I just tried your fix locally and it doesn't work:

image

**Comment by Spandamn** [comment]
Hmmm, looks like a client-server bug

**Pull request closed without merging**
