### PR TITLE
Enable incremental compilation in `tsc`

### PR DESCRIPTION
**Pull request by AnnikaCodes**
This makes `npm test` faster.

### CODE REVIEW

**Comment by Zarel** [comment]
Neat, thanks!

**Comment by urkerab** [comment]
How do you forcibly rebuild? I had an error in `data/abilities.ts` caused by a typo in `sim/dex-conditions.ts` and the only way I could proceed was to undo this change locally.

**Comment by urkerab** [comment]
... although I made the same mistake again and this time `tsc` noticed my change, so whatever...

**Comment by mia-pi-git** [comment]
> How do you forcibly rebuild? I had an error in `data/abilities.ts` caused by a typo in `sim/dex-conditions.ts` and the only way I could proceed was to undo this change locally.

``node build --force``.

**Comment by urkerab** [comment]
... it was the `tsc` that was failing, does `node build` even affect that?

**Comment by mia-pi-git** [comment]
Oh, i was only reading the "forcibly rebuild" part, sorry.

**Comment by AnnikaCodes** [comment]
You can probably just remove `*.tsbuildinfo`.

**Comment by Zarel** [comment]
We should probably make it so `build --force` deletes `*.tsbuildinfo`?

**Comment by AnnikaCodes** [comment]
That doesn't make much sense to me, since `node build` doesn't use `tsc`. Maybe `npm run clean` or something?

**Comment by Zarel** [comment]
I think that makes sense to me.

**Pull request merged**
