### PR TITLE
Added emotes like how you can do in discord

### PR DESCRIPTION
**Pull request by harbar20**
Like I can do `:smile:` instead of copy-pasting the smile unicode thing. 

I literally copy-pasted this directly from [here](https://github.com/Jackinev/Bully-Showdown-Server) so it's 99% likely there are lots of issues. Also, in emoticons.json, there's lots of unnecessary emotes, so they can be removed at request. Also if formatting's an issue that can be fixed too. Basically anything lol, idek if it'll work as is.

Hopefully it does.

### CODE REVIEW

**Comment by mia-pi-git** [comment]
I believe we've discussed this before. 
The consensus seems to be most people don't want this, as PS's simplicity is appreciated.
Additionally, this is a very clunky way of doing it, and provides absolutely no way for rooms to disable it. As such, it would be spammed and abused almost instantly.

**Comment by AeonicX7** [comment]
> Also quick talk with Aeonic, seems to be a similar no from policy?

Yeah. Not a fan of this idea for a variety of reasons, most of which were covered pretty well in that thread.

**Comment by harbar20** [comment]
Ah. The reasons in that thread make complete sense. Should I close the PR?

**Comment by mia-pi-git** [comment]
Seems like that's the consensus.

**Comment by AnnikaCodes** [comment]
For future reference, all new code accepted to this repository should be written in TypeScript.

**Comment by harbar20** [comment]
3456ertydfghxcvb

**Pull request closed without merging**
