### PR TITLE
Fix Octolock not activating certain abilities

### PR DESCRIPTION
**Pull request by ZardMX**
Fixes Octolock not activating Defiant, Simple, Mirror Armor, Contrary, Competitive, Clear Body, Big Pecks
Defiant: https://vimeo.com/375255848
Big Pecks: https://vimeo.com/375262242
Will update when I get sources for others.

### CODE REVIEW

**Comment by Zarel** [comment]
The "files changed" is currently a mess; can this be rebased on top of master?

**Comment by Zarel** [comment]
Can you give an example boosting message?

**Comment by Zarel** [comment]
Also this is a one-line change, this should probably be squashed into a single commit.

**Comment by ZardMX** [comment]
> Can you give an example boosting message?

The opposing Bisharp's Defense fell!
[The opposing Bisharp's Defiant]
The opposing Bisharp's Attack rose sharply!
The opposing Bisharp's Special Defense fell!
[The opposing Bisharp's Defiant]
The opposing Bisharp's Attack rose sharply!

**Comment by Zarel** [comment]
I mean a protocol message.

**Comment by Zarel** [comment]
Like, `|-boost|` etc

**Comment by ZardMX** [comment]
`'|poke|p1|Bisharp, M|',
  '|poke|p2|Grapploct, M|',
  '|teampreview',
  '|',
  '|start',
  '|split|p1',
  '|switch|p1a: Bisharp|Bisharp, M|271/271',
  '|switch|p1a: Bisharp|Bisharp, M|100/100',
  '|split|p2',
  '|switch|p2a: Grapploct|Grapploct, M|301/301',
  '|switch|p2a: Grapploct|Grapploct, M|100/100',
  '|turn|1',
  '|',
  '|move|p1a: Bisharp|Sleep Talk||[still]',
  '|-fail|p1a: Bisharp',
  '|move|p2a: Grapploct|Octolock|p1a: Bisharp',
  '|-activate|p1a: Bisharp|move: Octolock|[of] p2a: Grapploct',
  '|',
  '|-unboost|p1a: Bisharp|def|1',
  '|-ability|p1a: Bisharp|Defiant',
  '|-boost|p1a: Bisharp|atk|2',
  '|-unboost|p1a: Bisharp|spd|1',
  '|-ability|p1a: Bisharp|Defiant',
  '|-boost|p1a: Bisharp|atk|2',`

**Pull request merged**
