### PR TITLE
Make HP Percentage Mod an inherent part of Gen7, not a mod

### PR DESCRIPTION
**Pull request by xfix**
This will affect VGC format, I consider that to be a feature.

### CODE REVIEW

**Comment by Zarel** [comment]
VGC players do not consider that a feature. Why would you do this?

**Comment by Marty-D** [comment]
In SM the HP bars are 100 pixels wide, but I just checked USUM and as part of the UI redesign they were changed to 86 pixels. So, that sucks.

**Comment by xfix** [comment]
Okay, what? Why would they change HP bar to be 86 pixels in Ultra Sun and Ultra Moon? I thought they wouldn't do something that crazy.

Hm, I guess instead HP Percentage Mod will need to stay here, but instead of having 48 pixels HP bar, it would be 86 pixels HP bar for Gen7 formats???

**Comment by Zarel** [comment]
;_;

**Comment by Zarel** [comment]
We'll have to make client changes, I guess.

**Comment by Zarel** [comment]
So, we need some way of sending "exact HP" vs "approximate HP".

Currently, the client is very hacky; it interprets `/48` and `/100` as "approximate", and everything else as "exact". We should probably change that. Something like `/48p`?

**Comment by scheibo** [comment]
> So, we need some way of sending "exact HP" vs "approximate HP".
> 
> Currently, the client is very hacky; it interprets `/48` and `/100` as "approximate", and everything else as "exact". We should probably change that. Something like `/48p`?

Yeah, this is pretty hacky. Doesn't it break in obscure cases where the Pokemon's max HP is actually exactly 100 or 48 (though very unlikely since most games are at Lvl 5/50/70+/100).

`~` is a pretty universal sign for approximate (ie/ `~76/100` or `~36/48`), and `px` is how pixels are shortened in CSS (`36/48px`), though if we went with `px` I'd want to see `76/100%` for the HP Percentage Mod because we're not talking about pixels there. I guess your `p` suggestion is useful for both `p`ercent or `p`ixel, but given that its not much work to differentiate them it seems like being explicit would be desirable?

My preference would be:

- `X/100%` for the HP Percentage Mod
- `X/48px` or `X/86px` for non modded

Though a `~` prefix or a `p` suffix would be fine as well. I'm happy to take on the client + server changes if we can agree on what the affix should be.

**Comment by Zarel** [comment]
I actually did settle on `number-color` meaning HP pixels. Currently we only send HP color if it's ambiguous; if we instead sent them all the time, that would be clear. I just haven't gotten around to _implementing_ that yet.

**Comment by scheibo** [comment]
>  if we instead sent them all the time, that would be clear. 

I don't know that I'd go so far as to call it _clear_. I don't think you could be even more clear than an explicit `%` and `px` like I proposed. Always sending `'g'|'y'|'r'` can be used to denote pixels, but the client is still required to assume 'if the HP denominator is 100 then assume %' unless it wants to start parsing clauses. I understand that even with `px` you would need to to end the color along on occasion like we do today, and that `%` and `px` is more verbose on the wire protocol, but I don't really know why we wouldn't want to error on the side of just being overly explicit here.

Whatever the protocol, this doesn't seem super difficult to implement, and I'm quite surprised VGC players aren't complaining about this more given it seems like they'd want as much information as possible here.

**Comment by Zarel** [comment]
> I don't know that I'd go so far as to call it _clear_. I don't think you could be even more clear than an explicit `%` and `px` like I proposed. Always sending `'g'|'y'|'r'` can be used to denote pixels, but the client is still required to assume 'if the HP denominator is 100 then assume %' unless it wants to start parsing clauses. I understand that even with `px` you would need to to end the color along on occasion like we do today, and that `%` and `px` is more verbose on the wire protocol, but I don't really know why we wouldn't want to error on the side of just being overly explicit here.

We can send `g, y, r` for percentages, too. Percentages are just 100 pixels.

> Whatever the protocol, this doesn't seem super difficult to implement, and I'm quite surprised VGC players aren't complaining about this more given it seems like they'd want as much information as possible here.

VGC players don't exactly count literal pixels while playing the actual game. In practice, the point has always been to eyeball it, which hardcore mode reinforces.

**Comment by scheibo** [comment]
> We can send `g, y, r` for percentages, too. Percentages are just 100 pixels.

Doh. I guess you're right.

I guess I'm OK with this, and it helps sell the simplicity. I really like the explicitness of `%` and `px`, but having to send along color on occasion (`42/48px` + `9/48px y` or something) and the fact that both `%` and `px` could instead be treated using the same mechanism (`g, y, r`) is swaying me.

**Comment by Zarel** [comment]
So, to be clear, the plan is:

`120/240` = exact HP

`50/100y` = percents

`24/48y` = pixels

**Comment by Zarel** [comment]
It should be mostly backwards-compatible. Old replays would behave a bit weirdly, but not horribly.

**Comment by Zarel** [comment]
I'm not very against `50%y` as a shorthand for `50/100y`, but it seems like it would complicate the parsing code for a pretty minor gain.

**Comment by scheibo** [comment]
No, I was going to have it be `50/100%` and `12/48px`, as its very intuitive when reading the text protocol, but I agree, I don't think the complications to the parsing code (though slight) justify it, especially when you can unify both with `g` as well as handle the weird `px` edge cases around color.

**Comment by TheImmortal** [comment]
This was done.

**Comment by TheImmortal** [comment]
By this is mean what's in the title. Feel free to open an issue regarding what was discussed.

**Pull request closed without merging**
