### PR TITLE
Update Emergency Exit test

### PR DESCRIPTION
**Pull request by TheImmortal**

### CODE REVIEW

**Comment by TheImmortal** [comment]
@Zarel this should pass.

**Comment by Zarel** [comment]
I haven't forgotten...

**Comment by Zarel** [comment]
#6351 will also massively change Emergency Exit, so I guess this means I'll do both at once.

**Comment by Zarel** [comment]
Also, should both tests exist? Why did you replace it instead of adding a separate test?

**Comment by TheImmortal** [comment]
No particular reason. I can re-add it.

**Comment by TheImmortal** [comment]
But also, presumably you’d just copy this test locally and push it yourself when you fix it. Either works.

**Comment by Zarel** [comment]
Yeah, that's what I'm going to do.

**Pull request closed without merging**
