### PR TITLE
Custom Game: Allow more than 255 EVs in a single stat

### PR DESCRIPTION
**Pull request by Vaucin**

### CODE REVIEW

**Comment by KrisXV** [comment]
...why?

**Comment by HoeenCoder** [comment]
Hi, welcome to the PS server github repo. I assume your the user who posted this idea in the help room earlier this morning (allowing more EV's on pokemon in custom games). It appears you haven't read our contributing guide yet, I suggest you take a look: [CONTRIBUTING.md](https://github.com/Zarel/Pokemon-Showdown/blob/master/CONTRIBUTING.md)

As for your PR, a few things should be checked prior to merging this.
- Does the validator catch this in normal formats? We don't want people running around in OU or something with 510 EVs in a single stat. I'm pretty sure it does but it should be checked.
- Does this cause any unintended side affects / can PS handle an EV count higher than 225 in a stat?
- Should we do this at all? I'm not opposed for a custom game honestly, but idk what Zarel or anyone else thinks.

**Comment by Zarel** [comment]
I guess I don't necessarily have objections...

**Comment by SadisticMystic** [comment]
If you're going to allow this, why not allow negative EVs in custom as well?

**Comment by Zarel** [comment]
That's also possibly a good idea.

**Comment by DaWoblefet** [comment]
This PR has gone unmaintained by its author, and I can't think of a real reason custom game needs this anyway.

**Pull request closed without merging**
