### PR TITLE
Natdex: Power Construct is banned

### PR DESCRIPTION
**Pull request by asgdf**
As per https://www.smogon.com/forums/threads/national-dex-ou-metagame-discussion.3656899/.

### CODE REVIEW

**Comment by asgdf** [comment]
Ok maybe Moody is not supposed to be baned, the OP just still says it is because it wasn't updated? Don't merge quite yet I guess.

**Comment by Zarel** [comment]
You should be banning Zygarde-C, not Power Construct.

**Comment by asgdf** [comment]
Gen 7 OU, Gen 7 DOU and Metronome Battles all ban Power Construct, while no format bans Zygarde-C, so I went with consistency.

**Comment by Zarel** [comment]
:[ Fine, I guess.

Also I thought Zygarde was banned in Gen 7 OU? The Power Construct ban seems unnecessary.

**Comment by Marty-D** [comment]
Zygarde 10% also exists.

**Comment by asgdf** [comment]
Okay, so they didn't want Moody banned after all, and updated the OP accordingly, so I removed that ban again.
I did this through the online interface so I can't amend the commit easily, but that can be quashed when merging right?

**Comment by Zarel** [comment]
This conflicts with the Dyna+Mega+Z fix I think.

**Comment by asgdf** [comment]
Not anymore.

**Pull request merged**
