### PR TITLE
Update G-Max Gravitas' shortDesc

### PR DESCRIPTION
**Pull request by DeltaCoderr**

### CODE REVIEW

**Comment by KrisXV** [comment]
I don't think this is necessary

**Comment by Zarel** [comment]
Does this message even fit?

**Comment by Zarel** [comment]
No, but this fits:

image

I don't know if we care about this, though.

**Comment by KrisXV** [comment]
If we wanted to be sticklers about it, we would also need to update Max Flare's description on top of all other moves that call terrains/weathers/field effects

**Comment by DeltaCoderr** [comment]
So  do you want me to change it to `Summons Gravity (5 turns)`?

**Comment by Zarel** [comment]
It depends on what we agree on. @Marty-D, opinions?

**Comment by Marty-D** [comment]
I also don't think this is necessary. You're supposed to read it as "this starts the effect of Gravity, the move, which lasts 5 turns", just like effects referencing Rain Dance are implied to last 5 turns or 8 turns if the effect starter was holding Damp Rock, because that's how Rain Dance the move works. There's no space in short descriptions to be wordy like this.

**Pull request closed without merging**
