### PR TITLE
/botmsg: Permit ROs

### PR DESCRIPTION
**Pull request by PartMan7**
Bots face some rather inconvenient issues in subroomgroupchats.

### CODE REVIEW

**Comment by Zarel** [comment]
Sure, we can revert if this causes a problem.

**Comment by Zarel** [comment]
But why would they? Couldn't they inherit Bot status from the parent room?

**Comment by TheMezStrikes** [comment]
Something similar has been an issue in the past with a few commands, and precedent seems to be adding ROs to the pool of valid groups instead of reading the parent room rank.
The big issue is that in a few of the On-Site Games rooms (and also in Scrappie somewhere), bots make subroomgroupchats for games and thusly end up as Room Owner and permission errors arise.

**Comment by Zarel** [comment]
Oh, I see!

It really does sound like we need a lot of "Bot" exceptions to make permissions work right.

**Comment by TheMezStrikes** [comment]
The most elegant solution would probably be to read permissions in both sub- and parent room and return success if either of them contains the permission you're looking for. (That doesn't solve this specific PR as it's not a permission issue but a hardcoded rank check, but it'd solve a lot of the other issues)

**Pull request merged**
