### PR TITLE
Chat: Implement /requestcode

### PR DESCRIPTION
**Pull request by singiamtel**
Approved here: https://www.smogon.com/forums/threads/add-requestcode.3709337/

I mostly tried to copy how /requestshow is implemented. 
It's my first time dealing with chat commands, would appreciate any feedback/suggestion.

### CODE REVIEW

**Comment by mia-pi-git** [comment]
Personally, I still fail to see why this is necessary when someone can just post a link to a code-sharing website (pastebin, pastie, etc). It doesn’t seem like anyone actually addressed that in the thread, and this is a niche enough request it feels important to consider.

**Comment by singiamtel** [comment]
The same could be said about /requestshow and Imgur. It's more convenient to be able to do it directly from the room, and doesn't require staff to click random links to different pastebin clones.

**Comment by PartMan7** [comment]
Agreed with the cute weeb here, linking to a paste is far less likely to be read than a !code, and it's significantly more effort than a requestcode.

**Comment by mia-pi-git** [comment]
> The same could be said about /requestshow and Imgur

Those are commonly used, though. This seems to only be desired by a single room.

**Comment by HuntressRubyRose** [comment]
Tier rooms voices and above frequently use code to share teams without leaving the site.

**Comment by singiamtel** [comment]
How should we proceed here? I thought this was approved already, but if you're not convinced that it's needed, should we go back to discussing it in the Smogon thread?

**Comment by AnnikaCodes** [comment]
Like I said on Smogon, I'm not sure why showing code needs to be blocked from regular users in the first place (is the spam really so much worse than just normal chat? it's not like images where you can post shock content). If some rooms want to keep it blocked, would it make sense to make it a roomsetting that Tech & Code can toggle to let regular users post code blocks?

**Comment by mia-pi-git** [comment]
> Like I said on Smogon, I'm not sure why showing code needs to be blocked from regular users in the first place (is the spam really so much worse than just normal chat? it's not like images where you can post shock content). If some rooms want to keep it blocked, would it make sense to make it a roomsetting that Tech & Code can toggle to let regular users post code blocks?

Said as much in #staff but might as well repost: against this for feature bloat reasons, which a roomsetting would only aggravate. Plus, /code is restricted for a reason. If people want to post long blocks of text, making them go through an external host seems more prudent (easier to remove from the screen that way).

**Comment by AnnikaCodes** [comment]
Upper Staff have discussed this and the general consensus is that a roomsettings toggle to let anyone use `!code` that defaults to not letting them use it is fine.

**Comment by mia-pi-git** [comment]
> Upper Staff have discussed this and the general consensus is that a roomsettings toggle to let anyone use `!code` that defaults to not letting them use it is fine.

It may be prudent to, instead, have /permissions support allowing a given rank to broadcast specific commands. This is something people have asked about before, and it would be more general-use than a toggle for one command.

**Comment by AnnikaCodes** [comment]
> > Upper Staff have discussed this and the general consensus is that a roomsettings toggle to let anyone use `!code` that defaults to not letting them use it is fine.
> 
> It may be prudent to, instead, have /permissions support allowing a given rank to broadcast specific commands. This is something people have asked about before, and it would be more general-use than a toggle for one command.

Currently, we check if the user of a command has 'jurisdiction' over unranked users when testing permissions to broadcast (or use other commands without a target). Since you don't generally have jurisdiction over people of the same rank, I propose that we add an exception so that if `/permissions` has allowed a command to be used by unranked users, this jurisdiction check is skipped. Would this cause any problems I'm not seeing?

**Comment by AnnikaCodes** [comment]
Sorry @singiamtel; unfortunately US wanted a different solution to this.

**Comment by singiamtel** [comment]
Understood, thanks for the follow-up

**Pull request closed without merging**
