### PR TITLE
Fix Metronome (Item) and two-turn moves interaction

### PR DESCRIPTION
**Pull request by jmclemo6**
Should fix https://github.com/smogon/pokemon-showdown/projects/3#card-61614782

Also adds a test for the case of a two-turn move that bypasses its charge turn and fixes the original broken test that was here.

### CODE REVIEW

**Comment by jmclemo6** [comment]
I think this should be good to just squash merge. If I need to rebase it to make that clean, let me know.

**Review by Zarel — APPROVED** [review]
Looks fine to me.

**Review by Marty-D — APPROVED** [review]
This is good for now; eventually we just have to pull all this consecutive move functionality out of Metronome, apply the counter to every Pokemon regardless of item, and use it for Metronome, Fury Cutter, and Destiny Bond.

Thanks! 👍

**Comment by jmclemo6** [comment]
> This is good for now; eventually we just have to pull all this consecutive move functionality out of Metronome, apply a counter to every Pokemon regardless of item, and use it for Metronome, Fury Cutter, and Destiny Bond.
> 
> Thanks! 👍 

Replying to this a bit late, but I have a feeling this will partially help with another Metronome bug as well (https://github.com/smogon/pokemon-showdown/projects/3#card-61614791). I can't guarantee anything due to my current schedule, but if I'll try to work on adding the counter to Pokémon directly. If anyone else wants to pick it up, just let me know here, on PS, or via the development Discord server and I can update you on what work (if any) I've been able to do.

**Pull request merged**
