### PR TITLE
Gen 5: Refactor to use unreleasedHidden

### PR DESCRIPTION
**Pull request by xInstruct**
> [01:44] #Zarel: it should definitely set unreleasedHidden to true
[01:44] #Zarel: rather than literally nuking the HA

Welp, here I go on doing this. Will be a bit busy in a bit so just want this off the ground.

### CODE REVIEW

**Comment by KrisXV** [comment]
Theres a shitton more pokemon this applies to btw

also:

[01:14:21] #Zarel: uhhhhhhh
[01:15:00] #Zarel: !learn gen5, chandelure, ha, flamethrower
In Gen 5, HA Chandelure can't learn Flamethrower because:
Chandelure's move Flamethrower can only be learned in gens without Hidden Abilities.
[01:15:06] #Zarel: incorrect error message but it works
[01:15:22] #Zarel: confused why it doesn't just do unreleasedHidden though
[01:16:32] #Zarel: ok it looks like I just never pulled this hotpatch
[01:20:26] #Zarel: Bingus, I'm not entirely sure if the system needs to be changed

**Comment by xInstruct** [comment]
yea..

**Comment by Zarel** [comment]
This doesn't make much sense unless you want to also override with the never-released hidden abilities coded into Gen 5. Which we might want to do (for the Gen 5 DW format!) but I wouldn't do this without also doing that.

**Comment by xInstruct** [comment]
> This doesn't make much sense unless you want to also override with the never-released hidden abilities coded into Gen 5. Which we might want to do (for the Gen 5 DW format!) but I wouldn't do this without also doing that.

That is the plan! Hope anyone reading this enjoys STAG chandelure

**Comment by xInstruct** [comment]
Alright, DW abilities should be implemented properly, alongside a few mons who have unreleased abilities outside of gen 5. 

Anubis did PM me about incorrect shiny validation with some hidden abilities, but that will be another fish to fry later.

heatran sucks btw

**Comment by Zarel** [comment]
Can you clarify the incorrect shiny validation issue?

**Comment by xInstruct** [comment]
> Can you clarify the incorrect shiny validation issue? Is it a regression?


02:30:07] Centiskorch: btw did you also see the list of male/genderless-only gen 5 HAs
[02:30:24] Instruct: Yea
[02:30:46] Centiskorch: I said this to Marty in private but PS doesn't enforce the shiny lock on those mons either.
[02:33:29] Instruct: Alright, ill see if i can apply that as well
[02:33:31] Instruct: thanks
[02:34:03] Centiskorch: You can probably talk to him about it. He said something about an easier way would be to find what TI did before.

**Comment by Zarel** [comment]
Sounds like it's not a regression. OK, thanks!

**Pull request merged**
