### PR TITLE
Fix Me First's interaction with recharge moves

### PR DESCRIPTION
**Pull request by pacmanboss256**
for some reason a test in room-battle.js times out and I have zero clue why

It fails even with the one line i added commented out

### CODE REVIEW

**Comment by pacmanboss256** [comment]
edit: i have zero clue what happened here but it seems to pass everything now

**Comment by DaWoblefet** [comment]
I think this is fine.

**Comment by Zarel** [comment]
Thanks!

**Comment by Zarel** [comment]
@DaWoblefet Perhaps `willMove` should simply not return recharge turns? Would that break any other interaction?

**Pull request merged**
