### PR TITLE
Punishments: Don't warn / mark staff users in banned groupchats

### PR DESCRIPTION
**Pull request by mia-pi-git**
Found out this was a thing when i groupchatbanned someone in the target GC.

### CODE REVIEW

**Comment by Zarel** [comment]
The change to `getSubRooms` seems to make this not hotpatchable?

**Comment by mia-pi-git** [comment]
> The change to `getSubRooms` seems to make this not hotpatchable?

That was a botched merge, I believe. One sec.

**Comment by mia-pi-git** [comment]
> > The change to `getSubRooms` seems to make this not hotpatchable?
> 
> That was a botched merge, I believe. One sec.

Yeah, now we can /hotpatch punishments and /hotpatch roomsp.

**Comment by mia-pi-git** [comment]
But, this is probably pointless now. GCBans are deprecated.

**Comment by Zarel** [comment]
Unfortunate. :(

**Pull request merged**
