### PR TITLE
Ubers UU Tier Shifts

### PR DESCRIPTION
**Pull request by Imperial241**
implemented the shifts from the 3months

### CODE REVIEW

**Comment by KrisXV** [comment]
Already did this, thank you though

**Comment by Imperial241** [comment]
According to https://github.com/smogon/pokemon-showdown/commit/6856545eb188db8d3e83e66c227f94cde4432fb4
you did natdex uubers and lc uu, but not ubers uu, and the builder seems to accurately reflect this?
excuse me if im mistaken though, just slightly confused.

**Comment by KrisXV** [comment]
can you fix natdex uubers please?

**Comment by Imperial241** [comment]
did (i think)

**Pull request merged**
