### PR TITLE
(Not yet approved) Add /scav removehint and /scav edithint

### PR DESCRIPTION
**Pull request by PartMan7**
Requested by A Phantom, waiting on Room Owner approval
Requesting a review from sparkychild

Edit: Apparently, I can't directly request one from them, but I've asked them to take a look at it.

### CODE REVIEW

**Comment by xfix** [comment]
I'm not sure, what is the use-case for removing hints?

**Comment by PartMan7** [comment]
Mostly for when a hint gets added to the wrong question. It's not particularly common, but not particularly rare, either.

**Comment by xfix** [comment]
Fair then. I would like this to be approved by a room owner, but it seems fine for me.

**Comment by xfix** [comment]
Oops, I accidentally pressed enter while modifying the title to include `Scavengers:`, oh well.

**Pull request merged**
