### PR TITLE
Alias /srgc to /subroomgroupchat

### PR DESCRIPTION
**Pull request by sirKiraUzumaki**
Adding a simple alias "srgc" for commands /subroomgroupchat.

### CODE REVIEW

**Comment by Zarel** [comment]
I'm OK with this if there's enough interest. Was there a Suggestions thread somewhere?

**Comment by sirKiraUzumaki** [comment]
> I'm OK with this if there's enough interest. Was there a Suggestions thread somewhere?

No there wasn't a suggestion thread.

**Comment by sirKiraUzumaki** [comment]
I have also dropped a message in discord but lemme also clear this here. As /subroomgroupchat command to lengthy to typed. Sometimes typos can be faced and then you need to type in again (especially this sucks when you are typing on mobile).

**Comment by Zarel** [comment]
Hm. It matches other groupchat commands and at four characters long it's unlikely to conflict, so I think if you find it useful, that's good enough for me. Thanks!

**Pull request merged**
