### PR TITLE
Moderation: Support private reasons in /warn

### PR DESCRIPTION
**Pull request by AnnikaCodes**

### CODE REVIEW

**Comment by Zarel** [comment]
I'm not sure `[proof]` is the right term; I would go with `[private]`.

Also, is there any reason to use "spoiler"? Is that already used by other commands?

**Comment by mia-pi-git** [comment]
> I'm not sure `[proof]` is the right term; I would go with `[private]`.
> 
> Also, is there any reason to use "spoiler"? Is that already used by other commands?

Spoiler is used by other commands with this functionality, yes.

**Comment by Zarel** [comment]
On reflection, I would call it `[staff-only reason]` or `[private reason]`. I think that's just much clearer about its purpose.

**Comment by AnnikaCodes** [comment]
Rebased this! @Zarel, ETA on merging this?

**Comment by Zarel** [comment]
I don't remember why I didn't merge earlier, but I think it might have been the conflict? I certainly don't have anything else waiting on this.

**Pull request merged**
