### PR TITLE
Fix endless battle clause

### PR DESCRIPTION
**Pull request by pacmanboss256**

### CODE REVIEW

**Comment by pacmanboss256** [comment]
@AnnikaCodes this passed on my end

**Comment by AnnikaCodes** [comment]
You'll need to revert the other PR's changes to the test. It passes locally because you haven't rebased against upstream yet.

**Comment by Zarel** [comment]
Hm, this will say "in 2 turns, in 1 turn, in 0 turns, ended" over the course of the last four turns, which is probably undesirable.

Ideally the countdown should go something like:

- in 2 turns
- this turn
- ended

Or perhaps it _would_ be clearer if we ended at the beginning of turn 1000 rather than the end. Plausibly we should poll people for their intuitions first.

**Comment by pacmanboss256** [comment]
I can draft this for now

**Comment by AnnikaCodes** [comment]
@pacmanboss256 are you still working on this?

**Comment by pacmanboss256** [comment]
I think we left this as a policy decision, there really anything to change besides when it activates.

**Comment by AnnikaCodes** [comment]
I'll close this, then.

**Pull request closed without merging**
