### PR TITLE
Github Actions: Perform selective eslint & testing for PRs

### PR DESCRIPTION
**Pull request by im-tofa**
A few potential optimizations to the Github Actions job that could be worth trying out, if desired

1. Use [actions/cache@v3](https://github.com/actions/cache) to create a Github-hosted, immutable cache entry that stores a specified directory (in this case, `node_modules`). A new entry is created whenever `package-lock.json` is updated or a new `node-version` is specified in the action itself. Old entries are auto-evicted from the cache after a few days of inactivity or due to lack of space. Similar to what is done [here](https://github.com/prettier/eslint-config-prettier/blob/main/.github/workflows/check.yml), saves about a minute in the `npm install` step once cached
2. Use [tj-actions/changed-files@v35](https://github.com/tj-actions/changed-files) to fetch all changed/modified js, ts & tsx files in a PR, and use eslint only on those. If there's a push to master (force push or PR merge), a full lint is run instead. Saves 1-2 minutes for smaller PRs

The remaining large chunk of time is in `tsc` + `mocha` (~6-8m), mainly `mocha`. The runners on Github Actions also seem to vary quite a lot in performance in general between runs, but idk how much we can do about that

Examples:
1. [push-to-master](https://github.com/im-tofa/pokemon-showdown/actions/runs/4638042638/jobs/8207490831)
2. [pull request](https://github.com/im-tofa/pokemon-showdown/actions/runs/4638087164/jobs/8207571092?pr=2)

NOTE: I bumped the node version in Github Actions to `16.x` since I couldn't figure out why `14.x` won't pass `tsc` (happened in `master` as well). I'll change it back to `14.x` after someone who knows more is able to fix it in master

### CODE REVIEW

**Comment by Zarel** [comment]
While I don't have a _problem_ with this, I don't think either of these will have much impact on build times, the vast majority of which are spent in Mocha.

Plausibly the most impactful thing we can do is only run sim tests when the sim is changed, which would have a pretty huge impact.

**Comment by im-tofa** [comment]
Thanks for the feedback :)

> Plausibly the most impactful thing we can do is only run sim tests when the sim is changed, which would have a pretty huge impact.

Good point! I could take a look at adding that when I'm able to, should be possible to deduce with the `changed-files`-action. Would it be enough to say "if the `sim` or `data` directories are unchanged, there is no need to run `sim` tests"? I could add this for only PRs or for both PRs & merges/push-to-master

**Comment by Zarel** [comment]
> Would it be enough to say "if the `sim` or `data` directories are unchanged, there is no need to run `sim` tests"? I could add this for only PRs or for both PRs & merges/push-to-master

Yes, `sim` and `random-battles`.

**Comment by Zarel** [comment]
Although `config/formats` does also mean needing to re-run tests.

**Comment by im-tofa** [comment]
@Zarel I added your suggestion now; the workflow will skip tests in `test/sim/**` and `test/random-battles/**` if none of the changes are in `data/**`, `sim/**` or `config/formats.ts`. Non-sim PRs (e.g this PR) run much faster now :)

I also removed the `node_modules` caching, it only worked with `npm install` and felt pretty sketchy anyway. 

All of the optimizations are for PRs only, push-to-master still runs full lint & test just in case 👍

**Comment by singiamtel** [comment]
I'm not an expert in GitHub CI, but aren't you able to do this for changed files instead?

```yaml
on:
  push:
    branches: [ master ]
    paths:
      - "config/formats.ts"
      - "data/**"
      - "sim/**"
  pull_request:
    branches: [ master ]
    paths:
      - "config/formats.ts"
      - "data/**"
      - "sim/**"
```

From [Github docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore)

**Comment by im-tofa** [comment]
> I'm not an expert in GitHub CI, but aren't you able to do this for changed files instead?
> 
> ```yaml
> on:
>   push:
>     branches: [ master ]
>     paths:
>       - "config/formats.ts"
>       - "data/**"
>       - "sim/**"
>   pull_request:
>     branches: [ master ]
>     paths:
>       - "config/formats.ts"
>       - "data/**"
>       - "sim/**"
> ```
> 
> From [Github docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore)

Didn't know this was a thing, thanks for sharing! However while this PR focuses on sim-tests, linting, building & other testing is always done. It doesn't look like this type of conditional execution is possible with the quoted suggestion without having separate workflows

**Comment by Zarel** [comment]
This is exactly what I wanted! Thank you!

**Pull request merged**
