### PR TITLE
Fix setting modchat in battles

### PR DESCRIPTION
**Pull request by mia-pi-git**
``Config.groupsranking[1]`` is now whitelist, not voice, so this needs to be changed.

### CODE REVIEW

**Comment by mia-pi-git** [comment]
Although, maybe this should be `Config.groupsranking.indexOf('+')``?
Seems easier for the future but i may be missing a usecase.

**Comment by Zarel** [comment]
I'd worry about what happens if you don't have a `+` group in your config.

**Comment by Zarel** [comment]
(That's the genius `Math.max` trick I thought of!)

**Comment by Zarel** [comment]
Good catch, by the way!

**Pull request merged**
