### PR TITLE
Add Hindi to the youtube groupwatch whitelist

### PR DESCRIPTION
**Pull request by KennedyLFC**
at the request of Arsenal, they have an event planned to watch a Hindi movie using it

### CODE REVIEW

**Comment by DaWoblefet** [comment]
Is there a reason why we have this hardcoded list if we're just going to keep adding more and more rooms to it? Let's make it something configurable through something like an admin command in roomsettings or something (to be clear you don't have to do this Kennedy).

**Comment by mia-pi-git** [comment]
TBH, I could probably just make it open to all public rooms. I doubt it'll get used enough to have too much of an issue with quota.

**Comment by AnnikaCodes** [comment]
This is Main-specific anyway, so it should be configurable by admins or at least moved to config.js, if not removed altogether.

**Comment by KennedyLFC** [comment]
could we merge this anyways just as a short-term thing? Hindi needs it for an event they have planned

**Pull request merged**
