### PR TITLE
Fix tour challenges

### PR DESCRIPTION
**Pull request by scheibo**

### CODE REVIEW

**Comment by scheibo** [comment]
Github actions is wrong.

**Comment by scheibo** [comment]
YOLO, "tests pass on my box" (ill do a followup to fix tsc if its ACTUALLY broken, but i really dont think it is)

**Comment by scheibo** [comment]
Let it be known that I was correct and GH actions is poopy

**Comment by Zarel** [comment]
Yeah, I saw GitHub Actions being weird for someone else earlier, too.

**Pull request merged**
