### PR TITLE
Change protocol for passing donor details in Inheritance

### PR DESCRIPTION
**Pull request by Spandamn**
The ability hack that i came up with years ago is no longer required, since Gen 8does not have Hidden Powers.
@KrisXV

### CODE REVIEW

**Comment by Spandamn** [comment]
> Well, not impossible, but it would break things if someone tried to use Hidden Power.

If someone tries to use Hidden Power, wont it just say wrong move at the validator

**Comment by Slayer95** [comment]
> ability hack that i came up with years ago

Fairly sure that was my own idea. But ok?

**Comment by Spandamn** [comment]
> > ability hack that i came up with years ago
> 
> Fairly sure that was my own idea. But ok?

mightve been, its been a while since gen 7

**Comment by Spandamn** [comment]
#3280 this was the one and holy shit its been 4 years

**Comment by Spandamn** [comment]
Tried it out, validator says Invalid set of you select Hidden Power as a move

**Comment by KrisXV** [comment]
I don't want to merge this; it breaks compatibility with past-gens inheritance and national dex inheritance

**Comment by Zarel** [comment]
I think Kris makes a good point. You probably want to continue using this hack for now.

**Comment by Zarel** [comment]
Closing because there's been no further discussion since Kris mentioned the NatDex/past-gens issue.

**Pull request closed without merging**
