### PR TITLE
Modlog: Add refresh button

### PR DESCRIPTION
**Pull request by Distrib-ps**

### CODE REVIEW

**Comment by AnnikaCodes** [comment]
Does anybody actually want this? Was there a suggestion or discussion among global staff?

**Comment by mia-pi-git** [comment]
With modlog, i don't see much of a point for a refresh button? 
New entries might show up, yeah, but I can see a button also getting in the way (or accidentally resetting your search) more than it being useful, personally.

**Comment by Distrib-ps** [comment]
Someone had made a suggestion (https://www.smogon.com/forums/threads/add-a-refresh-option-in-the-modlog.3677976/) she came to tell me it was good . I believed because I didn't have access to smogon all day. Sorry we didn't check.

**Comment by AnnikaCodes** [comment]
The suggestion wasn't approved and I don't recognize any of the people who "liked" it as staff of major public rooms.

**Comment by Zarel** [comment]
I posted in the thread asking for more details, but it seems like this is unlikely to get merged. I'll leave this open until it's resolved, I guess.

**Comment by HoeenCoder** [comment]
This seems to be dead and nobody has indicated interest in the proposal. I did a last call in the staff room and got no interest as well.

**Pull request closed without merging**
