### PR TITLE
LC: Ban Woobat

### PR DESCRIPTION
**Pull request by Distrib-ps**
PR for https://www.smogon.com/forums/threads/ss-lc-suspect-process-woobat-voting.3681457/post-8808892

### CODE REVIEW

**Comment by KrisXV** [comment]
You need to actually ban Woobat from the LC format as well

**Comment by Zarel** [comment]
Shouldn't its tier be LC Uber and not NFE?

**Comment by KrisXV** [comment]
no, LC Uber doesnt exist anymore

**Comment by Zarel** [comment]
I don't like using the same tier name for middle evolutions and first-stages banned from LC.

**Pull request merged**
