### PR TITLE
Random Battle: Update Greedent

### PR DESCRIPTION
**Pull request by ascriptmaster**

### CODE REVIEW

**Comment by TheImmortal** [comment]
Uh, I was going to give it Iapapa Berry. It doesn't have Sub, and it has SD so Liechi isn't helpful. Iapapa + Cheek Pouch was the plan.

**Comment by ascriptmaster** [comment]
Isn't it hard to hit the 25% threshold? That's why I went Iapapa + Gluttony. But I guess your idea works too.

**Comment by ascriptmaster** [comment]
Changed the code to allow for Iapapa with EITHER ability, since I think they're both situationally useful. Gluttony changes a 2HKO to a 3HKO, but Cheek Pouch heals more in other situations.

**Comment by TheImmortal** [comment]
I don't think the future-proofing is necessary. I've been actually cleaning the file of things irrelevant to Galar mons.

**Pull request merged**
