### PR TITLE
Stomping Tantrum and CancelMove fix

### PR DESCRIPTION
**Pull request by pacmanboss256**
fixed PR#8324

### CODE REVIEW

**Comment by Zarel** [comment]
You'd still need to refactor Pursuit and Quash not to use `cancelMove`.

**Comment by Zarel** [comment]
(Or wait for me to, I suppose, which I'll get to eventually.)

**Comment by Zarel** [comment]
(A simple temporary measure would be to just add a `forRelocation` argument to `cancelMove` which Pursuit and Quash would set to `true`.)

**Comment by pacmanboss256** [comment]
it turns out that quash doesnt use cancelMove

**Comment by Marty-D** [comment]
> Quash moving a move down in priority in Gen 7 and earlier

Zarel mentioned Gen 7 in the other PR because that's where Quash is still using `cancelMove`.

Anyway, do they really need refactoring? What are we trying to defend against by doing so? Stuff like Pursuit accidentally triggering double damage Stomping Tantrum the turn after it hit a Pokemon switching out? I'm not convinced that happens, but maybe there should be tests written to that effect.

**Comment by pacmanboss256** [comment]
i dont think it matters actually because switching out with pursuit means you need to bring a new pokemon in, and then you would spend the turn that would double stomping tantrum swapping back into the original pokemon.

**Comment by Marty-D** [comment]
I thought it would be clear I'm talking about the Pursuit user also using Stomping Tantrum, since that is the Pokemon that had its move canceled.

**Comment by pacmanboss256** [comment]
ah

**Pull request closed without merging**
