### PR TITLE
Fix Clangorous Soul

### PR DESCRIPTION
**Pull request by ZardMX**
It should not fail if one stat is +6 stages, rather when all stats are +6 stages.
Proof: https://www.youtube.com/watch?v=-LLt-bnoQss (Thanks KennedyLFC)

### CODE REVIEW

**Comment by urkerab** [comment]
You should probably add parentheses for readability.

**Comment by ZardMX** [comment]
Actually it doesn't fail at when all stats +6 stages either, rather says "Stat won't go any higher!" but doesn't reduce the HP.

**Comment by urkerab** [comment]
So, this depends on what happens when Contrary is combined, but one approach is to remove the `boosts` from the move data and add it in the hit function, something like this:

    if (this.boost{atk: 1, def: 1, spa: 1, spd: 1, spe: 1}) {
       this.directDamage(pokemon.maxhp / 3);
    }

**Comment by ZardMX** [comment]
@urkerab then Clangorous Soul won't show up while using /ms boosts

**Comment by DaWoblefet** [comment]
Clangorous Soul will lower stats and reduce HP if it is at +6 all with Contrary. Clangorous Soul will say "< Pokemon >'s < stat > won't go any lower!" and not reduce HP if it is at -6 all with Contrary.

**Pull request closed without merging**
