### PR TITLE
Items: Add descriptions for Strange Ball

### PR DESCRIPTION
**Pull request by PartMan7**
I think this is the only item that doesn't have a description? Was adding types for ps-client and found this

https://bulbapedia.bulbagarden.net/wiki/Strange_Ball for reference

### CODE REVIEW

**Comment by DaWoblefet** [comment]
We normally use "Poke Ball" in descriptions.

**Comment by PartMan7** [comment]
Updated; thanks for mentioning!

**Comment by DaWoblefet** [comment]
I want to double check that Strange Ball doesn't have a desc when hacked in. I'm pretty sure it doesn't, so if not, this is as good of one as any.

**Comment by DaWoblefet** [comment]
Thanks!

**Pull request merged**
