### PR TITLE
Moderation: visualize mute times with less precision

### PR DESCRIPTION
**Pull request by mia-pi-git**
This part of this change seems to annoy everyone, and it's not useful for the main chat.

### CODE REVIEW

**Comment by Zarel** [comment]
This was a bug which will be fixed soon and fixed everywhere, not just in mute messages.

**Comment by Zarel** [comment]
Did... did someone hotpatch my change? I was hoping I could fix it before it got hotpatched.

**Comment by mia-pi-git** [comment]
It was hotpatched, yes.

**Comment by Zarel** [comment]
Can someone just fix it properly? :[

**Comment by Zarel** [comment]
Ugh I'll fix it in the web editor I guess.

**Comment by mia-pi-git** [comment]
> Can someone just fix it properly? :[

Is this not the proper way..? The problem is only here.

**Comment by Zarel** [comment]
Note to self, fixing it on my iPad is easier than fixing it in the web editor.

**Comment by Zarel** [comment]
Also note to self, fixing it in a monkeypatch is easier than fixing it in the web editor.

**Pull request closed without merging**
