### PR TITLE
Trivia: remove Weakest Link

### PR DESCRIPTION
**Pull request by AnnikaCodes**
Weakest Link is no longer played in the Trivia room and the ROs agreed that it'd be ok to remove it.

### CODE REVIEW

**Comment by Zarel** [comment]
Is there a need to remove something just because no one uses it? Maybe someone wants to run their own Weakest Link game in a groupchat or side server? Is it a maintenance burden?

**Comment by AnnikaCodes** [comment]
> Is there a need to remove something just because no one uses it? Maybe someone wants to run their own Weakest Link game in a groupchat or side server? Is it a maintenance burden?

If someone were to typescript trivia or change anything that Weakest Link uses then yes, it would be a maintenance burden. I suppose side servers could host it, that's a fair point — I don't know how much importance we place on the activities of side servers but if that's an issue then I can close this pull request. (Weakest Link and Trivia only work in the Trivia room, so it couldn't be hosted in a groupchat.)

**Comment by Zarel** [comment]
It really depends on how hard it is to maintain, and why people don't play it anymore. Do most people consider it not very fun? How hard would it be to continue maintaining? You've worked on Trivia more than me, so I'll let it be your decision.

**Comment by mia-pi-git** [comment]
Can confirm it's a burden - I'm working on typescripting trivia right now and this is an obnoxious barrier towards completion.

**Comment by AnnikaCodes** [comment]
> It really depends on how hard it is to maintain, and why people don't play it anymore. Do most people consider it not very fun? How hard would it be to continue maintaining? You've worked on Trivia more than me, so I'll let it be your decision.

Weakest Link hasn't been hosted at all in the time I've been in Trivia; I believe this is because it was unbalanced as a game and thus not very fun to play - I've never played myself but apparently when it was hosted a lot of regs and auth were unhappy with it. Knowing that and what @mia-pi-git said about it being a maintenance issue, I would think that keeping Weakest Link is more work than it's worth.

**Comment by Zarel** [comment]
Sounds good, thanks for explaining it to me!

**Comment by xfix** [comment]
Can confirm Weakest Link sucks, and nobody cares in Trivia room cares about it.

**Pull request merged**
