### PR TITLE
GitHub Actions: Fix auto-publishing CI

### LINKED ISSUE #9428: Update the npm package
Hi there! I was trying to install the package locally on my machine, however I keep running into typescript compilation errors.

I asked around on the Typescript discord, and after investagion we found that the issue was due to this export in this file
```typescript
// node_modules/pokemon-showdown/.sim-dist/index.d.ts
export * from '../lib';
```
However this issue appears to have since been fixed in this repository, and just requires being published to npm

### PR DESCRIPTION
**Pull request by Dirain1700**
Fixes #9428 #9470 

[sample workflow run](https://github.com/Dirain1700/workflows-test/actions/runs/4692304781)

The CI has a problems:

- This workflow runs on forks
- postinstall occures error on published ([ref](https://github.com/smogon/pokemon-showdown/issues/9428#issuecomment-1507121632), it occured on my local, package is wrong)

Fixed these problems and minimized files. Also, I ran `npx prettier -w --tab-widh=4 github/`

### CODE REVIEW

**Comment by Zarel** [comment]
Second is fixed by 5b941ac658d0fce73111c8fa7c8a73d3c086a3ab

I'm not sure I understand how you fixed the first?

**Comment by Dirain1700** [comment]
If you enabled actions in the folk, Publishing CI works on the folk againt contributor's will.
Also, this PR contains Refactor of the PR which I mentioned.
(I'm rebasing about your commit)

**Comment by Zarel** [comment]
We've now fixed both issues. It's unclear to me what the point of the refactor is. I don't believe merging the two separate actions into one file is a good thing? I also am confused about why we need prettier?

**Comment by Dirain1700** [comment]
I dont need this once 9519 have merged, so I'm closing this.

**Comment by Dirain1700** [comment]
(tbh i tried minimize files, it can be in 1 file)

**Pull request closed without merging**
