### PR TITLE
RoomGame: Uncomment optional functions

### PR DESCRIPTION
**Pull request by TheJetOU**
TypeScript will now recognizes these functions existence so
we don't have to supress the compiler whenever they come up.

### CODE REVIEW

**Comment by whalemer** [comment]
There's stuff like `/forfeit` and friends that check for if these functions exist to return a "not supported" message, you might want to return a similar message from the default implementation instead.

**Comment by TheJetOU** [comment]
> There's stuff like `/forfeit` and friends that check for if these functions exist to return a "not supported" message, you might want to return a similar message from the default implementation instead.

Those commands don't return the function though, they just run them. So, you'd need to refactor them in some way which doesn't seem worth the effort.

**Comment by Zarel** [comment]
Having these be nullable is nice especially since we're switching to allowing multiple games in the same room; if only one of them has a `choose` function, `/choose` is unambiguous.

**Comment by whalemer** [comment]
Should these default to null, then? Right now you'd need to explicitly null them for that to work.

**Comment by Zarel** [comment]
Null and undefined work the same way. Feel free, but it's not a big deal here.

**Comment by whalemer** [comment]
Oh, my bad, was misunderstanding syntax.

**Pull request merged**
