### PR TITLE
Don't display Weight for GMax Pokemon

### PR DESCRIPTION
**Pull request by PartMan7**
Alternatively, I can make it display `` Weight: 0 kg`` over `` Weight: 0 kg (20 BP)``.

### CODE REVIEW

**Comment by KrisXV** [comment]
It would probably be better to display the weight as `Weight: 0 kg` since they still have a weight

**Comment by Zarel** [comment]
maybe "(GK/LK fail)"

**Comment by PartMan7** [comment]
Implemented. On the other hand, what are your thoughts on using something like ``Weightless`` instead of the Weight flag, and accordingly modifying the ``desc``s for weight-based moves to specify that they fail against Weightless Pokemon?

**Comment by Zarel** [comment]
That seems uglier, to me.

**Pull request merged**
