### PR TITLE
Update Italian translations

### PR DESCRIPTION
**Pull request by palt0**
Adds missing translations of helptickets and fixes a few typos.

(On a side note, yesterday we translated repeats too but I'll wait for #7746 and submit the updated translations separately.)

### CODE REVIEW

**Comment by Zarel** [comment]
Thanks! @AnnikaCodes can you find someone to proofread this?

**Comment by palt0** [comment]
I showed Alpha these changes before opening the PR.

**Comment by AnnikaCodes** [comment]
(confirmed)

**Comment by Zarel** [comment]
Thanks!

**Pull request merged**
