### PR TITLE
Prepare [Gen 3] Hoenn Gaiden OU for Pet Mod of the Season

### PR DESCRIPTION
**Pull request by Petuuuhhh**
DM me (yakattack_, Yak Attack on Smogon), Rezzo, or Scoopapa on either Discord or Smogon for any questions or concerns. All Abilities, moves, and items have been tested and are functional.

Note: Our mods usually run a ruleset mod called "Data Mod" so that the types, Abilities, and stats of altered Pokemon/Fakemon are broadcast to the chat. If this is too much, I can remove it. Stat Boost Pass Mod, however, is crucial for the Hoenn Gaiden experience, and is also located in the main rulesets file.

I will be porting the Dragon Heaven client to main so that our mods can have mod support as well, so look out for that PR, too. The sprites folder is entirely for the client's functionality. Note that I am doing this regardless of whether or not it's approved, i.e. if it's disapproved, I'll still do it for personal use, so no worries if it isn't approved, lol.

Thank you.

### CODE REVIEW

**Comment by DaWoblefet** [comment]
> I will be porting the Dragon Heaven client to main so that our mods can have mod support as well, so look out for that PR, too. The sprites folder is entirely for the client's functionality. Note that I am doing this regardless of whether or not it's approved, i.e. if it's disapproved, I'll still do it for personal use, so no worries if it isn't approved, lol.

Can you talk about what the sprites are for in the context of this mod? Like, what about this mod specifically needs static sprites of a few of the modern Pokemon? If they are needed, they probably should live on the client, not the server.

**Comment by Petuuuhhh** [comment]
> > I will be porting the Dragon Heaven client to main so that our mods can have mod support as well, so look out for that PR, too. The sprites folder is entirely for the client's functionality. Note that I am doing this regardless of whether or not it's approved, i.e. if it's disapproved, I'll still do it for personal use, so no worries if it isn't approved, lol.
> 
> Can you talk about what the sprites are for in the context of this mod? Like, what about this mod specifically needs static sprites of a few of the modern Pokemon? If they are needed, they probably should live on the client, not the server.

ViZar (council member for Hoenn Gaiden) says they're not necessary unless we add client support. I would be willing to add them to the client. I wasn't sure where they should go.

**Comment by Petuuuhhh** [comment]
Okay, so I removed the sprites. However, they are still in the commit history. I can revert, add the files again in a new commit, and force push?

**Comment by Petuuuhhh** [comment]
Okay so I accidentally did what I was asking about anyway, hope that's okay.

**Comment by Petuuuhhh** [comment]
Based on Rezzo's comments, there's a lot more to be tested than I thought. Closing this, will open a separate PR once testing is complete.

**Pull request closed without merging**
