### PR TITLE
Fix trustuser commands

### PR DESCRIPTION
**Pull request by asgdf**
Currently, untrustuser straight up doesn't work, presumably because things are set up slightly differently now.

### CODE REVIEW

**Comment by Zarel** [comment]
Looks good, although I wonder if these should just alias to `/globalwhitelist` and `/globaldeauth`.

**Comment by Zarel** [comment]
(conflict)

**Comment by asgdf** [comment]
In terms of conflict resolution this looks about right I think?

I haven't been paying attention to the whitelist stuff, does "whitelist" supplant the "manual trustuser" concept?

**Comment by asgdf** [comment]
o shoot I forgot to push my updated version that fixes those warnings

**Comment by Zarel** [comment]
> I haven't been paying attention to the whitelist stuff, does "whitelist" supplant the "manual trustuser" concept?

"Whitelist" is a new rank between regular user and voice, which does not have a symbol (they look exactly the same as regular users).

It's implemented in the code as having an explicit rank equal to the implicit default rank - basically exactly the same way explicitly trusted users were implemented in the past. I don't know if "supplant" is the right word; it was implemented for room ranks, but the implementation is generic enough that it should work fine for global ranks as well.

**Comment by asgdf** [comment]
It seems theoretically possible to refactor trustuser to use that system, though I imagine it would involve somewhat more effort than just setting up some aliases

**Comment by Zarel** [comment]
Fair. This is a good incremental step.

**Pull request merged**
