### PR TITLE
Youtube: Support auto-recaching data

### PR DESCRIPTION
**Pull request by mia-pi-git**
I'm splitting this off from #7006, since this can happen before SQLite - that cannot.

### CODE REVIEW

**Comment by Zarel** [comment]
Why would you want it to auto-recache? Like I've said before, I think it makes more sense to just store a last update time, and ignore the cache if it's too old.

**Comment by Zarel** [comment]
Otherwise it seems like you're making extra HTTP requests from Main for no reason?

**Comment by sparkychildcharlie** [comment]
I have no experience with working with youtube APIs, but would auto updating all the data cause youtube to block PS's requests to it to prevent "DDoS"?  Once the list of channels expands into the hundreds, Youtube might not like being sent 100+ requests in under 100ms.  Last time I wrote a script to grab data from multiple pages at a time from serebii, I got blocked until I started pulling the data (some 200+ pages) one at a time at an interval of 1 second.

**Comment by mia-pi-git** [comment]
> Why would you want it to auto-recache? Like I've said before, I think it makes more sense to just store a last update time, and ignore the cache if it's too old.

Yes, but historical data :( 
I suppose I could track a update time for each chunk of data in the array and have it make a new request if that time is too old, and attach the data to the front of the array. From there, it'd probably be better to see a time for each data point in a trend.

**Comment by mia-pi-git** [comment]
On reflection, though, it would be an issue to do that cleanly in SQLite. I'm not really sure what the best solution for this is, so I guess I'll test a few different options and push the most efficient  one.

**Comment by Zarel** [comment]
Depending on how often this is used, I don't think it's worth spamming YouTube with requests from Main. I think if you want to do this, it should go in a bot.

**Comment by mia-pi-git** [comment]
> Depending on how often this is used, I don't think it's worth spamming YouTube with requests from Main. I think if you want to do this, it should go in a bot.

Alright, I can rework historical data to accommodate just using a last cached time.

**Comment by mia-pi-git** [comment]
Nuking this as well - even with the increased queries this would suck a lot.

**Pull request closed without merging**
