### PR TITLE
Trivia: Split help command up into sections

### PR DESCRIPTION
**Pull request by panpawn**

### CODE REVIEW

**Comment by Zarel** [comment]
Um, I didn't know we supported functions in `[command]help`...

**Comment by Zarel** [comment]
How well does this work? I'm also less sure this is a good idea, I think it might be better just to support sections in the array-help.

**Comment by Morfent** [comment]
I don't think using a function for a help command like this is such a good idea. I think following what the tournaments plugin does by giving a brief summary of what some of its commands do, then putting the more detailed information in a [Smogon post](https://www.smogon.com/forums/threads/3570628/#post-6777489) would work better without having to deviate from help API

**Comment by panpawn** [comment]
@Morfent - do you want to make the Smogon post?

**Comment by Morfent** [comment]
I'll write it

**Comment by Morfent** [comment]
Guide's here www.smogon.com/forums/threads/trivia-chat-plugin-guide.3612606/

I think it'd be fine to remove the mode/category/score cap information from /help trivia with the guide added. I don't think it's necessary to use HTML for this though. Just send the entire thing in a `this.sendReplyBox` call

**Comment by Morfent** [comment]
Guide was moved [here](http://www.smogon.com/forums/threads/pok%C3%A9mon-showdown-forum-rules-resources-read-here-first.3570628/#post-7477608)

**Comment by panpawn** [comment]
@Morfent - is this still something you'd want done?

**Comment by AnnikaCodes** [comment]
Trivia's help message now has a scrollbar.

**Comment by Zarel** [comment]
Can Trivia's scrollbar be converted to a readmore?

**Comment by Zarel** [comment]
(If you wanted to be fancy, you could default to collapsed when broadcast and expanded otherwise.)

**Comment by AnnikaCodes** [comment]
That's definitely something that can happen

**Comment by AnnikaCodes** [comment]
Although I think it'd be more useful to have an infobox and put the different sections (modes, question management commands, etc) in their own individual `<details>` blocks.

**Pull request closed without merging**
